### ISSUE TITLE
Add flake8 to tests or black to CI

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#106]
Currently it looks like PRs can pass tests without passing flake8 tests.  Do we want to start enforcing style?

**Comment by jhamman** [comment]
Do we want to start enforcing style?

I would like this. Is there a standard flake8 config and way to enforce this for dask sub projects?

**Comment by mrocklin** [comment]
Nothing fully standard.  We could grab the setup.cfg from dask/dask or
dask/distributed

**Comment by jhamman** [comment]
See #109. As far as I can tell, we've been running flake8 all along. Maybe @lesteve or @guillaumeeb has some idea why things weren't being raised in #78.

**Comment by guillaumeeb** [comment]
I remember asking myself if the none.sh job_script function would show something in Travis if flake checks failed.

The thing that troubled me is that we are running flake8 and py.test in one Travis operation. Maybe we should add a && between the two calls to take into account both return codes?

**Comment by guillaumeeb** [comment]
Closed with #110.
