### ISSUE TITLE
Include nbserverproxy or describe how to use it in the docs

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#111]
See https://github.com/dask/dask-jobqueue/issues/80#issuecomment-400797727.

To prevent from doing a lot of ssh tunneling, using [`nbserverproxy`]( https://github.com/jupyterhub/nbserverproxy ) could be helpful!

**Comment by guillaumeeb** [comment]
Cross referencing the work of @jhamman on https://github.com/pangeo-data/pangeo/pull/304 here, this already work in progress!

**Comment by jakirkham** [comment]
Probably worth linking [this comment]( https://github.com/dask/dask-jobqueue/issues/80#issuecomment-400947329 ) as well since that has a little more details about how to set it up. Not that there is much to setup at all.

**Comment by guillaumeeb** [comment]
@jakirkham, I tried nbserverproxy with no luck, as mentionned in pangeo thread. Could you look at it to see if you're doing things differently? I'll give it another go when I have some time.

**Comment by raybellwaves** [comment]
@guillaumeeb I was the same. I ended up opening an issue over there https://github.com/jupyterhub/nbserverproxy/issues/45 but closed it once I had the `ssh` solution working.

**Comment by guillaumeeb** [comment]
Okay, so I've found the problem with my setup : Dask dashboard was bind to a given network interface, but apparently nbserverproxy was not able to proxy to this one, it was probably trying another interface, don't know why though.

So in order to make nbserverproxy work, I add to use the trick described in #90: bind the dashboard to all interfaces.

**Comment by guillaumeeb** [comment]
@raybellwaves, could you give another go to nbserverproxy solution, now that #119 is in master?

**Comment by raybellwaves** [comment]
I haven't actually used jupyterhub before so you may want to ask someone with more experience than I. I still gave it a go though and my build notes from scratch are below. I made it as far as to 'sign up with github button' but it wasn't really responding after that

```
$ conda create -n djq_nbs python=3.6
$ conda activate dqj_nbs
$ pip install git+https://github.com/dask/dask-jobqueue.git
$ conda install -c conda-forge psutil jupyterhub nbserverproxy bokeh
$ pip install install oauthenticator
$ jupyter serverextension enable --py nbserverproxy
$ jupyterhub --generate-config

# Not sure if now needed with github login method
$ openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj '/CN=XX.XXX.XXX.XXX'
# Horrible hack to get rid of bad password phrase error when starting jupyterhub ( https://github.com/jupyterhub/jupyterhub/issues/1134; https://github.com/mcollina/mosca/issues/421)
$ cp key.pem key.old.pem
$ openssl rsa -in key.pem -out newkey.pem

# use github for logging in https://github.com/settings/applications/new
# Setup as environmental files (in your .bashrc
OAUTH_CALLBACK_URL=https://XX.XXX.XXX.X:8000/hub/oauth_callback
GITHUB_CLIENT_ID=xxx
GITHUB_CLIENT_SECRET=xxx

# edit jupyterhub_config.py:
import os
from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator
c.MyOAuthenticator.oauth_callback_url = 'https://XX.XXX.XXX.X:8000/hub/oauth_callback'
c.MyOAuthenticator.client_id = 'XXX'
c.MyOAuthenticator.client_secret = 'XXX'
c.JupyterHub.admin_access = True
c.Authenticator.admin_users = {'GITHUBUSERNAME'}
c.JupyterHub.ssl_key = 'newkey.pem'
c.JupyterHub.ssl_cert = 'cert.pem'
c.Authenticator.whitelist = {'GITHUBUSERNAME'}
c.LocalAuthenticator.create_system_users = True

$ jupyterhub --ip XX.XXX.XXX.XXX --port 8000

# On laptop open https://XX.XXX.XXX.XXX:8000
```

**Comment by guillaumeeb** [comment]
@raybellwaves ah sorry, I did not make myself clear enough. I just wanted you to test the nbserverproxy solution with your current procedure : user launched notebook. Something like that : 

````
pip install git+https://github.com/dask/dask-jobqueue.git
pip install nbserverproxy
jupyter serverextension enable --py nbserverproxy
jupyter lab --no-browser --ip=`hostname` --port=8888
````

Do the ssh tunneling thing to access to your notebook (and only your notebook). Then in your notebook, launch Dask using jobqueue, and go to
````
http://localhost:8888/proxy/8787/status
````
or wathever port Dask Dashboard has been launched to.

**Comment by raybellwaves** [comment]
No problem. I've been meaning to try jupyterhub for a while anyway so it was a good learning experience.

Ok. I'll give it a go later or tomorrow.

**Comment by guillaumeeb** [comment]
That's better.
Were your workers started at that moment?

**Comment by raybellwaves** [comment]
Yes. I just checked again.

Actually it works now if I just click on the dashboard link

<img width="530" alt="screen shot 2018-08-10 at 4 15 36 pm" src="https://user-images.githubusercontent.com/17162724/43979446-cc794e7c-9cb8-11e8-8a5c-1ce77a2dfdce.png">

<img width="847" alt="screen shot 2018-08-10 at 4 14 18 pm" src="https://user-images.githubusercontent.com/17162724/43979456-d4a258a0-9cb8-11e8-9edc-f52fd6f47bc2.png">

I may do a quick test without `nbserverproxy`. I think your recent PR's helped my problem in https://github.com/dask/dask-jobqueue/issues/116#issue-347245340

**Comment by guillaumeeb** [comment]
@raybellwaves it looks like you're not using nbserverproxy in your last comment. Is is probably as you say, just the binding to all interface that solved your problem.

Could you try again with the http://`localhost`:8888/proxy/`dashboardport`/status URL? Maybe its what you just did and there still was a problem?

**Comment by raybellwaves** [comment]
> it looks like you're not using nbserverproxy in your last comment

Correct. It seems to work without `nbserverproxy` for me now.

> Could you try again with the http://localhost:8888/proxy/dashboardport/status URL?

Yes. I made sure that my jobs were running. I still get the empty dashboard as shown above
I don't think I am missing something in the setup of the `nbserverproxy`?

**Comment by guillaumeeb** [comment]
> Yes. I made sure that my jobs were running. I still get the empty dashboard as shown above
I don't think I am missing something in the setup of the nbserverproxy

You could be on a dashboard from another cluster, maybe the dashboard port is not the right one.

**Comment by jakirkham** [comment]
It sounds like this is a bug fixed in `master`. Though downgrading should be equally effective at resolving the issue.

xref: https://github.com/jupyterhub/nbserverproxy/issues/39
