### ISSUE TITLE
Edge cases of Cluster.scale()

### ISSUE THREAD

**Issue by jhamman** [dask/dask-jobqueue#112]
Consider a simple jobqueue cluster:

```Python
from dask_jobqueue import FooCluster
cluster = FooCluster(cores=1, processes=1)
```

What should the behavior of the following cases be:

```Python
cluster.scale(2)
# run immediately
cluster.scale(0)
```

Currently, pending jobs are not removed from the cluster and eventually come on line. This is producing some buggy behavior. 

or 

```Python
cluster.scale_up(4)
cluster.scale_up(2)
```

Currently, the second scale_up call is a no-op but 4 workers will come online. Should we update the target number of workers or inform the user that scaling up to beyond 2 is already pending?

**Comment by mrocklin** [comment]
I think that scale should set a target state that the system should try to
achieve.  After waiting a suitable amount of time I would expect the number
of workers to match the most recent scale call.  I think that in both cases
we would ideally cancel the pending jobs.  Presumably we would call qdel
(or equivalent) on the pending jobs before moving on to ask the scheduler
to remove workers.

**Comment by guillaumeeb** [comment]
So this one is actually not closed.
