### ISSUE TITLE
Can't access dashboard

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-jobqueue#116]
Apologies for bringing this up again as it has been discussed in https://github.com/dask/dask-jobqueue/issues/71 and https://github.com/dask/dask-jobqueue/issues/80. The discussions in those haven't helped. Hopefully this is a quick fix and I can show my colleagues how cool the `LFSCluster` is :)

I tried the example from pangeo (http://pangeo-data.org/setup_guides/hpc.html#deploy-option-1-jupyter-dask-jobqueue).

Start a jupyter notebook on the HPC as: 
`jupyter notebook --no-browser --port 8888`. 
Then on my laptop I try: 
`ssh -N -L 8888:localhost:8888 -L 8787:localhost:8787 rxb826@pegasus.ccs.miami.edu`
This gives:
```
channel 4: open failed: connect failed: Connection refused
channel 5: open failed: connect failed: Connection refused
```
In this case I can't access http://localhost:8888 let alone the dashboard. I'm not quite sure why this happens. 
![screen shot 2018-08-02 at 10 50 31 pm](https://user-images.githubusercontent.com/17162724/43621629-846d2e5e-96a6-11e8-8d27-1ce12bfd66af.png)
I've had success in the past with tunneling notebooks as `ssh -N -L 8888:localhost:8888 rxb826@pegasus.ccs.miami.edu`. When I haven't even been able to connect to http://localhost:8888 restarting my laptop seems to work (i'm sure there is a less drastic fix).

Next I tried the example in the docs https://dask-jobqueue.readthedocs.io/en/latest/examples.html?highlight=tunnel#viewing-dask-dashboard

Start ipython on the HPC and inspect the client:
<img width="474" alt="screen shot 2018-08-02 at 10 52 49 pm" src="https://user-images.githubusercontent.com/17162724/43621712-d4f3fda8-96a6-11e8-93f3-7da61219f746.png">

Then on my laptop use this address for tunneling: `ssh -fN rxb826@10.10.0.14 -L 8787:localhost:8787`. Then when I try to connect to http://localhost:8787 I see:
![screen shot 2018-08-02 at 11 01 12 pm](https://user-images.githubusercontent.com/17162724/43621994-f9c76678-96a7-11e8-86a5-5de56434196c.png)

It seems I can't ping this address
<img width="305" alt="screen shot 2018-08-02 at 11 14 05 pm" src="https://user-images.githubusercontent.com/17162724/43622376-cb63cc0c-96a9-11e8-8551-a9197a61f87f.png">

I sent this to my IT dept as well. Will update with any info at that end.

**Comment by guillaumeeb** [comment]
Hi @raybellwaves.

First, we will try to make the tunneling work for jupyter. Could you show the logs of Jupyter? Especially if it tells something like : 
````
[I 07:24:22.377 LabApp] The Jupyter Notebook is running at:
[I 07:24:22.377 LabApp] http://node054.sis.cnes.fr:8877/
````

Then, use this url for tunneling, e.g. in my case : 
````
ssh -L 8877:node046.sis.cnes.fr:8877 user@hal.sis.cnes.fr
````

**Comment by raybellwaves** [comment]
```
[I 21:57:04.885 LabApp] The Jupyter Notebook is running at:
[I 21:57:04.885 LabApp] http://localhost:8888/?token=...
```
My tunneling command is:
```
ssh -L 8888:localhost:8888 rxb826@pegasus.ccs.miami.edu
```
This tunneling works. Thanks
<img width="901" alt="screen shot 2018-08-03 at 10 15 31 pm" src="https://user-images.githubusercontent.com/17162724/43671584-d71a7a34-976a-11e8-973b-347132e79ddc.png">

Now clicking on the dashboard http://10.10.0.13:8787/status I get:
<img width="281" alt="screen shot 2018-08-03 at 10 17 09 pm" src="https://user-images.githubusercontent.com/17162724/43671595-073767b8-976b-11e8-9556-b59e39b5ce13.png">

My IT dept got back to me and noted that port 8787 is not open on the cluster.
```
[rxb826@pegasus ~]$ netstat -nl | grep 8787
tcp        0      0 10.10.0.13:8787             0.0.0.0:*                   LISTEN  
[rxb826@pegasus ~]$ netstat -nl | grep 8888
tcp        0      0 127.0.0.1:8888              0.0.0.0:*                   LISTEN      
tcp        0      0 ::1:8888                    :::*                        LISTEN
```

If there I way I change the dask dashboard port to try something else?

**Comment by jhamman** [comment]
I'm not sure why but it looks like the dashboard is not being served from localhost (127.0.0.1) as is the case for your notebook server.

**Comment by raybellwaves** [comment]
@jakirkham thanks [nbserverproxy](https://github.com/jupyterhub/nbserverproxy) looks promising but I can't seem to get it working:

```
(djq_lsf) [rxb826@pegasus ~]$ conda install -c conda-forge nbserverproxy
(djq_lsf) [rxb826@pegasus ~]$ jupyter serverextension enable --py nbserverproxy
Enabling: nbserverproxy
- Writing config: /nethome/rxb826/.jupyter
    - Validating...
      nbserverproxy  OK
(djq_lsf) [rxb826@pegasus ~]$ jupyter lab --no-browser
[I 00:13:06.932 LabApp] The Jupyter Notebook is running at:
[I 00:13:06.932 LabApp] http://localhost:8888/?token=...
```
Open http://localhost:8888 on my laptop and try the [README example](https://github.com/jupyterhub/nbserverproxy#example)
<img width="769" alt="screen shot 2018-08-04 at 12 21 12 am" src="https://user-images.githubusercontent.com/17162724/43672461-5bb26b4c-977c-11e8-916f-ea021b5dbc4c.png">

<img width="291" alt="screen shot 2018-08-04 at 12 21 47 am" src="https://user-images.githubusercontent.com/17162724/43672464-6ecf16da-977c-11e8-8259-8343fc63a248.png">

<img width="542" alt="screen shot 2018-08-04 at 12 23 10 am" src="https://user-images.githubusercontent.com/17162724/43672485-bff96e70-977c-11e8-818c-bc101051f463.png">

**Comment by raybellwaves** [comment]
http://pangeo-data.org/setup_guides/hpc.html#deploy-option-1-jupyter-dask-jobqueue did have the solution after all.

I would open `ipython` and inspect the `client`
```
In [1]: from dask_jobqueue import LSFCluster

In [2]: from dask.distributed import Client

In [3]: cluster = LSFCluster(cores=2, memory='4 GB', walltime='00:02')

In [4]: client = Client(cluster)

In [5]: client
Out[5]: <Client: scheduler='tcp://10.10.0.14:42151' processes=0 cores=0>
```

Next I would use that ip to start my notebook `jupyter notebook --no-browser --ip=10.10.0.14 --port=8888`

Then on my laptop tunnel as `ssh -N -L 8888:10.10.0.14:8888 rxb826@pegasus.ccs.miami.edu` and open http://localhost:8888. Work though the notebook and inspect the `client`. The dashboard will most likely by port 8787 but sometimes it'll be a five digit port number e.g. 54611. Open another terminal and tunnel the dashboard as `ssh -N -L 54611:10.10.0.14:54611 rxb826@pegasus.ccs.miami.edu`. Lastly, open http://localhost:54611 on my laptop.

I can make a change to the docs if agreed https://dask-jobqueue.readthedocs.io/en/latest/examples.html?highlight=dashboard#viewing-dask-dashboard

**Comment by guillaumeeb** [comment]
It is true that this part of the docs is a little misleading with the localhost everywhere, any improvement welcome!
