### ISSUE TITLE
How to scale manually during computation in a notebook

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#120]
For demonstration purpose, I would like to show the possibility of manually scaling the cluster size during a computation. I just don't know how to do it from a running notebook or if it is possible.

Should I use adaptive scaling ?
I try to use the ipywidget of cluster with no luck, scaling was triggered after current computation.

**Comment by guillaumeeb** [comment]
Adaptive is a good solution, but I'm still interested to know if there is a way to do it manually.

**Comment by mrocklin** [comment]
You would call an asynchronous function, like persist, rather than
compute.  That way you'll still have access to the notebook.

**Comment by guillaumeeb** [comment]
Thanks @mrocklin! With hindsight, sorry for the lack of description in this issue. For some background, I was playing with the dask-example on time series : 
````python
import dask.dataframe as dd
df = dd.demo.make_timeseries('2000-01-01', '2020-12-31', freq='1s', partition_freq='1M',
                             dtypes={'name': str, 'id': int, 'x': float, 'y': float})
df[['x', 'y']].resample('1w').mean().compute()
````

So I think your answer is perfect, because my question was about Dataframe.

For the record, it is easily feasible with Future API using Client, that's a similar behavior I was trying to achieve with Dataframes:
```python
import pandas as pd
import numpy as np
input_params = pd.DataFrame(np.random.randint(low=0, high=1000, size=(1000, 4)),
               columns=['a', 'b', 'c', 'd'])
futures = client.map(my_costly_simulation, input_params.values)
```

Some questions though:
* Does'nt using persist imply to have enough memory on your workers? 
* Is there another method like client.submit wich would return a future? 
* Say that I have a really IO bound computation and I want to transform or reorganise some tabular data, no reduction at all, all the data will not fit into memory, and I want to trigger computation asynchonously. Can I do that?

**Comment by guillaumeeb** [comment]
Ok thanks, that's fine for me!
