### ISSUE TITLE
LSFCluster won't start workers

### ISSUE THREAD

**Issue by adamhaber** [dask/dask-jobqueue#123]
Hi,

I'm trying to follow the example given in #78 and I get the following error message:
```
In [1]: from dask_jobqueue import LSFCluster
In [2]: from dask.distributed import Client  
In [3]: cluster = LSFCluster(queue="new-medium", cores=8, walltime='00:02', memory="4GB")
In [4]: client = Client(cluster)
In [5]: cluster.start_workers(2)  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)                            
<ipython-input-6-1f2ad40cf5bd> in <module>()       
----> 1 cluster.start_workers(2)                   

~/miniconda3/lib/python3.6/site-packages/dask_jobqueue/core.py in start_workers(self, n)               
    302             with self.job_file() as fn:    
    303                 out = self._submit_job(fn) 
--> 304                 job = self._job_id_from_submit_output(out.decode())                            
    305                 logger.debug("started job: %s" % job)                                          
    306                 self.pending_jobs[job] = {}

~/miniconda3/lib/python3.6/site-packages/dask_jobqueue/lsf.py in _job_id_from_submit_output(self, out) 
    107                  
    108     def _job_id_from_submit_output(self, out):                                                 
--> 109         return out.split('<')[1].split('>')[0].strip()                                         
    110                  
    111     def _submit_job(self, script_filename):

IndexError: list index out of range
```

Some additional details:
 dask_jobqueue - 0.3.0+18.gbe20cad'
python version - 3.6.5
OS - Linux RedHat 7.3

ADD: `cluster.scale(2)` gives the same error.

Any help would be appreciated.

**Comment by guillaumeeb** [comment]
Hi, 

Could you just submit a job to your cluster and give us the ouput that is printed on you screen?

It looks like when submitting the job launching workers to LSF, we did not get the exepected output, something like:
````
Job <1234> is submitted to default queue <normal>
````

Additionnaly, can you precise how you submit job to your cluster? Our code uses 
````
bsub < job_script
````

Finaly, you could try to submit a for launching workers yourself.
In python :
````python
print(cluster.job_script())
````
Then just copy and paste that into a job script file, something like `worker_job_lsf.sh` or whatever, and submit it to your cluster to see the output:
````
bsub < worker_job_lsf.sh
````

**Comment by adamhaber** [comment]
Found the error - it has to do with resource requirements and `bsub` flags .

When I submit a job using the following command:
```
bsub -q new-medium -J adam[1-2] -o o-%I.txt -e e-%I.txt -R rusage[mem=4000] python tmp.py 
```

I get:
```
Memory reservation is (MB): 4000
Memory Limit is (MB): 4000
Job <967090> is submitted to queue <new-medium>.
```
This is my usual workflow. However, the job script create by dask uses the `-M` flag. This raises the following error:
```
MEMORY LIMIT GREATER THEN MEMORY RESERVED, NOT PERMITED
RESERVED MEMORY(MB): 2048 MEMORY LIMIT(MB): 4000
Request aborted by esub. Job not submitted.
```

The solution: append the memory request manually using the `job_extra` argument, for example:
```
cluster = LSFCluster(queue="new-medium", cores=8, walltime='00:02', memory="4G", job_extra=['-R rusage[mem=4000]'])
```

Thanks!

**Comment by jhamman** [comment]
@guillaumeeb - might you be convinced to add the suggestions in https://github.com/dask/dask-jobqueue/issues/123#issuecomment-412412517 to a "how to debug dask-jobqueue" section in our docs?

**Comment by guillaumeeb** [comment]
Sure, I will open an issue just to keep that in mind.
