### ISSUE TITLE
Github admin rights

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#124]
I just noticed that I don't have the admin rights on the github project. What I mean by this is that I can not see the "Settings" tab. Here is a snapshot from joblib for which I have the admin rights: 

![screenshot_2018-08-13 joblib joblib](https://user-images.githubusercontent.com/1680079/44020983-e8c70ee8-9ee3-11e8-8abe-7c55efb916aa.png)

@mrocklin would you consider granting them to a few of us, I am guessing @jhamman, @guillaumeeb and myself (for those who don't have them already)?

Full disclosure: the reason I wanted to look at Settings was to only enable "Squash and merge" when clicking on the Merge button. I think this makes for a cleaner history and it is easy to forget to set it to Squash+Merge if you have more than one option available.

Note: when using Squash+Merge, I would strongly encourage editing the commit message. By default it is just the concatenation of all the commit messages in the PR which is generally a lot more verbose/noisier than what you want.

**Comment by mrocklin** [comment]
I've just given @jhamman @guillaumeeb and @lesteve admin rights.  Thank you
all for maintaining this project.  Happy to demote myself from admin role
any time :)

**Comment by lesteve** [comment]
Great, thanks a lot, I can see the "Settings" tab now, closing this one.

> Happy to demote myself from admin role any time :)

:)

**Comment by lesteve** [comment]
With my new super rights, I have only enabled "Squash and Merge" in the "Merge" options. Please anyone shout if you see a problem with this.

**Comment by mrocklin** [comment]
Rarely, I do construct PRs with a few independent changes with a few very
cleanly separated commits.  In these cases I sometimes use rebase and marge
in order to maintain history.  This is rare enough though that I'm fine
waiting until this comes up before discussing it further.  Happy to close
as-is.

**Comment by lesteve** [comment]
If this is rare enough, doing the PR and pushing into upstream/master when the PR is ready to merge could be an option. In my experience I have found that clicking on Merge and forgetting to select "Squash and Merge" (generally because you are so happy that something eventually gets merged) and getting a noisy history is more common.
