### ISSUE TITLE
Adaptive prematurely killing workers

### ISSUE THREAD

**Issue by josephhardinee** [dask/dask-jobqueue#126]
I think this may be related to #122 but not sure so I'll post it as it's own issue.

When I start up a PBS cluster with adaptive, it starts up the minimum number of workers, but then kills all of them after about 10 seconds. This is not the case if I scale without using adaptive. I'm attaching a notebook to show a simple example and other information. 

[Adaptive Example](https://gist.github.com/josephhardinee/23594e44d943a6f97fc689842d501952)

**Comment by guillaumeeb** [comment]
I think I got this one. If you're using master branch, argument to scale or to adaptive are not the number of job to launch anymore, but the number of worker processes to launch.

So in your example, you've apparently configured dask-jobqueue to launch workers by group of 6. When you tell adaptive to adapt from 2 to 4, it may have trouble chosing between 0 or 1 job.

But wait, this is weird as you seem to have 2 jobs started in both of your example, with `adapt` or `scale`. So I take it you're not using master branch, and probably latest release from pip or conda? In that case, adaptive in that release is probably broken, as IIRC #63 was not in.

I will open another issue for preparing a new release.

**Comment by guillaumeeb** [comment]
With #119, scheduler now listen to any network interface by default. So interface parameters is indeed ignored for scheduler binding, it is however taken into account for workers. That should not be a problem, given that scheduler should be listening on your ib0 interface too.

If you still need to tell the scheduler to listen on a specific interface, the only solution currently is the one you propose: use `ip=` kwarg to the PBSCluster call. You can get the IP programmatically if needed, this is what was done in dask-jobqueue 0.3.0.

Reading more carefully your comment, I don't know what is the impact of worker connecting to scheduler with eth0 and then using ib0 interface. @mrocklin will certainly be more knowledgeable, #119 may have introduced an issue. Will this affect communication performances between workers and scheduler? Or will the --interface options force the worker to communicate through ib0 with scheduler as with other workers?

**Comment by josephhardinee** [comment]
Well the bigger issue I'm running into here is that I believe there are two separate networks. So the IP address that is being passed to the worker to connect to, is not actually accessible by the worker.

**Comment by guillaumeeb** [comment]
Hm, that's a problem I did not forsee in #119. I believe when given empty ip kwargs, scheduler bind to all interfaces, but takes the first one it sees as a display attribute. 

We should probably override the default address attribute in case interface kwarg is given, so do something around here: https://github.com/dask/dask-jobqueue/blob/4ea3c984be11984d047c9d38fdb81fb299d7530c/dask_jobqueue/core.py#L222

**Comment by guillaumeeb** [comment]
@josephhardinee, if you find time to give a go to last updates in master branch, your problem should be fixed.
