### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#127]
#63 has been merged after the previous release. I think we should make a new one to account this change and other smaller ones. Moreover, without #63, adaptive seems to be broken as highlighted in #126, and probably #122.

**Comment by guillaumeeb** [comment]
ping @mrocklin @jhamman @lesteve 

Maybe we should wait for #118 #131  and #135, that should get in soon.

**Comment by lesteve** [comment]
What is the status of #97? I haven't followed closely but my feeling is that adaptative still have some quirks that would be nice to iron out.

**Comment by jhamman** [comment]
Status of #97. Not done. Could use some beta testers / new ideas. We can make a release without those changes but I'd like to make sure a few others understand the complications therein.

**Comment by guillaumeeb** [comment]
I think we should move on and release soon. I've never done that, but can try tomorrow.

**Comment by mrocklin** [comment]
I would be happy to help walk you through it.  I typically follow the checklist here: https://github.com/dask/dask/blob/master/docs/release-procedure.md

I'll need to add you as a maintainer of the project on PyPI.  Do you have an account there already?

**Comment by guillaumeeb** [comment]
Nope, don't think so, will create it.

**Comment by guillaumeeb** [comment]
Done, same login as github.

**Comment by mrocklin** [comment]
You should now have push access to PyPI.  Do the steps in the release
procedure doc make sense to you?

**Comment by guillaumeeb** [comment]
Generally yes. Don't know twine though, and conda forge part looks a bit more complex, but that should be ok.

**Comment by mrocklin** [comment]
You should be able to just pip install twine and then follow instructions.

**Comment by guillaumeeb** [comment]
Perfect, will try tomorrow and get to you if I encounter some issue. Thanks !

That leaves some hours for others to chime in if against a release now.

**Comment by willirath** [comment]
> conda forge part looks a bit more complex

This is not necessarily true any more:  You can skip the rerendering part and trigger this with a comment in the discussion after creating the PR with just the `recipe/meta.yaml` updated to the new version (hash, version number, reset build number): 

https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

**Comment by mrocklin** [comment]
Conda forge bots will also probably pick up the change once it's on PyPI.
I recommend pushing to PyPI and then waiting for a while to see what
happens.

**Comment by guillaumeeb** [comment]
dask-jobqueue (0.4.0) pushed to PyPI.

Waiting for conda-forge as recommended by @mrocklin.

**Comment by guillaumeeb** [comment]
Done!
