### ISSUE TITLE
worker names have `--0:jobid--` instead of `--jobid--`

### ISSUE THREAD

**Issue by willirath** [dask/dask-jobqueue#134]
With #131 and on PBS, I get KeyErrors on the right-hand side of: <https://github.com/dask/dask-jobqueue/blob/4a10c1960e27be862560dbb6a8dd1eb8387250d7/dask_jobqueue/core.py#L61>

The `worker.name`s do not look like `'prefix--jobid--suffix'`, but like `'prefix--0:jobid--suffix'`.  Any idea where the leading `0:` comes from?

**Comment by guillaumeeb** [comment]
See https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/pbs.py#L97, job id is retrieved inside the submitted job using JOB_ID=${PBS_JOBID%.*}.

Could you submit an interactive job and see what the PBS_JOBID env variable looks like?

JOB_ID is then used for worker name here https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L230:
```python
self._command_template += " --name %s--${JOB_ID}--" % name
```

**Comment by guillaumeeb** [comment]
Your cluster scheduler looks like a weird PBS version :slightly_smiling_face: !

**Comment by willirath** [comment]
> Your cluster scheduler looks like a weird PBS version slightly_smiling_face !

!

**Comment by willirath** [comment]
> `JOB_ID=${PBS_JOBID%.*}`

Adding `"JOB_ID=${JOB_ID#*:}"` to the `env_extra` keyword fixes it. Thanks!

**Comment by guillaumeeb** [comment]
Cool! Nice use of `env_extra`. As your cluster seems really peculiar, can we close this issue? I don't think we could generalize this with a PR.

**Comment by willirath** [comment]
Yes, this can be closed.  Our PBS is a very rare one, this does not need to be in the main code.
