### ISSUE TITLE
Reusing dask-jobqueue code for launching Apache Spark cluster

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#14]
Just an idea I had, and feel that it was better to ask here before doing anything.
I believe that the (great) work done here could be applied to Spark as well as Dask. This simple interface with Job Scheduler may be adapted for launching Spark cluster.

Question is, how do you feel about that? Is there some kind of license or property constraint?

**Comment by guillaumeeb** [comment]
ping @mrocklin as you probably are the most concerned about his.

**Comment by mrocklin** [comment]
No strong thoughts from me.  I don't think licenses come into it.  I think
that mostly the concern I would have would be one of maintenance, setting
up CI, handling user issues, etc..  However you and @jhamman seem to be
taking that on, so as long as you're promising to support this for the next
year or two I don't have any strong objection.

**Comment by guillaumeeb** [comment]
Okay, that's perfect.

Just one point, I was thinking of just starting another repo somewhere else, as a Spark implementation of jobqueue system in dask/dask-jobqueue repo sounded weird to me. You would prefer to put it there?

**Comment by mrocklin** [comment]
No preference from me

**Comment by jakirkham** [comment]
@guillaumeeb, were you able to put something together for this? Have a use case where it might be nice to start Dask on top of Spark.

**Comment by guillaumeeb** [comment]
I hope to start some work on this soon, the idea is mostly to launch a Spark cluster the way it is done here for Dask, not to mix the two technologies. Is this what you would need? I'm curious of why you might want to launch Dask on top of Spark?

**Comment by guillaumeeb** [comment]
Don't your in-house Spark cluster rely on some resource manager like YaRN or Mesos? It is only a Spark standalone cluster?

I was not aware of dask-spark! Even if it is quite old, that's interesting, thanks!

**Comment by guillaumeeb** [comment]
I'll close this one as there is nothing preventing to do it, so my first question is answered. Obviously I've nothing to share yet, and this is not one of my priority. If I ever get back to this, I'll share things!
