### ISSUE TITLE
Change stdout and stderr default setting in LSF and Slurm cluster implementation

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#141]
As mentionned in #122 and #139, default values for job output files in LSF and Slurm implementation are
````python
"-e %s.err" % self.name
"-o %s.out" % self.name
````

If those configuration parameters have similar behavior as those from PBSPro, then this means every job submitted by dask-jobqueue will use this file name for writting its stdout and stderr when finished. So at one time, we will have only the last finished job stderr and stdout. 

I'm not sure this is what we want. At least when trying to understand some bug, this can be problematic. I propose to use templating propose by both scheduler, e.g. for Slurm, something like (maybe with escaping char):
````python
"-e %s-%j.err" % self.name
"-o %s-%j.out" % self.name
````

On the other hand, if we specify a value different for each job, we will get (as is happening currently with default PBSCluster implementation) the submission folder flooded with jobs stdout and stderr file.

**Comment by mrocklin** [comment]
Perhaps we should make a directory for log files and then flood that
directory?

**Comment by lesteve** [comment]
> +1 on this idea. Even better if that logs directory is configurable in the jobqueue config file.

Yeah and an additional parameter in the `JobQueueCluster.__init__` as well. We may need to create the folder before, if it does not exist. I seem to remember that SGE fails not very helpfully when you are using a log folder that does not exist.

**Comment by guillaumeeb** [comment]
As PBS doesn't handle any replacement symbol in the output files option, the easiest is to do the qsub inside the log files directory. This should be fine for other schedulers too.

**Comment by guillaumeeb** [comment]
After some conversation with @lesteve in #145, I believe we have three choices:
- Creating a folder, and submitting jobs from this directory using `cwd` arg in `Popen`. This could lead to some edge problems, mainly with eventual use of relative paths into user workflow. This is the better for having a good file name, at least for PBS.
- Creating a folder, and configuring job script to use it for standard outputs. Problem is for some scheduler (PBS), you cannot chose the filename this way, it will be a PBS default name not very explicit. I don't know for other scheduler if this possibility exist.
- Just leave the default, removing all -e or -o options, and let the user specify what he wants with `job_extra`.

**Comment by lesteve** [comment]
> Creating a folder, and configuring job script to use it for standard outputs. Problem is for some scheduler (PBS), you cannot chose the filename this way, it will be a PBS default name not very explicit.

Can you give the detail about the default PBS name? As long as the job id is in the name for the automatic PBS log name I think this is good enough.

> I don't know for other scheduler if this possibility exist.

I know it works for SGE (for SGE the automatic name when only specifying the folder is `<job-name>.o<job-id>`). If schedulers don't support using a folder for `-e/-o` but they allow variable expansion in their directives (e.g. for SLURM you can do something like `#SBATCH --error=hello-%J.out` according to [this](https://confluence.ecmwf.int/display/UDOC/Writing+SLURM+jobs), we can always use that instead.
