### ISSUE TITLE
Use the grouped workers `worker_key` function in scale outside of adaptive

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#152]
Seen thanks to https://github.com/dask/dask-kubernetes/issues/98.

Currently, `_job_id_from_worker_name` function is used as worker_key in adaptive options: https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L145.

However, this is not in place when manually scaling down or up. This could be a nice thing to avoid stopping too many workers when scaling down.

This may have to be changed upstream in distributed, somewhere here: https://github.com/dask/distributed/blob/master/distributed/deploy/cluster.py#L103. We could use a `self.worker_key method` if defined as another kwarg.

@mrocklin any opinion on that?

**Comment by mrocklin** [comment]
Yes.  That makes sense to me.
