### ISSUE TITLE
TypeError in dask-jobqueue/core.py when starting up workers (v0.4.0)

### ISSUE THREAD

**Issue by kaelancotter** [dask/dask-jobqueue#154]
Error Seems pretty straightforward. Adding a quick int() fixed things on my end.  LMK if you want a PR and or CI coverage... (I didn't see a contributing guide anywhere in the docs)  For context grid is an SGECluster object.  Thanks for the great tool.

```
In [6]: grid.scale(2)

DEBUG:Scaling up to 2 workers.
DEBUG:Found 0 active/pending workers.
DEBUG:starting 2 workers
In [7]: tornado.application - ERROR - Exception in callback <functools.partial object at 0x7fba4979c208>
Traceback (most recent call last):
  File ".../miniconda/envs/dask/lib/python2.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File ".../miniconda/envs/dask/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File ".../miniconda/envs/dask/lib/python2.7/site-packages/dask_jobqueue/core.py", line 375, in scale_up
    self.start_workers(n - active_and_pending)
  File ".../miniconda/envs/dask/lib/python2.7/site-packages/dask_jobqueue/core.py", line 299, in start_workers
    for _ in range(num_jobs):
TypeError: range() integer end argument expected, got float.
```

**Comment by kaelancotter** [comment]
Looking a little deeper, its certainly a python 2.7 vs 3.x issue specifically https://www.python.org/dev/peps/pep-3141/

**Comment by mrocklin** [comment]
Thanks for the bug report @kaelancotter .  A pull request would be welcome.  Contributor guidelines are available at documentation for the parent project: http://dask.pydata.org/en/latest/develop.html

**Comment by kaelancotter** [comment]
I took a look through the travis ci logs for python 2.7 sge.  Right now it looks like the sge_master image in the compose stack that executes pytest uses a default 3.x python from miniconda3 instead of the travis_python_version.  I think fixing the container to use the travis python version will greatly improve 2.7 test coverage, including coverage of the original type error. I hipe Im not overstepping.  :)

**Comment by guillaumeeb** [comment]
You're probably right, thanks for raising this too! It seems currently python 2.7 sge tests are useless.

It's really nice having other people stepping in this code, so you're very welcome here!

Feel free to submit one or two separate PR, for the initialy raised problem, and for test coverage which seems more complicate to fix.

**Comment by kaelancotter** [comment]
Awesome Thanks @guillaumeeb !

**Comment by guillaumeeb** [comment]
Thanks to you for your help here!

**Comment by guillaumeeb** [comment]
Closing thanks to #155 #158 and #157

**Comment by guillaumeeb** [comment]
Thanks again @kaelancotter.
