### ISSUE TITLE
Missing space using extra in PBSCluster

### ISSUE THREAD

**Issue by lanougue** [dask/dask-jobqueue#156]
Hi guys,

First post on Github for me... newbie.
I found an issue using  keyword "extra" in PBSCluster:

`cluster = PBSCluster(extra="--preload my_module.py") 

'cluster.job_script()'
returns
'#!/bin/bash\n\n#PBS -N dask-worker\n#PBS -q mpi_1\n#PBS -A SKIM\n#PBS -l select=1:ncpus=28:mem=120GB\n#PBS -l walltime=24:00:00\n#PBS -m n\n\n\n\n/home1/datahome/fnouguie/miniconda3/envs/lops-array/bin/python -m distributed.cli.dask_worker tcp://10.148.1.18:56677 --nthreads 2 --nprocs 28 --memory-limit 3.57GB --name dask-worker-2 --death-timeout 900--preload my_module.py --interface  ib0 \n'

showing no white space between 900 and --preload leading to the error.
I manually added a white space as a first character of  my extra command to PBSCluster to bypass the error.
Seems like a small bug.

**Comment by guillaumeeb** [comment]
Thanks @lanougue for the bug report. Would you want to submit a Pull Request to fix this and maybe add some simple test?

**Comment by lanougue** [comment]
I would prefer let you do that. I'm really just starting playing with GIT

**Comment by guillaumeeb** [comment]
Done in #160
