### ISSUE TITLE
expose Adaptive keyword arguments in adapt method

### ISSUE THREAD

**Issue by jhamman** [dask/dask-jobqueue#16]
Our current `adapt` method does not allow for any keyword arguments. It would be nice if we could pass in arguments like `minimum` and `maximum` to the `Adaptive` constructor with a usage like:

```Python
cluster = MyQueueCluster(...)
cluster.adapt(minimum=1, maximum=20)
```

**Comment by mrocklin** [comment]
This would be resolved by subclassing from the new `distributed.deploy.Cluster` superclass.
