### ISSUE TITLE
Pangeo/dask-jobqueue blog post

### ISSUE THREAD

**Issue by jhamman** [dask/dask-jobqueue#163]
I have written a semi-technical blog post on how dask-jobqueue. I think @mrocklin has already read most of it. I'd like to get comments from @guillaumeeb and @lesteve if possible.

The draft is here: https://medium.com/pangeo/scalable-interactive-analysis-workflows-using-dask-distributed-on-hpc-systems-d7754e42ca53

I actually started writing this months ago and just realized I never finished it off. Hopefully we can press submit later this week.

**Comment by mrocklin** [comment]
It would be good to get comments from others.  In the mean time, two brief
comments from me.

1.  Feel free to remove references to me personally, replacing with "we"
2.  This would also be welcome on blog.dask.org (
https://github.com/dask/dask-blog#add-a-new-page)

**Comment by jhamman** [comment]
Thanks @guillaumeeb - I've hit most of your comments now and added a nod to the common interface question in the conclusions.

**Comment by lesteve** [comment]
This seems very nice! A few things I noticed:
* should we mention somewhere mention that the jupyter notebook runs in an interactive job (or whatever the right word for it is), since I guess that is the typical setup, 
right?

A few minor things I noticed:
* there is a ibo instead of ib0 somewhere
* maybe separate this in two different code cells 
```
conda install -c conda-forge dask-jobqueue
# or
pip install dask-jobqueue
```

**Comment by guillaumeeb** [comment]
Some other minor points:
- for interactive analysis on very large data analysis
- scale_up and scale down, chose between with or without underscore

**Comment by jhamman** [comment]
Thanks all. I have the post scheduled to be published Monday morning. I also opened a PR on dask/blog to mirror the content there.

**Comment by jhamman** [comment]
cross referencing the published blog posts:

- https://medium.com/pangeo/dask-jobqueue-d7754e42ca53
- http://blog.dask.org/2018/10/08/Dask-Jobqueue

**Comment by guillaumeeb** [comment]
FWIW, you still have the sentence with repeated 'analysis' word.
