### ISSUE TITLE
Make python command configurable

### ISSUE THREAD

**Issue by ocaisa** [dask/dask-jobqueue#166]
Using `sys.executable` in https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L238 seems unnecessarily strict. My use case is that I have KNL nodes available and I want to manage both KNL and standard nodes from dask_jobqueue. I've mirrored the software stacks, and all the necessary `module load`s are the same, but the absolute paths differ.

I'm happy to issue a PR but I wanted to know how you would consider handling it? In my case, I'm installing  `dask_jobqueue` as a module for our users so I know that `os.path.basename(sys.executable)` (for example) would work as intended. I could add a new keyword arg that sets `python` which defaults to the existing value?

**Comment by mrocklin** [comment]
That seems quite reasonable to me
