### ISSUE TITLE
Error when port 8787 not available

### ISSUE THREAD

**Issue by ocaisa** [dask/dask-jobqueue#168]
When I start my cluster on our frontend I am getting:
```
Starting cluster... /usr/local/software/jureca/Stages/Devel-2018a/software/dask/0.19.2-intel-para-2018a-Python-3.6.5/lib/python3.6/site-packages/distributed-1.23.2-py3.6.egg/distributed/bokeh/core.py:56: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)
OK
```
Everything proceeds fine until it comes to gathering the results from the workers, when I get:
```
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://10.80.71.50:38543'], run_mpi-3b10797611ae08c0f20b7e53ae40d9cb
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://10.80.71.50:38543'], run_mpi-5d2195c688e8ee9e378788b1459b08bc
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://10.80.71.50:38543'], run_mpi-4fc33dd85059ce884fd6f856f8bfb3a9
NoneType: None
distributed.client - WARNING - Couldn't gather 3 keys, rescheduling {'run_mpi-3b10797611ae08c0f20b7e53ae40d9cb': ('tcp://10.80.71.50:38543',), 'run_mpi-5d2195c688e8ee9e378788b1459b08bc': ('tcp://10.80.71.50:38543',), 'run_mpi-4fc33dd85059ce884fd6f856f8bfb3a9': ('tcp://10.80.71.50:38543',)}
```
If I run on the backend, where the port is available, it runs without issue.

There may be another network issue at play that I don't understand, but I checked the workers and in the failing case they are definitely executing the tasks.

**Comment by ocaisa** [comment]
I should note that the error only occurs when I send tasks to our KNL partition, which are probably on a different subnet (I'm no network expert though), so it could indeed be just a network issue.

**Comment by mrocklin** [comment]
> I should note that the error only occurs when I send tasks to our KNL partition, which are probably on a different subnet (I'm no network expert though), so it could indeed be just a network issue.

This seems worth investigating to me.  You might want to play around with the `--interface` keyword argument.

**Comment by ocaisa** [comment]
Hmm, yes the port 8787 is not the issue. It must be some kind of firewall issue for the frontends maybe, I'll ask the admins.
