### ISSUE TITLE
Bug in last version (str / list in interface keyword)

### ISSUE THREAD

**Issue by lanougue** [dask/dask-jobqueue#180]
Hi,
I decided to upgrade my dask-jobqueue module. Now, I get some strange bug with this simple code:
```
from dask_jobqueue import PBSCluster
c=PBSCluster()
```
Here is the error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-8423031cee94> in <module>
      1 from dask_jobqueue import PBSCluster
----> 2 c=PBSCluster()

~/conda-env/RSSS/lib/python3.6/site-packages/dask_jobqueue/pbs.py in __init__(self, queue, project, resource_spec, walltime, job_extra, **kwargs)
     69 
     70         # Instantiate args and parameters from parent abstract class
---> 71         super(PBSCluster, self).__init__(**kwargs)
     72 
     73         # Try to find a project name from environment variable

~/conda-env/RSSS/lib/python3.6/site-packages/dask_jobqueue/core.py in __init__(self, name, cores, memory, processes, interface, death_timeout, local_directory, extra, env_extra, log_directory, walltime, threads, python, **kwargs)
    220 
    221         if interface:
--> 222             extra += ['--interface', interface]
    223             kwargs.setdefault('ip', get_ip_interface(interface))
    224         else:

TypeError: must be str, not list

I did not change anything in my config yaml file :

> jobqueue:
>   pbs:
>     name: dask-worker
> 
>     # Dask worker options
>     cores: 56
>     processes: 28
>     memory: 120GB
>     interface: ib0
>     death-timeout: 900 # should be large if many workers are launched
>     local-directory: null
> 
>     # PBS resource manager options
>     queue: mpi_1
>     project: SKIM
>     walltime: '24:00:00'
>     extra: ""
>     env-extra: []
>     resource-spec: select=1:ncpus=28:mem=120GB
>     job-extra: ['-m n']

**Comment by guillaumeeb** [comment]
Hi,

Sorry for the trouble, there has been a small breaking change in #160. You should replace 
```
extra: ""
```
By
```
extra: []
```

**Comment by lanougue** [comment]
Hi Guillaume, 
Thanks. Now it works. What was strange is that the error was about the "interface" keyword and not the "extra" one even if the interface was a str.
