### ISSUE TITLE
Adaptative implementation with a Remote scheduler

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#188]
In order to identify the interaction between adaptative mode and the ClusterManager and Scheduler components, it would be good to use current dask-jobqueue implementation.

- [ ] Move adaptive logic here, remove distributed.deploy dependency to it.
- [ ] Simplify the logic if possible, see if adaptive can only call scale, and not retire_workers itself
- [ ] Identify the remote method that adaptive will need to be available from Scheduler.

**Comment by guillaumeeb** [comment]
@mrocklin @jacobtomlinson since https://github.com/dask/dask-kubernetes/pull/162 was merge, I guess Adaptive mode doesn't need access to Scheduler object anymore and discuss with it only by RPC calls?

**Comment by mrocklin** [comment]
That's correct

**Comment by mrocklin** [comment]
This was fixed in https://github.com/dask/distributed/pull/2865

**Comment by guillaumeeb** [comment]
Closing this one, fixed upstream.
