### ISSUE TITLE
Arbitrary resources specification

### ISSUE THREAD

**Issue by leej3** [dask/dask-jobqueue#208]
I wonder can spot what I'm doing wrong here or whether this is a bug. I am attempting to define an limited arbitrary resource available to the workers so that I can constrain how certain jobs are run as described in the example [here](https://github.com/dask/distributed/issues/691)

This is my attempt. I would expect the workers to have specified resources but it is instead empty values:

```python
from dask_jobqueue import SLURMCluster
n_workers = 2
cluster = SLURMCluster(
    queue='norm',
    memory =  '8g',
    processes=1,
    threads = 8,
    resources={'foo':2},
    job_extra = ["--time=03:00:00"] )
cluster.start_workers(n_workers)

```

    [2, 3]

```python
from dask.distributed import Client
client = Client(cluster)
```

```python
client
```

<table style="border: 2px solid white;">
<tr>
<td style="vertical-align: top; border: 0px solid white">
<h3>Client</h3>
<ul>
  <li><b>Scheduler: </b>tcp://10.2.2.121:34243
  <li><b>Dashboard: </b><a href='http://10.2.2.121:39569/status' target='_blank'>http://10.2.2.121:39569/status</a>
</ul>
</td>
<td style="vertical-align: top; border: 0px solid white">
<h3>Cluster</h3>
<ul>
  <li><b>Workers: </b>2</li>
  <li><b>Cores: </b>16</li>
  <li><b>Memory: </b>16.00 GB</li>
</ul>
</td>
</tr>
</table>

```python
client.scheduler_info()
```

    {'type': 'Scheduler',
     'id': 'Scheduler-f91e76b3-1acf-43cc-878f-7d067a5b69f0',
     'address': 'tcp://10.2.2.121:34243',
     'services': {'bokeh': 39569},
     'workers': {'tcp://10.2.8.195:41307': {'name': 'dask-worker-2',
       'memory_limit': 8000000000,
       'host': '10.2.8.195',
       'resources': {},
       'ncores': 8,
       'services': {'nanny': 36619, 'bokeh': 8789},
       'local_directory': '/gpfs/gsfs10/users/DSST/template_making/dask-worker-space/worker-x8c8i_f9',
       'pid': 55064,
       'cpu': 4.0,
       'memory': 77385728,
       'time': 1544826786.8669972,
       'read_bytes': 2321.9966783571076,
       'write_bytes': 2511.9964065603162,
       'num_fds': 25,
       'executing': 0,
       'in_memory': 0,
       'ready': 0,
       'in_flight': 0},
      'tcp://10.2.8.204:35588': {'name': 'dask-worker-3',
       'memory_limit': 8000000000,
       'host': '10.2.8.204',
       'resources': {},
       'ncores': 8,
       'services': {'nanny': 38422, 'bokeh': 8789},
       'local_directory': '/gpfs/gsfs10/users/DSST/template_making/dask-worker-space/worker-_oieon0d',
       'pid': 8994,
       'cpu': 2.0,
       'memory': 79437824,
       'time': 1544826786.882559,
       'read_bytes': 290916709.90968,
       'write_bytes': 3363344.64549749,
       'num_fds': 25,
       'executing': 0,
       'in_memory': 0,
       'ready': 0,
       'in_flight': 0}}}

**Comment by jhamman** [comment]
@leej3 - Best place to start for how to debug these sorts of things is here: https://dask-jobqueue.readthedocs.io/en/latest/debug.html

In particular, I would start by printing the job script (`print(cluster.job_script())`). We generally find, iterating to get this job script right is pretty straightforward given most HPC users knowledge of their system.

**Comment by leej3** [comment]
Thanks. I realized I was using a rather old version of the package anyway. With the most recent version from conda-forge I am getting an error.
Using:
dask                      1.0.0                      py_0    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
dask-jobqueue             0.4.1                      py_0    conda-forge

With the command:

```
cluster = SLURMCluster(processes=6, cores=24, memory="20GB")
cluster.start_workers(n_workers)
```

I get the error:
```
ValueError: Could not parse job id from submission command output.
```

The job script:
```
ipdb>  print(Path('/tmp/tmp8p0fptda.sh').read_text())
#!/bin/bash

#!/usr/bin/env bash
#SBATCH -J dask-worker
#SBATCH -p norm
#SBATCH -A woodshole
#SBATCH -n 1
#SBATCH --cpus-per-task=2
#SBATCH --mem=15G
#SBATCH -t 01:00:00
JOB_ID=${SLURM_JOB_ID%;*}



/data/rodgersleejg/python/envs/dask/bin/python -m distributed.cli.dask_worker tcp://10.2.2.121:38849 --nthreads 0 --nprocs 4 --memory-limit 4.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60
```

I will open a different issue for this when I get a chance. Thanks for the pointers.

**Comment by mrocklin** [comment]
I wouldn't be surprised if we just didn't pass through the resources=
keyword argument to the workers.  I'm not sure.  I suspect that you could
take a look at the core file to find out decently quickly (it's not a large
codebase).

**Comment by guillaumeeb** [comment]
For using `reources`, see @lesteve comment here: https://github.com/dask/dask-jobqueue/issues/181#issuecomment-436711950.

`resources` is not a kwarg, you must use `extra` kwarg to pass `resources` to the worker command.

For the second problem, this error is raised when dask-jobqueue is not able to parse the String returned by your job submission command. If you raise another issue, please try to submit the `job_script` you printed, using `sbatch` on a command line, and copy the output you get here. For Slurm, we expect something like https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/tests/test_jobqueue_core.py#L89.

**Comment by leej3** [comment]
Thanks for the help with this. The following code now assigns resource contraints to the workers as I would expect:

```python
from distributed import Client
from dask_jobqueue import SLURMCluster
n_workers = 3

cluster = SLURMCluster(
    queue='norm',
    memory =  '8g',
    processes=1,
    cores = 8,
    extra=['--resources foo=2'],
    job_extra = ["--time=03:00:00 "],
env_extra=['export OMP_NUM_THREADS="8"'])

client = Client(cluster)
cluster.start_workers(n_workers)
```


```python
client.scheduler_info()['workers']['tcp://10.2.8.228:38056']
```

    {'type': 'Worker',
     'id': 'dask-worker--15834153--',
     'host': '10.2.8.228',
     'resources': {'foo': 2.0},
     'local_directory': '/gpfs/gsfs10/users/DSST/template_making/worker-2pfpfv4w',
     'name': 'dask-worker--15834153--',
     'ncores': 8,
     'memory_limit': 8000000000,
     'last_seen': 1545062404.4479392,
     'services': {'nanny': 36292, 'bokeh': 43603},
     'metrics': {'cpu': 4.0,
      'memory': 77275136,
      'time': 1545062403.9508224,
      'read_bytes': 2491.014388221522,
      'write_bytes': 1364.5556729052835,
      'num_fds': 30,
      'executing': 0,
      'in_memory': 9,
      'ready': 0,
      'in_flight': 0}}
