### ISSUE TITLE
Looking for some advice

### ISSUE THREAD

**Issue by ocaisa** [dask/dask-jobqueue#210]
I've been experimenting more with jobqueue and I had a few questions (that probably also fall back to Dask itself).

Firstly, I've noticed scenarios where it seems like results are cached. The case I had was where I had a task that takes no arguments and more or less just sleeps for 5 seconds. If I started up 200 of these on an adaptive cluster, only 1 worker started and all the result seemed to come back in the time it took to run a single task. If I added an (unused) iterator argument to the task, the cluster scaled up and ran as expected. I'm guessing Dask is being clever in this respect somehow? Maybe you can point me somewhere that describes this (and how to turn it off)?

The second thing is I would like to use the `adapt()` method to control the resources but it seems that it's not possible to use this in combination with `scale_up()`. The use case is I want the possibility of the cluster dynamically scaling down (so I don't want to use `minimum=`) but if I have long-running tasks I don't want to wait for one to finish before `adapt()` decides to scale up (that seems to be how it's working).

Any tips would be very welcome.

**Comment by ocaisa** [comment]
@guillaumeeb Thanks for the help. The first point was exactly what I needed.

For the second case, the test setup we have doesn't really allow me to try your first point but from playing with the second case I can see that it would work. In the second case, tweaking `wait_count` (and `interval`) has an impact on shutting a worker down *after* it has executed something but`adapt()` still shut down some of my workers before I managed to queue an initial task for some of them.

One thing I noticed is that `adapt()` does not seem to respect `minimum=0`, it always leaves one worker running. That may be a side effect of our test setup, where we have 3 different clusters running (one for each hardware on the system), one worker of each type persists until they have all finished.

**Comment by ocaisa** [comment]
The best solution for the second point is probably your point 3, I'll see how we could implement that in our setup.

**Comment by guillaumeeb** [comment]
> butadapt() still shut down some of my workers before I managed to queue an initial task for them.

Oh sorry, I didn't check the code of adaptive before saying that. Do not hesitate to look at it, it is not that big or complicated. https://github.com/dask/distributed/blob/master/distributed/deploy/adaptive.py. Taking a quick look at https://github.com/dask/distributed/blob/master/distributed/deploy/adaptive.py#L294-L307, this seems weird that adaptive is closing your workers before the wait_count, but there is probably something I miss.

> The best solution for the second point is probably your point 3, I'll see how we could implement that in our setup.

Please post here once you have a solution!

**Comment by ocaisa** [comment]
Ok, when workers sit in the queue it's even more obvious, if no tasks have run, `adapt()` kills off the queued workers. Letting the scheduler know about (a fake?) task duration seems like it might be the only workable fix.

**Comment by guillaumeeb** [comment]
I tried the `wait_count` kwarg, what I did was:

```python
cluster.scale(2)
cluster.adapt(minimum=1, maximum=10, wait_count=30)
```

As I expected, Adaptive only shut down one of my worker after 30 seconds. So that means I have 30 seconds to start tasks.

Anyway, do you still need this open @ocaisa, or did the previous conversation solved you issue?

**Comment by ocaisa** [comment]
Maybe it was the order I did things, I tried `adapt()` and then `scale()` and it still seems to kill them off unless they had actually registered with the scheduler (if they were still in the queue or configuring they seemed liable to being shut down).

Anyway, no need to leave this open, I have the info I needed. If I can define a concrete problem I'll open a new issue.
