### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by AdamWlodarczyk** [dask/dask-jobqueue#225]
Hi, do you have any template for citation (such as [Dask itself](http://docs.dask.org/en/latest/cite.html))?

**Comment by guillaumeeb** [comment]
Hm, using Dask citation might be sufficient? No specific template for dask-jobqueue.

You may also cite a blog post if you want: https://blog.dask.org/2018/10/08/Dask-Jobqueue.

**Comment by jhamman** [comment]
Yes, I suggest using the dask citations and reference this repo/docs and/or the blog @guillaumeeb posted if you need something specific to jobqueue.
