### ISSUE TITLE
SLURM cluster fails with unrecognized option '--parsable'

### ISSUE THREAD

**Issue by brian-rose** [dask/dask-jobqueue#227]
I'm trying out a Pangeo deployment on our local HPC system at UAlbany, which uses SLURM.
Basically following [these instructions](https://pangeo.io/setup_guides/hpc.html) from the Pangeo documentation.

Running this code from within a Jupyter notebook:
```
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(processes=4,
                       cores=4,
                       memory="16GB",
                       walltime="01:00:00",
                       queue="snow-1")
cluster.scale(4)
```
fails with the following:
```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b8d1bfb7bf8>, 4)
Traceback (most recent call last):
  File "/network/rit/home/br546577/miniconda3/envs/pangeo/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/network/rit/home/br546577/miniconda3/envs/pangeo/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/network/rit/home/br546577/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_jobqueue/core.py", line 416, in scale_up
    self.start_workers(n - self._count_active_and_pending_workers())
  File "/network/rit/home/br546577/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_jobqueue/core.py", line 330, in start_workers
    out = self._submit_job(fn)
  File "/network/rit/home/br546577/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_jobqueue/core.py", line 322, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/network/rit/home/br546577/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_jobqueue/core.py", line 383, in _call
    cmd_str, out, err))
RuntimeError: Command exited with non-zero exit code.
Exit code: 1
Command:
sbatch --parsable /tmp/tmpo8zdikq3.sh
stdout:

stderr:
sbatch: unrecognized option '--parsable'
Try "sbatch --help" for more information
```

I generated the same error message by running
```
sbatch --parsable
```
directly on the command line.

It's possible that this is because we are running a very old version of SLURM:
```
[br546577@snow-23 ~]$ sbatch --version
slurm 2.5.1
```

Workarounds?

**Comment by lesteve** [comment]
> It's possible that this is because we are running a very old version of SLURM:

I googled a bit and found [this commit](https://github.com/SchedMD/slurm/commit/b3b5b9dd8f70cdfa053e42f89460d13aef3b2079) which seems to have reached the [14-03-0-1 release](https://github.com/SchedMD/slurm/releases/tag/slurm-14-03-0-1) released in Mar 26, 2014.

The first thing I would suggest is asking your sys-admin whether there is a slight chance to update the SLURM install. Maybe unlikely but I guess it's worth a try.

A work-around in `dask-jobqueue` would be to not use `--parsable` and get the job id from the stdout produced by `sbatch the_temporary_script.sh` + a regex. A PR doing that would be more than welcome!

You may want to look at https://github.com/dask/dask-jobqueue/pull/45 that added `--parsable` in `dask-jobqueue` and the reasons that motivated the change. IIRC the main reason was: it is cleaner to avoid post-treatment in `dask-jobqueue` as much as possible, but of course we did not imagine that `--parsable` was a problem in very old SLURM installs ...

Another thing to draw inspiration from `IPython.parallel` and how they get the jobid from the submit command output in: https://github.com/ipython/ipyparallel/blob/6.1.1/ipyparallel/apps/launcher.py.

**Comment by brian-rose** [comment]
I will ask about a SLURM update but I don't expect that to happen quickly.

Meanwhile I will look into the workaround you proposed.

**Comment by jhamman** [comment]
@brian-rose - 

You may try editing the `submit_command` attribute:

```
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(processes=4,
                       cores=4,
                       memory="16GB",
                       walltime="01:00:00",
                       queue="snow-1")

# defaults to 'sbatch --parsable'
cluster.submit_command = 'sbatch'

cluster.scale(4)
```

This may present problems parsing the job id but we wont know until you try this.

**Comment by brian-rose** [comment]
@jhamman incredibly, this worked.

**Comment by jhamman** [comment]
@brian-rose - fantastic. If you can suggest (and/or implement) a change to the documentation that would help alleviate this in the future, that would be great.

**Comment by lesteve** [comment]
> @jhamman incredibly, this worked.

IIRC the jobs start but the parsing of the job id fails (you may want to look at `cluster.jobs`). For example, that means that your jobs can not be killed. #44 was more or less about this.

**Comment by brian-rose** [comment]
I probably spoke too soon. Setting
```
cluster.submit_command = 'sbatch'
```
as above runs without throwing any errors, but the workers seem to die shortly after they are created.

I don't understand any of this well enough to know if there is any relationship to parsing the job id. 

After the workers are created and immediately die, the output of `cluster.finished_jobs` looks like
```
OrderedDict([('838715', {})])
```

**Comment by jhamman** [comment]
@brian-rose - that actually looks right. 

Why the workers aren't starting appears to be unrelated to your original issue. From here, I suggest working through https://dask-jobqueue.readthedocs.io/en/latest/debug.html. In particular, the `cluster.job_script()` method seems to be very useful for understanding what jobqueue is doing and how it is interfacing with your scheduler.

**Comment by brian-rose** [comment]
Ok, so in regards to the original issue, is removing `--parsable` entirely going to cause problems for other SLURM users?

If not, I can see about adding a note in the docs regarding this workaround.

**Comment by brian-rose** [comment]
Update: I have a working setup on our slurm cluster now. It looks like this:
```
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(processes=8,  
                       cores=32,  
                       memory="256GB", 
                       walltime="01:00:00",
                       queue="snow-1",
                      )
# defaults to 'sbatch --parsable'
cluster.submit_command = 'sbatch'
cluster.start_workers(1)
```

I have questions about use and performance for a workflow that involves `xarray.open_mfdataset` on a large collection of netcdf files. I don't want to completely derail this issue, so where is the right place to ask?

**Comment by jhamman** [comment]
Let's move that conversation to the Pangeo issue tracker. 

We can keep this open to discuss if we need the `--parsable` flag at all.

**Comment by lesteve** [comment]
@brian-roe can you post the output of `cluster.jobs` in your working setup?

**Comment by brian-rose** [comment]
Sure. I was confused by your comment above, because the output is this:
```
AttributeError: 'SLURMCluster' object has no attribute 'jobs'
```

**Comment by lesteve** [comment]
Sorry I meant `cluster.running_jobs`.

**Comment by brian-rose** [comment]
Ok! Here it is:
```
OrderedDict([('839023',
              {'dask-worker--839023---1': <Worker 'tcp://10.77.8.123:41859', memory: 1, processing: 0>,
               'dask-worker--839023---7': <Worker 'tcp://10.77.8.123:47793', memory: 1, processing: 0>,
               'dask-worker--839023---4': <Worker 'tcp://10.77.8.123:48302', memory: 1, processing: 0>,
               'dask-worker--839023---6': <Worker 'tcp://10.77.8.123:33315', memory: 11, processing: 0>,
               'dask-worker--839023---5': <Worker 'tcp://10.77.8.123:36668', memory: 4, processing: 0>,
               'dask-worker--839023---3': <Worker 'tcp://10.77.8.123:40763', memory: 0, processing: 0>,
               'dask-worker--839023---0': <Worker 'tcp://10.77.8.123:46865', memory: 1, processing: 0>,
               'dask-worker--839023---2': <Worker 'tcp://10.77.8.123:42937', memory: 1, processing: 0>})])
```

**Comment by lesteve** [comment]
Great it seems the parsing of the job id is working fine, i.e. the keys of your `cluster.running_jobs` dictionary is your job id, glad to see that !

**Comment by guillaumeeb** [comment]
I think we can safely remove the `--parsable` flag.

**Comment by lesteve** [comment]
Agreed. I opened #232 and will merge if CIs are green.

If `--parsable` turns out to be strongly needed (which I doubt) we can always add `--parsable` conditionally, e.g. by using `"--parsable" in subprocess.check_output(['sbatch', '--help'])`
