### ISSUE TITLE
Workers not starting

### ISSUE THREAD

**Issue by DanielGalea** [dask/dask-jobqueue#228]
Hi,

I have been trying to set up an LSFCluster using the dask_jobqueue from inside a Singularity container. The container is buiilt to the latest version of CentOS7, dask, dask_jobqueue and python3.6. The container itself does not have access to the LSF scheduler, so I have had to sub-class the LSFCluster class in dask-jobqueue to be able to use SSH to submit the jobs. This is the following:

    def create_worker(use_line):
		
		sh = "#BSUB -cwd /home/users/dgalea/junk \n\n /apps/singularity/bin/singularity shell ~/containers/container.img<<EOF\n" + "/usr/local/bin/python3.6 " + use_line + " \nEOF"
		return sh

    class BetterLSFCluster(LSFCluster): 

	    def __init__(self, *args, **kwargs):
		super(BetterLSFCluster, self).__init__(*args, **kwargs) 
		self.submit_command = "ssh 0 bsub < "

	    def _submit_job(self, script_filename):

		orig_script = open(script_filename)

		with tempfile.NamedTemporaryFile(delete=False) as temp_file:
			with open(temp_file.name, 'w') as write_file:
				use_line = None
				while(True):
					line = orig_script.readline()
					if line.startswith("/usr"):
						use_line = line.split("python3 ")[1]
						write_file.write(create_worker(use_line))
						break
					else:
						write_file.write(line)			

			piped_cmd = [self.submit_command + ' ' + temp_file.name + ' 2> /dev/null']

		orig_script.close()
		return self._call(piped_cmd, shell=True)

This successfully submits the job. I then use the following to start 10 workers:

    num_procs = 10	

	cluster = BetterLSFCluster(cores=1, memory='2GB',  queue='short-serial', death_timeout=60)

	cluster.scale(num_procs)

	client = Client(cluster, processes=False, timeout=60)

This submits and starts all the jobs. After I managed this, I noticed that I was not getting the performance I wanted and realised that not all of the workers were connecting, even though the jobs were running. I confirmed this by using the following:

    current_procs = int(len(cluster.running_jobs))
	while not current_procs == num_procs:
		print("Have " + str(current_procs) + " out of " + str(num_procs) + "jobs.")
		time.sleep(1)
		current_procs = int(len(cluster.running_jobs))

This showed that a variable number of jobs were connecting whenever I run my script. I checked the logs of one of the workers that was not connecting, which gave me this

    distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.70.4:41601'

Therefore, the worker is stuck at starting the nanny. Would anyone know how I can try to get all the workers to start and connect to the Dask cluster?

**Comment by lesteve** [comment]
No great suggestion off the top of my head I am afraid. You may be able to find useful pieces of information in https://dask-jobqueue.readthedocs.io/en/latest/debug.html. 

Just a piece of generic advice (maybe you have tried this already ...): if I were you I would try to reduce the number of moving pieces e.g. start with the scheduler not running in a Singularity container and on the cluster login node (i.e. you don't need your ssh trick so you can use `LSFCluster`) and add layers of complexity one by one.

**Comment by guillaumeeb** [comment]
@DanielGalea did you find a solution?

Have you tried using the `--no-nanny` option? Maybe somehow some of your processes can fork other processes...

**Comment by guillaumeeb** [comment]
Closing as stale. Feel free to reopen if you get back at it @DanielGalea!
