### ISSUE TITLE
Release 0.4.2 or 0.5.0

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#234]
This was asked on https://gitter.im/dask/dask by @djhoese mainly to have #192 in an official release.

There has been some other improvements over the past few months, but also the start of some tries to write a ClusterManager concept, which is far from being done by now (sorry for not advancing as much as I'd like on this). Fortunately, this should not impact this module stability, this mainly implies some duplication and potential non synchronization of code between dask-jobqueue and distributed.deploy package.

So, should we make a release? Which tag? I'm inclined to go toward 0.5.0 as there is some major changes on going.

**Comment by jhamman** [comment]
I'd be happy to see a 0.5 release. Are there any issues (bugs or major features) that we want to get in before such a release?

**Comment by guillaumeeb** [comment]
I would have liked to get in a lot of things, but I've pretty much not started anything :grin:. So I would say that we may wait for #223 to be finished, but other features will have to wait.
I don't think we've got major bugs waiting to be fixed.

**Comment by guillaumeeb** [comment]
I hope you were not in a hurry @djhoese, hopefully #223 will be completed soon enough.

**Comment by djhoese** [comment]
No problem. This was mostly needed for some jupyter lab on a slurm cluster testing I was doing. I installed from github master and haven't touched it sense. Thanks.

**Comment by LokiYang** [comment]
Hi @djhoese , as #223 is merged, just wondering whether you can help to prepare a release? Thanks.

**Comment by djhoese** [comment]
@lokiyang what can I do?

**Comment by LokiYang** [comment]
> @LokiYang what can I do?

Sorry I should ask @guillaumeeb for release... 

Hi @guillaumeeb , as #223 is merged, do you mind to make a release on current master? Thanks.

**Comment by guillaumeeb** [comment]
Oh yes, I'd forgotten about this, quite busy at the moment. I will try to do it by the end of the week.
I suspect there could be another release not so much time after, as there are some evolution to take into accout in distributed.

**Comment by guillaumeeb** [comment]
version 0.5.0 should be up in pypi, waiting for conda bot to ping me.

**Comment by willirath** [comment]
Thanks for tagging, @guillaumeeb.  It's great to have all the recent progress in a proper release!

**Comment by guillaumeeb** [comment]
Release done!
