### ISSUE TITLE
SGE parallel environment spec

### ISSUE THREAD

**Issue by ericmjl** [dask/dask-jobqueue#235]
GridEngine clusters apparently allow for a `-pe` flag. This maps to a "parallel environment" specification. 

What are opinions on modifying the SGECluster source code to add in a `pe_spec` kwarg, such that end users who are knowledgeable can add this in?

Wanted to get opinions on this before I did work on it.

**Comment by jhamman** [comment]
I would think this is already possible using `job_extra=['-pe orte']` (for example). The `job_extra` kwarg is there to allow arbitrary additions to the job script, line by line.

**Comment by ericmjl** [comment]
Oh, this is great to know! I guess I should PR into the docs example instead, then :smile:

**Comment by guillaumeeb** [comment]
I'm closing this issue as there is an already built-in solution for cases like this as answered by @jhamman . But @ericmjl do not hesitate to propose a PR for documentation update, this would be more than welcomed!
