### ISSUE TITLE
Give a talk at SciPy?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#236]
I suspect that dask-jobqueue would be a hit at the annual SciPy conference that takes place in July in Austin, Texas.

The call or proposals ends next week.  Is anyone interested?

**Comment by mrocklin** [comment]
Checking in here.  I suspect that it's difficult for many of the core maintainers of this project to give a talk at SciPy either because 

1.  They're probably giving another talk (as is perhaps the case for @jhamman )
2.  They live really far away and may not make it to the conference (as is perhaps the case for @guillaumeeb and @lesteve ) 

If that is the case then perhaps an active user of this package might be willing to give a talk?

**Comment by guillaumeeb** [comment]
As much as I'd like participate to SciPy, that won't be this year for private and family life reason. I'd be happy to help review something if needed.

**Comment by lesteve** [comment]
I am not sure at all I will make it to SciPy this year unfortunately ... I won't have a better visibility on this before end-March.

**Comment by jhamman** [comment]
@andersy005 and I are putting together an abstract that will cover dask-jobqueue. Whoop!

**Comment by mrocklin** [comment]
I'm glad to hear it!

**Comment by jhamman** [comment]
@andersy005's abstract went in on Friday!
