### ISSUE TITLE
Use black on this codebase

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#237]
@mrocklin proposed this on dask issue tracker, and implemented it on dask-kubernetes (see https://github.com/dask/dask-kubernetes/pull/122).

I think this is a really good idea, and I'm opening this issue to remember it, and do it at one point on dask-jobqueue.

**Comment by lesteve** [comment]
I'd be happy to try out black on dask-jobqueue !

The only thing I would say is that the PR adding black is likely to create conflicts with other PRs. So maybe we should have a quick look at oustanding PRs and decide if we should try to merge some before we use black.
