### ISSUE TITLE
Not all worker jobs submitted with processes != 1

### ISSUE THREAD

**Issue by jbusecke** [dask/dask-jobqueue#243]
I am planning to run large analysis jobs on the Princeton Tiger HPC.
I run the latest master of dask-jobqueue (as recommended in #241), but noticed a strange behaviour when trying to adjust the number of cores per worker.

When I set the cluster up as follows:
```
from dask_jobqueue import SLURMCluster
from dask.distributed import Client

cluster = SLURMCluster(
    job_mem="95GB",
    job_cpu=20,
    cores=20,
    memory="95GB",
#     processes=10,
    processes=1,
    interface="em1",
    walltime="00:30:00",
    diagnostics_port=1224
)
client = Client(cluster)

cluster.scale(2)

import time

time.sleep(30)

client
```
I get two worker jobs with a total of 40 cores and 2 workers as expected.

If I want to decrease the number of cores per worker by passing `processes=5`, 
```
from dask_jobqueue import SLURMCluster
from dask.distributed import Client

cluster = SLURMCluster(
    job_mem="95GB",
    job_cpu=20,
    cores=20,
    memory="95GB",
    processes=5,
    interface="em1",
    walltime="00:30:00",
    diagnostics_port=1224
)
client = Client(cluster)

cluster.scale(2)

import time

time.sleep(10)

client
```
only one of the two expected jobs gets submitted (confirmed with `squeue -u <username>`. 

Does anyone have an idea what I am doing wrong or how to debug this?

Many thanks.

**Comment by guillaumeeb** [comment]
> I am planning to run large analysis jobs on the Princeton Tiger HPC

That's great, if at one point you can talk of your use of dask here or on Pangeo github, this would be nice!

About your problem, `scale` takes in argument the number of worker **processes**, not the number of worker jobs. So for dask-jobqueue, actually 5 worker processes were started, more than the 2 requested.

With master branch, you can also scale with number of cpu cores as kwarg.

**Comment by jbusecke** [comment]
Fantastic! Thanks for the explanation. Perhaps it would be worth to explain this in more detail in the docs? I could try to put ip a PR.

I was definitely planning to write this up once I have tested it a bit more.

TTYS



Julius Busecke

**Comment by guillaumeeb** [comment]
A PR on the docs would be more than welcomed!
