### ISSUE TITLE
Adaptive cluster maximums less than minimum number of workers started results in endless loop

### ISSUE THREAD

**Issue by Lnaden** [dask/dask-jobqueue#249]
Short: Can an exception be raised when a user feeds in `adapt(maximum=X)` where `X` is less than the minimum number of Workers the `Cluster` can create?

There is a non-intuitive infinite loop of workers starting and dying you can create if your `Cluster` will create more Dask Workers than your `adapt(maximum=X)` keyword allows.

E.g. 
```python
from dask import Client
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(cores=2, processes=2)
cluster.adapt(maximum=1)
Client(cluster)
```
will create a scenario that when a worker is needed, a SLURM job will be submitted requesting 2 `cores`, and create 2 Worker `processes`, each process receiving 1 thread. The SLURM job will be started and the 2 Workers will be created and report back to the `Client`. At this point, the `Adaptive` component detects there are 2 Workers, but can only have a max of 1 so it tries to shut Workers down, the only way it can do this is to kill the SLURM job, killing both workers.
Now there are tasks waiting, no workers to be found, so `SLURMCluster` submits a new SLURMJob repeat forever.

This does not raise any kind of warning or exception, because this is all behaving the way its programed to. The problem is its not intuitive and without a warning or error, its hard to understand why all your queued jobs are created, shut down gracefully, but never finish tasks. I understand this is a corner, unaware-user case which probably does not need to be engineered around, but could an exception be thrown if a user tries to do this instead?

**Comment by guillaumeeb** [comment]
Thanks @Lnaden for this well described issue!

Are you using master branch or last stable version (0.4.1)?

I encountered this behavior before, and thought I had fixed it, but I may have only with standard `scale` calls, and not when using `adapt`. IIRC Dask distributed Adaptive class calls directly `scale_up` and `scale_down` methods, which may be the problem here. This may need to fix things in Dask distributed directly.

We can raise an Exception or informative error when the maximum/minimum parameters is not a multiple of `processes`, as I believe you would see behavior close to this when using `adapt(maximum=3)` in your example.

But I would prefer to have a fix which just round up the maximum number of workers requested to make it a multiple of `processes`. We can probably do this in dask-jobqueue.

Any opinion?

**Comment by Lnaden** [comment]
> Are you using master branch or last stable version (0.4.1)?

Latest stable, v0.4.1 from Conda-Forge 

>  but I may have only with standard scale

The standard `scale` calls work fine, but the `adapt` logic is where it does this loop. So if you replaced the initial example's `adapt` call with `cluster.scale(1)`, then the job is submitted and two workers are created which happily continue to exist.

> RC Dask distributed Adaptive class calls directly scale_up and scale_down methods, which may be the problem here. This may need to fix things in Dask distributed directly.

It does. Theres some overhead logic, but the `dask.ditributed.deploy.adaptive.Adaptive` class is the main actor here. I can raise this issue on the Distributed repo if you think it would be better addressed there?

> We can raise an Exception or informative error when the maximum/minimum parameters is not a multiple of processes, as I believe you would see behavior close to this when using adapt(maximum=3) in your example.

I had suggested the exception only in the case where "adaptive max" < "min number of Workers which can be created" because that creates the unproductive loop, and would be the path of less resistance. The larger problem is that the `adapt` will always start and stop scheduler jobs endlessly if the `processes`  kwarg/default is not a multiple of the maximum as you identified with the `maximum=3` example. The difference here is that the first scheduler job's workers will still be productive.

> Any opinion?

I think the best solution here would be 2 checks. 
1. Raise an exception when "adaptive max" < "min number of Workers which can be created" as originally posted. This will block the user from doing something non-productive. 
2. The second would be that the scheduler would *not* start a new Cluster-submitted job if that job will create more new Worker processes which would make the total exceed the max. 

I think this would make the most intuitive sense and be the most conservative with user resources. Since the `maximum` is just a limit, not what it has to be running at all times, and then the user does not suddenly have more workers than they thought would be created. E.g. the Cluster job creates 99 Workers with a 100 max, under the rounding logic the user would see 198 workers, which would be equally confusing I think.

Thoughts?

**Comment by guillaumeeb** [comment]
>  call with cluster.scale(1), then the job is submitted and two workers are created which happily continue to exist

What about if you issue another call to `scale(1)` right after? Does it kill the workers? If so, this should be fixed on master, but I think this won't change anything to `adapt()` call.

> I can raise this issue on the Distributed repo if you think it would be better addressed there?

Not sure, let's see how we would solve it here first.

> The larger problem is that the adapt will always start and stop scheduler jobs endlessly if the processes kwarg/default is not a multiple of the maximum as you identified

So we must solve that!

> The second would be that the scheduler would not start a new Cluster-submitted job if that job will create more new Worker processes which would make the total exceed the max.
> I think this would make the most intuitive sense and be the most conservative with user resources. Since the maximum is just a limit, not what it has to be running at all times

Hm, the strategy we use currently is to round up instead of floor down... But this is applied to scale, not adapt, maybe we should do things differently, even if I don't like that on first thought. I can see your point. Even if I don't think we would reach such an extreme situation as you describe :slightly_smiling_face:. And it could also be the way around, be stuck at 101 workers with a max at 200!

**Comment by guillaumeeb** [comment]
And the most important question, would you like to work on a PR for that? I think the logic is not much different between rounding up or down, so this is just a detail. You can look at ClusterManager class and what is done for scale currently, see if it applies here.

**Comment by Lnaden** [comment]
> What about if you issue another call to scale(1) right after? Does it kill the workers? If so, this should be fixed on master, but I think this won't change anything to adapt() call.

I think for `scale` its handled correctly. For `adapt` it isn't. I did also switch to the head branch to get the changes to `scale` fixed to be sure. Adaptive still has some issues.

> Even if I don't think we would reach such an extreme situation as you describe 

Sure, its an extreme example, and the reverse is also true, but its nice rounded numbers. Either solution is fine with me in the end, so long as the behavior is documented.

> would you like to work on a PR for that

I'm not going to be able to contribute to helping with this right now, sorry :/

**Comment by guillaumeeb** [comment]
The behavior here should be tried again with #306 in.

**Comment by guillaumeeb** [comment]
This issue is really outdated, but a problem which looks similar is raised in https://github.com/dask/dask-jobqueue/issues/498.

I'm going to close this one in favor of the other.
