### ISSUE TITLE
Mismatch between the job's and the sum of the workers' memory allocation

### ISSUE THREAD

**Issue by willirath** [dask/dask-jobqueue#252]
This cluster:

```python
cluster = SLURMCluster(cores=8, processes=2, threads_per_worker=4,
                       memory="24GB",
                       queue="medium", interface="ib0")
```

gives me this job script:

```shell
#!/bin/bash

#!/usr/bin/env bash
#SBATCH -J dask-worker
#SBATCH -p medium
#SBATCH -n 1
#SBATCH --cpus-per-task=8
#SBATCH --mem=23G
#SBATCH -t 00:30:00
JOB_ID=${SLURM_JOB_ID%;*}

<path_to_python_env>/bin/python -m distributed.cli.dask_worker tcp://10.246.201.1:41911 --nthreads 4 --nprocs 2 --memory-limit 12.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60 --interface ib0
```

So the sum of the worker memory (2x  `12.00GB`) is larger than the memory requested for the job (`#SBATCH --mem=23G`).

Dask versions are:

```bash
$ conda list | grep -e dask  -e distributed
dask                      1.1.4                      py_0    conda-forge
dask-core                 1.1.4                      py_0
dask-jobqueue             0.4.1                      py_0    conda-forge
distributed               1.26.0                   py37_1    conda-forge
```

**Comment by guillaumeeb** [comment]
Hi @willirath! How are you?

The thing is Dask makes the difference between gigabytes and gibibytes (https://en.wikipedia.org/wiki/Gigabyte_(disambiguation)). Whereas Slurm does only talk in Gibibytes (this is what is written here https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/slurm.py#L112). This is the case for PBS, so this may be something inherited from PBSCluster class.

Thus 
> So the sum of the worker memory (2x 12.00GB) is larger than the memory requested for the job (#SBATCH --mem=23G).

is probably not true. 24 * 10**9 < 23 * 2**30

You can use ` memory="24GiB"` to disambiguate.

**Comment by willirath** [comment]
> Hi @willirath! How are you?

Not bad. :) But mostly busy with non-dask stuff.  So I didn't get to be as active here as I wanted to...

> > So the sum of the worker memory (2x 12.00GB) is larger than the memory requested for the job (#SBATCH --mem=23G).

> is probably not true. `24 * 10**9 < 23 * 2**30`

Not sure about this. I got "worker was killed, probably due to memory issues" without the Nanny kicking in at 95% (worker) memory use.  So that might be slurm killing the process because of memory issues?

I'll investigate this and come up with a demo if this turns out ot be true.

**Comment by guillaumeeb** [comment]
>  So I didn't get to be as active here as I wanted to...

Yep I can share that feeling.

>  I got "worker was killed, probably due to memory issues" without the Nanny kicking in at 95% (worker) memory use. So that might be slurm killing the process because of memory issues?

Slurm should tell you if it has killed the job, doesn't it? With PBS we have some information about this.

**Comment by guillaumeeb** [comment]
Did you investigate more on this @willirath? Do you need something else, or can this be closed? We could add some doc about gibibyte vs gigabytes...
