### ISSUE TITLE
workers without threading

### ISSUE THREAD

**Issue by basnijholt** [dask/dask-jobqueue#265]
I need to avoid a shared memory at all cost because of [issues](https://github.com/sympy/sympy/issues/16030).

With `ipyparallel` I can just start a `ipcluster` with a resulting jobscript (and single job) that looks like (to start 200 cores):
```bash
#!/bin/sh
#SBATCH --ntasks=200
#SBATCH --tasks-per-node=24
#SBATCH --cpus-per-task=1
srun ipengine --profile-dir="/gscratch/home/t-banij/.ipython/profile_slurm" --cluster-id=""
```
This will result in 200 Python processes that are independent.

I try to do the same with `dask_jobqueue` by doing the following:

```python
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(
    cores=1,
    processess=1,
    memory="16GB",
    project="WAL",
    walltime="240:00:00",
    queue="debug",
    local_directory='TMPDIR',
    log_directory='TMPDIR',
    env_extra=[
        "export MKL_NUM_THREADS=1",
        "export OPENBLAS_NUM_THREADS=1",
        "export OMP_NUM_THREADS=1",
    ],
)
cluster.scale(500)
```
However, this will create as many job scripts as there are cores. 

I would like to avoid this because SLURM tends to send different jobs to different nodes. So if I want to start 500 cores, I usually occupy one CPU on 500 nodes. This is undesirable for my colleagues that run with `#SBATCH --exclusive`.

Is it possible to create fewer jobs with more cores, however with independent Python processes (or no threading at least)?

**Comment by guillaumeeb** [comment]
Yes it is! You can have one job per node. However, note that you cannot have multi nodes job with dask-jobqueue.

If your compute nodes have 24 cores and 256GB of memory:

```python
cluster = SLURMCluster(cores=24, 
                 processess=24,
                 memory='256GB'
                 ...)
cluster.scale(500)
```

**Comment by basnijholt** [comment]
Thanks, I did try that before, but it seems like there is still some shared memory.

I have been struggling with this problem for 2 years, haha. And unfortunately (because of the threading) it's extremely hard to debug. The following code is the simplest way (for me) to reproduce it. See [this](http://nbviewer.jupyter.org/url/files.nijho.lt/dask-slurm-fail.ipynb?flush_cache=true) notebook.

**Comment by guillaumeeb** [comment]
There should not be any shared memory, using `processes=24`, dask distributed will fork 24 independant processes.

However, looking at your notebook:
```python
    processess=8,
    memory="16GB",
```
means you will have only 2GB per process. Is this enough?

Can you look at http://jobqueue.dask.org/en/latest/debug.html#interact-with-your-job-queuing-system and give more details, like stderr or stdout of your jobs?

**Comment by ocaisa** [comment]
I'm guessing you are not tripping over this IRL but there is a rolling typo through the comments here, it should be `processes` and not `processess`

**Comment by willirath** [comment]
The typo may well be the reason for this weird behaviour here?  All unknown keywords are just caught by `**kwargs`: <https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L182>

**Comment by guillaumeeb** [comment]
Whoops, Nice catch, I just copy pasted it wuthout seeing!

**Comment by basnijholt** [comment]
Wow, yeah that typo was the culprit! It works now.

Thanks to all for your bug-vision 😇
