### ISSUE TITLE
Workers don't clean after themselves

### ISSUE THREAD

**Issue by edurand** [dask/dask-jobqueue#266]
Hi,

When a worker completes its tasks, it would be nice for the directories and files that were created to be automatically deleted (worker-XXXX directories and lock files). When running large jobs, all these extra files are quite the clutter :)

Thank you!

**Comment by ericmjl** [comment]
Just had a thought - is there a way to configure where the dask worker directories go?

**Comment by guillaumeeb** [comment]
Hi @edurand and @ericmjl,

In my setup, I put worker directories and file in a local space on my compute nodes. See http://jobqueue.dask.org/en/latest/examples.html#pbs-deployments: 
```python
local_directory='$TMPDIR',
```

This way, PBS Pro scheduler just removes this folder when job ends.

Generally, it is recommended to [use a local storage for this directories](http://jobqueue.dask.org/en/latest/configuration-setup.html#local-storage). On the same document page is described the approach to take when you have no local storage.

If you are in another case, then I think this issue belongs to the upstream repository [distributed](https://github.com/dask/distributed). Worker process should clean their storage space when they are stopped.

**Comment by edurand** [comment]
Hi @guillaumeeb this is a good solution - it works well for me. Thanks for pointing this out!

**Comment by guillaumeeb** [comment]
Glad to hear it, closing then, and I hope your enjoying working with Dask and dask-jobqueue !
