### ISSUE TITLE
Deprecation warning from distributed

### ISSUE THREAD

**Issue by ocaisa** [dask/dask-jobqueue#267]
With `dask 1.2.0` and `distributed 1.27.0` there is now a deprecation warning
```
/.../lib/python3.6/site-packages/distributed/deploy/local.py:106: UserWarning: diagnostics_port has been deprecated. Please use `dashboard_address=` instead
```

**Comment by ocaisa** [comment]
Comes from https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/core.py#L246

**Comment by guillaumeeb** [comment]
Thanks @ocaisa for the input!

I'm not sure what should be done here? Probably modify the incriminated line, but also change the distributed and dask required version.

Would you want to do this?

**Comment by ocaisa** [comment]
I would but I probably don't understand the implications of this. From http://distributed.dask.org/en/latest/local-cluster.html , the argument is now a string and I believe the change should be:
```
kwargs.setdefault("dashboard_address", ("", ":8787"))
```
but this is already the default (I think), so I wonder if there is a point setting it explicitly? Should I just remove the line and bump the distributed version to `1.27.0`?

**Comment by guillaumeeb** [comment]
> but this is already the default (I think), so I wonder if there is a point setting it explicitly?

We may have to explicitly set this in the case we also set a specific IP or interface for the scheduler. Before this change, setting an IP to the scheduler would make it the default IP for the dashboard too. 
This is probably still the case, so I would just leave the line with the new kwarg. No need to change the value as you mention, just do:

```python
kwargs.setdefault("dashboard_address", ("", 8787))
```

And bump the distributed version (and maybe dask one accordingly).
