### ISSUE TITLE
Unexpected behaviour with `KilledWorker` Exception in adaptive mode

### ISSUE THREAD

**Issue by wkerzendorf** [dask/dask-jobqueue#270]
There has been a long-standing issue #122 and in I've seen other threads about this and I **believe** that this is a simple design issue. The problem appears if there are queues that last longer than a slurm allocation or if the nanny kills workers. 

In both cases, the worker is killed and the future immediately raises a killed worker exception on the future of that task (which unexpectantly is not caught) and all other tasks scheduled on this worker.
@mrocklin @guillaumeeb does that accurately describe the current design?

The expected behaviour (IMO) is that the task(s) is/are reallocated to the next worker that becomes free and that the queue continues (with the added problem that if the worker is killed by SLURM - all other workers are killed at the same time). 

@rcthomas - that is interesting for our problem probably.

**Comment by mrocklin** [comment]
Tasks will be reallocated to other workers if the worker on which they live dies.  See https://stackoverflow.com/questions/46691675/what-do-killedworker-exceptions-mean-in-dask

**Comment by wkerzendorf** [comment]
That is not the behavior I experience. As soon as the first task triggers a nanny restarting the worker. It seems that many tasks start to error. It is definitely not 3 Times but the first time and then many tasks start to exhibit a killedworker exception. Is there a way to restart the worker after each task - that might be a temporary fix

**Comment by wkerzendorf** [comment]
I'm now testing with this code

```python
import pandas as pd
import numpy as np
from dask.distributed import Client, LocalCluster, Queue, as_completed
from distributed.scheduler import KilledWorker

from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(walltime='00:20:00', memory='1 GB', 
                       job_extra=['--nodes=1', '--ntasks-per-node=1'], 
                       cores=4)#, extra=['--resources processes=1'])
client = Client(cluster)

cluster.adapt(minimum=0, maximum=20)

def test_worker(n):
    import time
    import numpy as np
    if n%5 == 0:
        time.sleep(60)
        np.empty(int(7e8), dtype=np.float64)
    else:
        time.sleep(60)
    return n

futures = [client.submit(test_worker, n) for n in np.arange(20000)]
```

**Comment by wkerzendorf** [comment]
@mrocklin I'm still waiting to get scheduled on my slurm cluster to try it out. But I think I **might** have found a bug (depending what is in the variable):
here https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L1931 - dask loops through all the tasks that are processing on a worker (not sure what processing means in this case) - and marks them all as suspicious (even though only one is "suspicious"). It could be that in the processing dict at that time, we have all the tasks queued on that worker. 

My hypothesis is that given my setup of 4 workers and 100k tasks that that 25k tasks are in that  dictionary and get their suspicious +1 mark when the first worker is killed due to reaching the memory limit (I have a memory leak problem that only appears on dask and not when running my code outside of dask). Then the suspicious tasks (25k) are transferred to the next worker that is NOT YET killed. when the next worker goes down due to the memory limit all the tasks on that worker are again marked as suspicious +=1 which gets most of them the second suspicious flag. This continues until essentially all tasks have earned 3 suspicious flags. This would explain the behavior. Let me know what you think.

**Comment by mrocklin** [comment]
Yes, that is how things work.

**Comment by mrocklin** [comment]
Unfortunately the scheduler doesn't know precisely which task a worker is
working on at any given time.

**Comment by wkerzendorf** [comment]
I see that is unfortunate for my problem. That means setting the allowed supicious flag to ridiculous high numbers is a potential solution. 

I also was wondering if I can make the nanny kill my worker after every task to clean-up the memory problem.

**Comment by wkerzendorf** [comment]
I ran it with 1e20 allowed suspicious flags and now get multiple other errors:

```python
  File "/beegfs/wek224/miniconda/envs/tardis3/lib/python3.6/site-packages/distributed/scheduler.py", line 1410, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://172.16.2.190:41508
```

```python
ValueError: Worker already exists tcp://172.16.2.188:35978
Worker tcp://172.16.2.185:35385 restart in Job 1293199. This can be due to memory issue.
distributed.utils - ERROR - 'run_tardis_dask-8e2fc0581d59c519a2e6dbf68a20619c'
```

followed several thousand messages later by 

```python
line 182, in move_task_request
    self.scheduler.stream_comms[victim.address].send(
KeyError: 'tcp://172.16.2.169:44892'
tornado.application - ERROR - Exception in callback <bound method WorkStealing.balance of <distributed.stealing.WorkStealing object at 0x2b8f2b8ef978>>
```

**Comment by guillaumeeb** [comment]
@wkerzendorf, this issue as gone a little stale. Where you able to fix your problem? It still looks like a memory issue which causes you workers to be restarted...

Did you observe this with the code snippet above?

**Comment by wkerzendorf** [comment]
I just started a new position and am a bit swamped - but I will want to use dask again for my research. We can close it and I'll reopen later if there are issues - or we can leave it open until I have a chance to try it out again. Thanks for looking into this!

**Comment by guillaumeeb** [comment]
OK thanks, so let's close this one.
