### ISSUE TITLE
ModuleNotFoundError on ipywidgets with minimal install

### ISSUE THREAD

**Issue by stsievert** [dask/dask-jobqueue#271]
I'm running dask-jobqueue and have a minimal installation with miniconda. I've installed miniconda, JupyterLab, NumPy/Pandas/Scikit-Learn and Dask/Distributed. After I do that and run the following in a cell

``` python
cluster = SLURMCluster(...)
cluster
```

I get the traceback

``` python-traceback
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/miniconda3/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    916             method = get_real_method(obj, self.print_method)
    917             if method is not None:
--> 918                 method()
    919                 return True
    920 

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/cluster.py in _ipython_display_(self, **kwargs)
    215 
    216     def _ipython_display_(self, **kwargs):
--> 217         return self._widget()._ipython_display_(**kwargs)

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/cluster.py in _widget(self)
    151             pass
    152 
--> 153         from ipywidgets import Layout, VBox, HBox, IntText, Button, HTML, Accordion
    154 
    155         layout = Layout(width="150px")

ModuleNotFoundError: No module named 'ipywidgets'
```

**Comment by stsievert** [comment]
I'm unsure where to file this. I'm filing it here because it's most related. I suspect this is a distributed issue.

**Comment by lesteve** [comment]
Weird, I would guess that this is a `distributed` problem indeed. Have you tried whether you get the same problem with `cluster = LocalCluster()`?

**Comment by lesteve** [comment]
I can reproduce the problem locally with a `distributed.LocalCluster` when `ipywidgets` is not installed I am going to close this one.

For completeness it does not seem that easy to fix in a clean way in the sense that when `_ipython_display_` has an error it kind of falls back to `__repr__` but it still displays the traceback of `_ipython_display_`. Note sure whether this is a `IPython` problem, and not sure there is a not too complicated work-around we could use in `distributed`:

Code:
```py
class A:
    def _ipython_display_(self):
        1/0
    def __repr__(self):
        return '__repr__'
    
A()
```

Ouput inside a notebook (note that `__repr__` is still showed in the output prompt):

![image](https://user-images.githubusercontent.com/1680079/58577785-89574e80-8247-11e9-948e-5a48d417803c.png)

**Comment by stsievert** [comment]
Thanks @lesteve. I’ll push this upstream
