### ISSUE TITLE
Usage breakdown

### ISSUE THREAD

**Issue by dcieslak19973** [dask/dask-jobqueue#285]
We're looking at using dask-jobqueue and are trying to assess whether to use PBS or SLURM. If 80% of users are using one or the other, we'd like to go that direction; if numbers are closer to 50-50, we'd use other metrics to decide.

Does the community tend towards one or the other, or is it more of a 50-50 break?

Thanks

**Comment by guillaumeeb** [comment]
From what I've seen on this project issues, this is more like 50-50. I think these are the two most used batch scheduling system from the community around dask-jobqueue, but I don't see a clear winner. 

To be clear, I'm only speaking in term of number of dask-jobqueue users I've talked to one way or another, I'm not talking about software quality or functionnality.

**Comment by dcieslak19973** [comment]
Thanks; feel free to close this ticket
