### ISSUE TITLE
ClusterManager: dashboard_link not working since dask>= 2

### ISSUE THREAD

**Issue by joschaschmiedt** [dask/dask-jobqueue#288]
Since the das.distributed commit [d202e6253ed8ddc7919d0d4f128d88954e9859b8](https://github.com/dask/distributed/commit/d202e6253ed8ddc7919d0d4f128d88954e9859b8#diff-b701ae6089e410739e69f91ff503e2d4), the scheduler services key for the scheduler is `'dashboard'` and not `'bokeh'` anymore.  Therefore the `ClusterManager.dashboard_link` property fails with a `KeyError`:
https://github.com/dask/dask-jobqueue/blob/bff96a329439c23414bd0cb11c0ee8e67145d96b/dask_jobqueue/deploy/cluster_manager.py#L143

**Comment by guillaumeeb** [comment]
Thanks, would you open a Pull Request to fix that?

**Comment by stuarteberg** [comment]
Will be fixed when #291 is merged.

**Comment by lesteve** [comment]
I had a look at this. `bokeh` -> `dashboard` happened in distributed 2.0: https://github.com/dask/distributed/commit/d202e6253ed8ddc7919d0d4f128d88954e9859b8.
dask-kubernetes change `bokeh` -> `dashboard` in dask-kubernetes 0.9. https://github.com/dask/dask-kubernetes/commit/038d2bbec50d3fd3e31e7fef490f0de89307b4d9 without checking for the `bokeh`. In other words `dask-kubernetes` is only compatible with `distributed >= 2`.

I suggest we do something similar for dask-jobqueue i.e. `bokeh` -> `dashboard` without backward compatibility. @guillaumeeb any strong opinion on this?

**Comment by lesteve** [comment]
If we agree on this, we may want to look at other possible issues related to distributed >= 2 e.g. https://github.com/dask/dask-jobqueue/pull/278 and we do a release afterwards.

**Comment by lesteve** [comment]
@stuarteberg @joschaschmiedt how does this bug manifest itself in practice? Am I right in thinking that the main impact is that the dashboard link does not show up in the cluster widget?

OK I guess you can call `cluster.dashboard_link` directly and get an error but I am guessing this is probably not how you encountered it.

**Comment by stuarteberg** [comment]
Actually, that’s exactly how I encountered it.

On Jul 19, 2019, at 12:33, Loïc Estève <notifications@github.com<mailto:notifications@github.com>> wrote:


@stuarteberg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stuarteberg&d=DwMCaQ&c=LU6cRtx0xgB8s29tIz9Olw&r=jwWc8kPdMp_9wbd8ag2Yp4XY5-5zRJxVt7sbSeHVEPU&m=XPX5QqGDzEXRjlUXDRUZYIWkj0YKsOtQyRd8fAYV964&s=a8sljO4a0OylyHHM1lbw_LbjMaDVsTAKENVPhgPtadw&e=> @joschaschmiedt<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_joschaschmiedt&d=DwMCaQ&c=LU6cRtx0xgB8s29tIz9Olw&r=jwWc8kPdMp_9wbd8ag2Yp4XY5-5zRJxVt7sbSeHVEPU&m=XPX5QqGDzEXRjlUXDRUZYIWkj0YKsOtQyRd8fAYV964&s=-IYT0qAlnxhX25n1k_csRli6pUSNHe6K-ccnI_omDo8&e=> how does this bug manifest itself in practice? Am I right in thinking that the main impact is that the dashboard link does not show up in the cluster widget?

OK I guess you can call cluster.dashboard_link directly and get an error but I am guessing this is probably not how you encountered it.

**Comment by lesteve** [comment]
Interesting I did not know about `dashboard_link` and I would not have assumed that people would call it directly. I always used `client.scheduler_info['services']` when I wanted to figure out the port the dashboard was running on for some (probably historical) reason.

**Comment by guillaumeeb** [comment]
> I suggest we do something similar for dask-jobqueue i.e. bokeh -> dashboard without backward compatibility. @guillaumeeb any strong opinion on this?

I'm perfectly fine with this! 6.0 release was meant to be compatible with Dask and distributed 2.0, so we could push a 6.1 release then.
