### ISSUE TITLE
Cobalt Support

### ISSUE THREAD

**Issue by Phantom139** [dask/dask-jobqueue#298]
Continuing conversation from #202, I have an allocation on Argonne's Theta cluster which uses the Cobalt job scheduling system. While the general framework of dask-jobqueue does seem to fit in with the background process once the job is in the queue, there are a few nitpicky things I have been trying to work out over the course of the day while also dealing with a high user workload causing testing to be slow.

My work so far has been placed on the develop-cobalt branch of my fork located here: https://github.com/Phantom139/dask-jobqueue

Here are the primary differences I have noticed with Cobalt compared to some of the other clusters.

- First, when submitting a job on Cobalt (Might be an Argonne specific thing), the job id gets sent through stdout while additional job information is passed through stderr prompting a return code of 1 when calling **qsub**, which in the current implementation of _call() throws an exception.
- Second, Cobalt requires all job script files to be executable while the script only writes out a plaintext file for the job, this was fixed with a simple addition of a chmod +x call before calling self._submit_job() in the start_workers() definition
- I'm unsure if this is due to the newline terminator after the 'shebang', but for some reason Cobalt is not recognizing the headers created in the jobfile, so I added capability to instead attach the relevant parameters to the command line call of **qsub**.

I still need to test my code a bit more to verify things are working, and I have no idea if this will work for other Cobalt clusters, but it should be a start.

**Comment by Phantom139** [comment]
Just an update on my current progress on implementing Cobalt support. I can get the job script to be generated, for my test application it looks like this:

```
#!/bin/bash

#COBALT -q debug-cache-quad
#COBALT -A climate_severe
#COBALT -t 60
#COBALT -n 8



/projects/climate_severe/Python/anaconda/bin/python3.7 -m distributed.cli.dask_worker tcp://140.221.69.22:39363 --nthreads 64 --memory-limit 100.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60
```
This is being submitted to the cluster and the job does start, however there is no output from the job and it does not save the log files that Cobalt generated (JOBID.output & JOBID.error). The script that is using this cluster is set up like so:

```
		cluster = CobaltCluster(processes=1,
							   memory="100GB",
							   cores=64,
							   ncpus=8,
							   project="climate_severe",
							   walltime="60",
							   queue="debug-cache-quad")
		cluster.scale(1)
		dask_client = Client(cluster, timeout=60)
		calculation_future = dask_client.map(run_calculation_routines, fList)	
		wait(calculation_future) 
```

The job aborts very shortly after it starts and without any notifications I can't debug further. Does anything here look off?

**Comment by Phantom139** [comment]
I was able to generate a more simple task to test with: 
```
import numpy as np
import dask.array as da
from dask.array import map_blocks
from dask.distributed import Client, progress, metrics, wait
import dask_jobqueue
from dask_jobqueue import CobaltCluster

def test_calculation(in_data):
	return in_data + 1

print("*** DASK JOBQUEUE TEST")
print("INITIALIZE CLUSTER")
cluster = CobaltCluster(processes=1,
					   memory="100GB",
					   cores=64,
					   ncpus=1,
					   project="climate_severe",
					   walltime="60",
					   queue="debug-cache-quad")
cluster.scale(1)
dask_client = Client(cluster, timeout=60)

huge_array = np.arange(10000, 100000, 1)
dask_array = da.from_array(huge_array)

calculation_future = dask_client.map(test_calculation, dask_array)	
wait(calculation_future)

result = dask_client.gather(calculation_future)
print("RESULT:\n\n" + str(result))

cluster.stop_all_jobs()
dask_client.close()

print("*** PROGRAM COMPLETE")	
```

This time, I was able to collect log & error files from the job and it would appear as if something is holding up the connection.

```
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '140.221.69.22', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:34479'
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:37599
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:37599
distributed.worker - INFO -          dashboard at:            127.0.0.1:43183
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:37233
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         64
distributed.worker - INFO -                Memory:                  100.00 GB
distributed.worker - INFO -       Local Directory: /lus/theta-fs0/projects/climate_severe/Python/worker-c9z2oyfv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:37233
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:37233
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:37233
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:37233
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:37233
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:34479'
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:37599
distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: None, threads: 64>' to scheduler 'tcp://140.221.69.22:37233'
Traceback (most recent call last):
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/nanny.py", line 303, in instantiate
    timedelta(seconds=self.death_timeout), self.process.start()
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
tornado.util.TimeoutError: Timeout
distributed.dask_worker - INFO - End worker
```

Any ideas on what's happening and how I might approach fixing this?

**Comment by lesteve** [comment]
Could it be the same thing as https://github.com/dask/dask-jobqueue/issues/293#issuecomment-513640277?

If that's the same thing, I think this is a general dask caveat, if you have some idea how we could improve the dask-jobqueue documentation that'd be great! Maybe by putting a more complete script in our doc or maybe in the dask distributed doc somewhere.

Overall this looks like this is going in the right direction, congrats for this! Here are a few pointers for the questions you had above:

* qsub return code of 1: weird Cobalt qsub does not seem to follow the usual convention of exiting with an exit code of 0 when everything goes fine. Is there something in the stderr that indicates why the exit code is not 0? When you use qsub directly do you also get a non-zero exit code?
* chmod: this is fine and can leave in your CobaltCluster specific code.
* script vs command-line arguments: ideally submitting a script would be nicer (this is what most `*Cluster` classes do and can be easily inspected it with `.job_script`). Note that `OARCluster` I could not figure out a way to get it to work with a script so I hacked something to turn the headers in the script into command-line arguments (see [this](https://github.com/dask/dask-jobqueue/blob/79be8124c6e410732d7bcdc691cfcbd1401bbe01/dask_jobqueue/oar.py#L104) for more details)

**Comment by Phantom139** [comment]
I added the wait call to my script:
```
import numpy as np
import dask.array as da
from dask.array import map_blocks
from dask.distributed import Client, progress, metrics, wait
import dask_jobqueue
from dask_jobqueue import CobaltCluster

def test_calculation(in_data):
	return in_data + 1

print("*** DASK JOBQUEUE TEST")
print("INITIALIZE CLUSTER")

num_workers = 1

cluster = CobaltCluster(processes=1,
					   memory="100GB",
					   cores=64,
					   ncpus=1,
					   project="climate_severe",
					   walltime="60",
					   queue="debug-cache-quad")
cluster.scale(num_workers)
dask_client = Client(cluster, timeout=60)
dask_client.wait_for_workers(n_workers=num_workers)

huge_array = np.arange(10000, 100000, 1)
dask_array = da.from_array(huge_array)

calculation_future = dask_client.map(test_calculation, dask_array)	
wait(calculation_future)

result = dask_client.gather(calculation_future)
print("RESULT:\n\n" + str(result))

cluster.stop_all_jobs()
dask_client.close()

print("*** PROGRAM COMPLETE")
```

Unfortunately this did not resolve the error I was getting with my script (Same output in the .error file and same error messages).

In terms of the future, I do think having more complete start -> finish examples would be a step in the right direction for documentation purposes as some areas are quite lacking and generally have me digging through google searches or needing to bug some of my colleagues who are a bit more experienced with Dask.

**Comment by lesteve** [comment]
Could you try https://jobqueue.dask.org/en/latest/debug.html#activate-debug-mode to see whether you get more information in the logs?

On top of this, can you describe what you are seing in a little bit more details:
- which print commands do you see from your main script? Does it go past the client_wait_for_workers? does it go past the `dask_client.gather` (note you don't need the `wait(calculation_future)` as the client.gather will block until you get the result back)
- what do you see with `qstat`, do you see a job that starts and then dies very quickly (say in less than 5 seconds) do you see a jobs that stays there for longer (around a minute) and then dies.
- I did not quite follow what the status was regarding the job-id parsing did you get the qsub command to exit with a 0 exit code and the job-id parsing to work. I seem to remember you need the job-id parsing to work. 
- can you have information about the job after it has ended? In SGE you can do `qacct -j the-job-id` and can infer from this whether the job terminated normally or killed by the job scheduler. Maybe there is an equivalent on Cobalt.

Documentation is tricky to get right: amongst other things we are at the intersection of dask and HPC and both have quirks that can be confusing if you are not familiar with them. Of course suggestions and help are more than welcome about improving the documentation! To be honest, being a new user and having a fresh set of eyes is the best place you can be to improve the documentation significantly!

**Comment by Phantom139** [comment]
Added a few more debug prints to the call and turned on the debug mode. Here's the prints specifically from the debug call.

<details>
<summary>Debug Log</summary>

```
Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn("\n" + msg)
DEBUG:Job script:
 #!/bin/bash

#COBALT -q debug-cache-quad
#COBALT -A climate_severe
#COBALT -t 60
#COBALT -n 1



/projects/climate_severe/Python/anaconda/bin/python3.7 -m distributed.cli.dask_worker tcp://140.221.69.22:44362 --nthreads 64 --memory-limit 100.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60

CLUSTER INITIALIZAED
SCALING TO 1 WORKERS
INITIALIZING DASK CLIENT WITH CLUSTER OBJECT
DEBUG:Found 0 active/pending workers.
DEBUG:Scaling up to 1 workers.
DEBUG:starting 1 workers
DEBUG:writing job script:
#!/bin/bash

#COBALT -q debug-cache-quad
#COBALT -A climate_severe
#COBALT -t 60
#COBALT -n 1



/projects/climate_severe/Python/anaconda/bin/python3.7 -m distributed.cli.dask_worker tcp://140.221.69.22:44362 --nthreads 64 --memory-limit 100.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60
DEBUG:Found 0 active/pending workers.
DEBUG:Scaling up to 1 workers.
DEBUG:starting 1 workers
DEBUG:writing job script:
#!/bin/bash

#COBALT -q debug-cache-quad
#COBALT -A climate_severe
#COBALT -t 60
#COBALT -n 1



/projects/climate_severe/Python/anaconda/bin/python3.7 -m distributed.cli.dask_worker tcp://140.221.69.22:44362 --nthreads 64 --memory-limit 100.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60

DEBUG:Executing the following command to command line
chmod +x /projects/climate_severe/runs/20180602/postprd/submit_worker.sh
DEBUG:_call(): Returns:
stdout:
b''
stderr:
b''
DEBUG:Executing the following command to command line
qsub --mode script -q debug-cache-quad -A climate_severe -t 60 -n 1 /projects/climate_severe/runs/20180602/postprd/submit_worker.sh
DEBUG:Using selector: EpollSelector
DEBUG:Using selector: EpollSelector
DEBUG:_call(): Returns:
stdout:
b'357281\n'
stderr:
b'Job routed to queue "debug-cache-quad".\nMemory mode set to cache quad for queue debug-cache-quad\n'

DEBUG:started job: 357281
```
</details>

In terms of your other questions:

- The python script reaches the wait_for_workers() call, then holds indefinitely there. The workers are never seen by the script and I see the job in the queue start, reach the running state, then abort, and the python script that started it doesn't respond beyond that point.
- In terms of the job itself, it starts, runs for about a little over a minute, then aborts.
- For the Job-ID, what happens on this machine is the job-id is returned as a text string to stdout and is properly recovered by jobqueue (See the debug logs above), however additional job information (What queue it was sent to, etc) is pushed through stderr. I added a debug call in the past and this caused a return code of 1.
- I don't see an equivalent command on Cobalt, however the cobalt log file has some information as well:

```
Thu Jul 25 14:23:29 2019 +0000 (UTC) Info: stdin received from /dev/null
Thu Jul 25 14:23:29 2019 +0000 (UTC) Info: stdout sent to /lus/theta-fs0/projects/climate_severe/Python/357279.output
Thu Jul 25 14:23:29 2019 +0000 (UTC) Info: stderr sent to /lus/theta-fs0/projects/climate_severe/Python/357279.error
Thu Jul 25 14:23:29 2019 +0000 (UTC)
Thu Jul 25 14:25:07 2019 +0000 (UTC) Info: task completed normally with an exit code of 1; initiating job cleanup and removal
```

**Comment by lesteve** [comment]
Thanks for the details, do you get more info from the worker logs e.g. the one you posted in https://github.com/dask/dask-jobqueue/issues/298#issuecomment-514829688?

Actually looking closer at this post, I completely missed the warnings about "Couldn't detect a suitable IP address for reaching 'some-ip-address', defaulting to '127.0.0.1': [Errno 101] Network is unreachable". Hmmm this may be part of the problem indeed.

Something you could try is to specify `interface` in your cluster object, you want something like `eth0` or `ib0`. You can look at `ifconfig` to see all the interfaces available. You also want an interface that exists on the machine your main script runs and on the machine your job will be launched. If that does not work, I think you still have an option of specifying `host` to a hostname (or IP address) that is reachable from where your job is going to run.

Here is a few background information about dask in case it helps:
* when you create your cluster object, a dask scheduler is started on the machine you are running your main script from 
* `.job_script()` is submitted and contains the IP address and port of the scheduler (for example in https://github.com/dask/dask-jobqueue/issues/298#issuecomment-514829688 the scheduler address and port was `tcp://140.221.69.22:37233`), when `dask-worker` starts it is supposed to connect to this IP address. If he doesn't manage to do that it will kill itself automatically so as not to waste ressources after some time.

**Comment by Phantom139** [comment]
Here's the full stack trace on the exception:

```
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '140.221.69.22', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:43666'
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:38217
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:38217
distributed.worker - INFO -          dashboard at:            127.0.0.1:42148
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:41923
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         64
distributed.worker - INFO -                Memory:                  100.00 GB
distributed.worker - INFO -       Local Directory: /lus/theta-fs0/projects/climate_severe/Python/worker-rrbhq7g2
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:41923
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:41923
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:41923
distributed.worker - INFO - Waiting to connect to:  tcp://140.221.69.22:41923
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:43666'
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:38217
distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: None, threads: 64>' to scheduler 'tcp://140.221.69.22:41923'
Traceback (most recent call last):
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/nanny.py", line 303, in instantiate
    timedelta(seconds=self.death_timeout), self.process.start()
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
      value = future.result()
tornado.util.TimeoutError: Timeout
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 405, in <module>
    go()
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 401, in go
    main()
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 392, in main
    raise TimeoutError("Timed out starting worker.") from None
tornado.util.TimeoutError: Timed out starting worker.
/projects/climate_severe/Python/anaconda/lib/python3.7/site-packages/distributed/utils.py:139: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
```

Argonne has the system set up that some commands only have root access and ifconfig is one of them, I have an email out to them to ask if they have any information that could help as well. If not, I can swing by their help desk when I'm on site tomorrow.

**Comment by lesteve** [comment]
> Argonne has the system set up that some commands only have root access and ifconfig is one of them

Interesting ... if you are in contact with IT, the best is to ask them whether they have an advice about which network interface you should use.

Out of interest, here is a way to list all the network interfaces in Python. Does this work for you?
```py
import psutil 
psutil.net_if_addrs()
```

**Comment by guillaumeeb** [comment]
Definitly a networking problem.

Just to be clear with what @lesteve told : you need to find the correct interface both on the machine from where you launch your main python script, and on the compute nodes where your Dask workers live.

Maybe 'ib0' is only available on your submission node?

**Comment by Phantom139** [comment]
I was able to run the above command and I got the same interfaces listed from what was given to me from IT.

I am curious though, would choosing the wrong interface cause the listed KeyError? Following the stack trace it is causing the error on this call:
```
psutil.net_if_addrs()[ifname]
```

But if I manually call this from the command line in Python (ex: psutil.net_if_addrs()['ib0']), the output returns as expected.

I'll try all of the interfaces just to be sure though.

**Comment by lesteve** [comment]
> But if I manually call this from the command line in Python (ex: psutil.net_if_addrs()['ib0']), the output returns as expected.

So that probably means that 'ib0' does exit on the submission node but not on the node where the dask-worker runs as @guillaumeeb was saying.

Maybe you could ask IT whether there is a network interface you can use that exists both on your submission node and your worker node. You need the same name on both.

One way you could figure out by yourself what are the network interfaces on your worker node is to `qsub` a python script that runs `psutil.net_if_addrs()` (`qlogin` would be more convenient but not sure whether that is a Cobat thing).

**Comment by Phantom139** [comment]
I see what you mean now, there does not appear to be any network interfaces that exist on both the login and compute nodes (compute only has two network interfaces, and they are different than the ones seen on the login node).

**Comment by lesteve** [comment]
Right, at this point I see two broad general directions:

* Try to get IT involved and ask them whether they would consider changing the cluster setup to have a uniform network interface name. I think the main thing you want to tell them is that you have a scheduler on the node where you main script runs, you have workers on other nodes that you get through `qsub` and that there needs to be some communication between the scheduler and the workers. Maybe you can motivate why that would be useful for your particular use case and if they need extra convincing talk about [Pangeo](https://pangeo.io/) and mention that dask is already used on other big name clusters and that it is extremely useful for researchers productivity.
* keep hacking: this is worth a try but I am not 100% sure this is going to work and will need tweaking. Basically you could try a combination of `host` and `interface`. One thing I would try is this:
```py
cluster = CobalCluster(host=main_script_node_ip_address,
                       interface=worker_network_interface,
                       ...)
```

where `main_script_node_ip_address` is an IP address (or hostname) of the host where your main script runs that your workers can connect to (you can check with `ping` for example), `worker_network_interface` is a network interface that is available on your workers.

**Comment by Phantom139** [comment]
I'll try out the second bullet point. Our group here will try to set up a meeting next week with the IT guys to see if they can open a uniform interface for us to fix this issue.

I'll let you know of any new developments on this.

**Comment by lesteve** [comment]
OK let us know!

**Comment by Phantom139** [comment]
Just wanted to give everyone a quick status update on this. We met with the system adminstrators yesterday and while they are unable to create a universal interface, they did provide some information that should get things moving in the correct direction. I have also been in communication with one of the IT folks in continuation from yesterday's meeting. Some things they noted are as follows:

- The newline terminator between the shebang and the COBALT directives is causing the directives to not be registered by the scheduler, and while passing these as command line arguments is fine for deployment, a full solution really should remove the newline and pass through the jobfile.
- For this specific machine, the compute nodes can communicate through the network by passing the login node's name as a hostname and then using a TCP connection (IE: thetalogin3 for example), which leads to the next issue,
- The 'host' argument on the Cluster classes does literally nothing right now, because according to the definition in core.py, it's only considered if interface is not None. I made a modification of the Cobalt init method to include this in the definition:
```
		if host is not None:
			command_args = [dask_worker_command, host]
		else:
			command_args = [dask_worker_command, self.scheduler.address]
```
- This implementation does not appear to properly create a scheduler on the login nodes that can then communicate with the compute nodes, I had to manually add to my test script the scheduler:
```
loop = IOLoop.current()
t = Thread(target=loop.start, daemon=True)
t.start()

s = Scheduler(loop=loop)
s.start("tcp://: " + str(sched_port))
```
This allows the jobqueue to initialize the single requested worker which then does connect, but the connection appears to immediately break and the script still hangs at the wait for workers call.
```
distributed.worker - INFO -       Start worker at:  tcp://10.237.16.102:44524
distributed.worker - INFO -          Listening to:  tcp://10.237.16.102:44524
distributed.worker - INFO -          dashboard at:        10.237.16.102:44498
distributed.worker - INFO - Waiting to connect to:    tcp://thetalogin4:12345
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   10.00 GB
distributed.worker - INFO -       Local Directory: /lus/theta-fs0/projects/climate_severe/Python/worker-17petjno
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://thetalogin4:12345
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
```

I think we're getting fairly close here, so that's a good thing. Any ideas on what to try next to fix the above issue?

**Comment by lesteve** [comment]
Thanks for the update! At this point what I would recommend is to try to get a simpler setup that works and move out from there.

* Start with familiarising yourself with launching manually `dask-worker`/`dask-scheduler` on a single machine, for example read [this](https://distributed.dask.org/en/latest/setup.html#using-the-command-line).
* Try to run `dask-scheduler` on the login node and `dask-worker` inside an interactive job (if I read correctly [this](https://www.alcf.anl.gov/user-guides/running-jobs-xc40#submitting-interactive-jobs) interactive jobs is a thing with Cobalt)
* Try to `dask-worker` inside a submission script?

To make sure you have a functional dask scheduler with a dask worker connected to it, you want to run a script like this (on the login node):

```py
import time

from dask.distributed import Client

client = Client('tcp://scheduler-ip-address:scheduler-port')

while len(client.scheduler_info()['workers']) < 1:
    print('No workers connected yet')
    time.sleep(5)

future = client.submit(lambda x: x, 1)
print('Got result: ', future.result())
```

Out of curiosity, what were the reasons given by IT for not providing a uniform network interface on all the nodes?

**Comment by Phantom139** [comment]
Sorry for dropping this on the backburner, I've been caught up with some other projects as well so I let this one slide.

In terms of what we were told at the meeting, ALCF and Intel work in tandem when it comes to the chip and the system configurations and their current setup works best for both them and Intel to keep the system compliant with the standards.

While this does remove the "easy option" of using the interface, connection between the nodes is still allowable via tcp:// interface from the compute nodes to the originating login node (named thetalogin# with # being between 1 and 8).

I've been talking with some others at ANL who have used dask on some of the other systems that Argonne has to try to find a solution that works for my problem and may also solve the issue here as well, but so far I have not been able to run any tests or do any extensive developments to see if there is a problem with the code I have written or if something else is going on.

**Comment by guillaumeeb** [comment]
I'm don't really see how we can help more here... From your previous message, it looks like the workers are able to see and connect to the scheduler, but that the connection is terminated right after. I don't know what could be causing this issue...

**Comment by Phantom139** [comment]
This is going to need further investigation. I was able to write a minimal script that calls scheduler and worker directly and it worked fine on the Cobalt machine, but when trying to use jobqueue to automate these processes it fails.

For the purposes of my work, I'll probably be fine going forward with the minimal example and building up, but I'll keep investigating further when I have free time to do so.

**Comment by lesteve** [comment]
Thanks a lot for letting us know! My hope is that by starting with a minimal example that works and building on top of it, you'll learn more about dask and that it will help you to integrate Cobalt in dask-jobqueue in the long run.

This is a bit orthogonal to Cobalt support, but it would be incredibly useful if you let us know if you can figure out a way to work around the non-uniform network interfaces issue. This is something that some people have faced in the past and it would be really great if we had a reasonable answer to this in our documentation (or in our error messages).

Some other comments:
* I was slightly wrong in https://github.com/dask/dask-jobqueue/issues/298#issuecomment-515508749. You  may want to try `ip` and `interface` in the `CobaltCluster` class (rather than `hostname` and `interface`). IIRC `ip` is passed to `LocalCluster` and this decides which ip is used to run the scheduler on. A similar comment is: https://github.com/dask/dask-jobqueue/issues/309#issuecomment-519082293
* it may be worth to ask on gitter ([dask gitter](https://gitter.im/dask/dask) or maybe [Pangeo gitter](https://gitter.im/pangeo-data)) if someone has faced non-uniform network interfaces with `dask-jobqueue` and has managed to find a work-around.

**Comment by guillaumeeb** [comment]
Hey @Phantom139, were you finally able to get somethign up and running on your cluster?

**Comment by Phantom139** [comment]
At the current moment, we haven't been able to get things completely running on COBALT using Cluster, and our primary work machine has switched to a system which employs the SLURM system, for which Dask-JobQueue already fully supports.

This is still an endeavor I'm pursuing, but one that I need to investigate further with the sample scripts I have to see exactly where it is failing.

**Comment by guillaumeeb** [comment]
Closing this issue as stale. @Phantom139 feel free to reopen if you intend to work on this.

**Comment by hmacdope** [comment]
I am facing this at the moment, was there ever a consensus solution reached?

**Comment by guillaumeeb** [comment]
Unfortunately no, it looks it has remained a work in progress, are you working on Cobalt?

**Comment by hmacdope** [comment]
Sorry should have been clearer, was more referring to the mixed network interface stuff.

**Comment by guillaumeeb** [comment]
I'm not sure if this was possible at the time this issue was discussed, but you should normally be able to specify a specific host (or maybe even interface) to bind to for the scheduler, using `PBSCluster(..., scheduler_options({'host': 'your-host-ip-here'})` as [commented here](https://github.com/dask/dask-jobqueue/issues/490#issuecomment-804692781).

So in theory, you could specify an address or interface for the Scheduler different than the one for the Workers.

**Comment by guillaumeeb** [comment]
Looking at the code, I'm not sure this is still true. But it should definitely be possible, so if it does not work, we might want to add this possibility.
