### ISSUE TITLE
Add Grid Engine

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#3]
It might be valuable to extend this repository with a solution for Grid Engine.  My hope is that this is relatively easy for someone with modest grid engine experience.  Looking at the current solutions for [PBS](https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/pbs.py) or [SLURM](https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/slurm.py) might be helpful (they're about 100 lines, mostly docstrings)

**Comment by jhamman** [comment]
I have a fair bit of SGE experience, and a cluster that I could test this on apart from travis. I'd be happy to contribute the SGECluster.
