### ISSUE TITLE
SGE timeout issue

### ISSUE THREAD

**Issue by Rasinj** [dask/dask-jobqueue#309]
I'm having some problems when trying to run jobs using dask_jobqueue. I can't really figure out what piece I'm missing.

I'm trying to run this:

```
from dask_jobqueue import SGECluster
from distributed import Client
from dask import delayed
import time

@delayed
def example_function(thingy):
    time.sleep(2)
    print('Example')
    return thingy

if __name__=='__main__':
    cluster = SGECluster(queue='myq',
                         project='myproj',
                         processes=1,
                         cores=1,
                         memory='4GB',
                         death_timeout=100,
                         resource_spec='m_mem_free=4G')
    print(cluster.job_script())
    cluster.start_workers(1)
    i=2
    future = example_function(i)
    client = Client(cluster)
    client.compute(future)
    print('Finished')
```

The job is submitted properly, but is timing out. Seems like they can't connect to the scheduler

```
(dasktest) ono@host01:~/git/dasktest$ cat dask-worker.o758174
distributed.nanny - INFO -         Start Nanny at: 'tcp://56.172.568.215:43322'
distributed.worker - INFO -       Start worker at: tcp://56.172.568.215:37385
distributed.worker - INFO -          Listening to: tcp://56.172.568.215:37385
distributed.worker - INFO -          dashboard at:       56.172.568.215:36952
distributed.worker - INFO - Waiting to connect to:  tcp://56.142.76.231:42401
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.00 GB
distributed.worker - INFO -       Local Directory: /home/DOM/ono/git/dasktest/worker-mxsadt3h
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:  tcp://56.142.76.231:42401
distributed.nanny - INFO - Closing Nanny at 'tcp://56.172.568.215:43322'
distributed.worker - INFO - Stopping worker at tcp://56.172.568.215:37385
distributed.worker - INFO - Closed worker has not yet started: None
distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: None, threads: 1>' to scheduler 'tcp://56.142.76.231:42401'
Traceback (most recent call last):
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/distributed/nanny.py", line 309, in instantiate
    timedelta(seconds=self.death_timeout), self.process.start()
tornado.util.TimeoutError: Timeout
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 456, in <module>
    go()
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 406, in go
    main()
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/click/core.py", line 764, in __call__


    return self.main(*args, **kwargs)
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/DOM/ono/miniconda3/envs/dasktest/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 397, in main
    raise TimeoutError("Timed out starting worker.") from None
tornado.util.TimeoutError: Timed out starting worker.
```

I guess I'm not completely getting whether I need to submit an independent job to start a scheduler or whether that's handled internally. I was assuming it was handled internally.

What am I missing?

Many thanks!

**Comment by hhyap** [comment]
> This is definitly a dask-jobqueue issue.
> 
> Job submission is handled internally. You seem to have a network problem, the compute nodes where your workers are running are not able to see the Scheduler address.
> 
> You need to use either the `interface` kwarg which allows specifying both network interface to be used by Scheduler host (the host where you start your main python script) and workers hosts (your compute nodes) or `ip` kwarg to specify the IP or hostname the Scheduler host should bind to. Interface is often something like `ib0` if your cluster use Infiniband network. You may need to use both kwarg.
> 
> Another solution is to start the Scheduler and so your script from a compute node, for example in an interactive job.

Thanks for the hint. If `ib0` appears when one does `ifconfig`, then setting `interface="ib0"` helped. If it doesn't (but `gn0` does), then I have to set `interface="gn0"` for it to work. In that case, then the following warning appears:

```
distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available
```

**Comment by guillaumeeb** [comment]
Names of the network interfaces depend about your system configuration, probably done by your admins. When using Infiniband, it is often seen to have a TCP over IB interface that is names `ib0`, but it could be anything!

Anyway, is your problem solved? I'm not sure if the warning is important here...

**Comment by hhyap** [comment]
I faced the same problem as the original poster, it was completely solved on a cluster with ``ib0``. On another cluster with ``gn0``, I keep getting the warning messages mentioned above, but otherwise the problem is solved.

**Comment by guillaumeeb** [comment]
A sorry, I did not notice you were not the person at the origin of this issue!

@Rasinj please tell us if you managed to solve your issue.

**Comment by lesteve** [comment]
Side-comment: I think the error message could be improved when the interface does not exist. I opened a PR on `dask/distributed`: https://github.com/dask/distributed/pull/2964.

The key improvement is to mention the possible network interfaces to push people in the right direction.

We could maybe have a stop-gap solution in `dask-jobqueue` if we think improving the error message is important while waiting for the change to reach a `distributed` release.

**Comment by guillaumeeb** [comment]
Closing this one as stale, and the problem seems related to network interfaces names.
