### ISSUE TITLE
Workers not connecting?

### ISSUE THREAD

**Issue by kforti** [dask/dask-jobqueue#310]
I am not really sure what is happening here. My workers are not connecting to my dask scheduler on LSF. Maybe they are connecting, but they die fast. This appears to happen when I start the scheduler as a part of a larger running program. If I start a standalone cluster on an interactive session it works fine. 

Does the scheduler run on the same process that initializes it? If so, could my code possibly be preventing the scheduler from establishing a connection with the workers before the timeout period? 

```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.192.18.44:34311'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.192.18.44:35472'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.192.18.44:34311'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.192.18.44:35472'
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process 70386 was killed by unknown signal
distributed.nanny - WARNING - Worker process 70387 was killed by unknown signal
distributed.dask_worker - INFO - End worker
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-3, started daemon)>
```

Here is my workers job

```
#!/bin/bash

#BSUB -J dask-worker
#BSUB -q short
#BSUB -P /project/umw_athma_pai
#BSUB -n 12
#BSUB -R "span[hosts=1]"
#BSUB -M 24000
#BSUB -W 04:00
#BSUB -R rusage[mem=2048]
#BSUB -o dask_lsf_cluster.err
#BSUB -o dask_lsf_cluster.out
JOB_ID=${LSB_JOBID%.*}



/share/pkg/python3/3.5.0/bin/python3 -m distributed.cli.dask_worker tcp://10.192.17.134:35314 --nthreads 4 --nprocs 3 --memory-limit 8.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60

```

**Comment by guillaumeeb** [comment]
> Does the scheduler run on the same process that initializes it?

Yes!

Is your main program still running when your workers die? If the Scheduler does not live, the Workers will be killed?

Is this the full worker log that you are giving above? Are the workers able to connect to the scheduler?

**Comment by kforti** [comment]
Hi @guillaumeeb - I have confirmed the workers are not connecting to the scheduler. The problem seems to be isolated to the lsf system I have been using. I moved my code to a separate slurm system and it worked okay. 

The strange thing is that my code was running fine less than a week ago. This has happened once before, and it magically started working again one day. I did some brainstorming with IT but it is still unclear what is causing this problem.

Any thoughts would be greatly appreciated because I would like to get to the bottom of this.

The logs consist of many repetitions of what I have provided.

**Comment by guillaumeeb** [comment]
Hi,

We need some more information here. It looks like a network interface problem: in some case your workers cannot reach the scheduler. The logs are weird though don't you have some information in it that tells to which address the workers are trying to contact the Scheduler?

Does it always work in interactive mode? You talk about interactive sessions, do you use an interactive node or a special machine?

Do you have several machines from which you can submit jobs to the LSF cluster?

**Comment by guillaumeeb** [comment]
I'm closing this as stale. Feel free to re-open @kforti if you have something else to ask.
