### ISSUE TITLE
Obtaining worker information.

### ISSUE THREAD

**Issue by trivialfis** [dask/dask-jobqueue#325]
I'm currently trying to run xgboost with dask on slurm managed cluster.  Internally XGBoost needs to track the uri of each worker and total number of workers: https://github.com/dmlc/xgboost/blob/41227d193359d13efee32c94ae5a314d03615f32/python-package/xgboost/dask.py#L16 .   
After initializing `SLURMCluster`, the "task" is submitted as `jobs` represented in sh scripts, stored in `pending_jobs`.  But the workers list is empty:

``` python
cluster = dask_jobqueue.SLURMCluster(cores=8, memory='12 GB')
cluster.scale(4)
cluster.workers
```
```
Out[28]: SortedDict({})
```
Also if I don't have workers, then calling `client.run` doesn't execute any function so I don't know how to run the above linked function in: https://github.com/dmlc/xgboost/blob/41227d193359d13efee32c94ae5a314d03615f32/python-package/xgboost/dask.py#L119

Could you please provide some suggestions on how to get these workers before run?

**Comment by mrocklin** [comment]
My guess is that your workers weren't able to connect for some reason.  I
recommend checking the logs of your jobs.  Hopefully you can track down the
stdout and stderr files of your SLURM jobs.

**Comment by trivialfis** [comment]
@mrocklin Thanks for the reply.  I tried to read the source code of `cluster.start_workers(n_workers)`, which is introduced in https://jobqueue.dask.org/en/latest/examples.html .  It doesn't involve using callback so I figure it would be easier for me to get my hands dirty.   But I couldn't find any related code for adding worker or nanny.  Could you point me to the code where these workers are supposed to be "connected"?

**Comment by mrocklin** [comment]
I recommend looking at the logs of your jobs.  I also recommend looking at
cluster.job_script()

**Comment by trivialfis** [comment]
@mrocklin Will upload the log files tomorrow when I get access to a linux box ...  But you are right that logging from slurm shows workers are waiting to connect. ;-)

**Comment by mrocklin** [comment]
There are often small details like which network interfaces to use or ports
that can be open that are highly specific to a particular HPC machine.
These are usually not too hard to work around if we have someone who is
familiar with the system, usually an IT administrator or a long-time user.
For examples of other configuration files for other machines you may want
to look at https://jobqueue.dask.org/en/latest/configurations.html .  The
notes in those sections gives some examples of problems that can arise in
the wild.

**Comment by trivialfis** [comment]
@mrocklin Here is the simple script I used:
``` python
from dask.distributed import Client
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(cores=4, memory='1 GB')
cluster.scale(2)


def total_workers(cluster):
    total_jobs = len(cluster.pending_jobs) + len(cluster.running_jobs)
    print('toal_jobs:', total_jobs)
    print('pending:', cluster.pending_jobs)
    total_ws = total_jobs * cluster.worker_processes
    return total_ws


print('total_workers(cluster) BEFORE accepted by client:\n',
      total_workers(cluster))
client = Client(cluster)
print('client:', client)
print('client.cluster:', client.cluster)
print('total_workers(client.cluster) AFTER accepted by client:\n',
      total_workers(client.cluster))
print('client.cluster.workers:', client.cluster.workers)

print('--- job_scripts ---')
print(cluster.job_script())
```

Command used to run:
``` bash
srun -N2 python test_dask.py > srun.log
```

The complete log is attached below.
[slurm.log.zip](https://github.com/dask/dask-jobqueue/files/3539426/slurm.log.zip)

**Comment by trivialfis** [comment]
Sure, and `jobqueue.yaml`:

``` yaml
jobqueue:
  slurm:
    name: dask-worker

    # Dask worker options
    processes: 1                # Number of Python processes per job
    local-directory: ./tmp
    log-directory: ./log
    death-timeout: 60

    interface: null

    walltime: '00:30:00'
    job-extra: []
```

**Comment by mrocklin** [comment]
Looking at the logs it looks like the workers can't connect back to the scheduler.  

```
distributed.worker - INFO - Waiting to connect to:    tcp://10.33.12.15:45049
distributed.worker - INFO - Waiting to connect to:    tcp://10.33.12.15:45049
distributed.worker - INFO - Waiting to connect to:    tcp://10.33.12.15:45049
distributed.worker - INFO - Waiting to connect to:    tcp://10.33.12.15:45049
distributed.worker - INFO - Waiting to connect to:    tcp://10.33.12.15:45049
distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.12.17:40560'
distributed.worker - INFO - Stopping worker at tcp://10.33.12.17:37017
distributed.worker - INFO - Closed worker has not yet started: None
distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: None, threads: 2>' to scheduler 'tcp://10.33.12.15:45049'
Traceback (most recent call last):
  File "/home/jiamingy/anaconda3/envs/XGBoost/lib/python3.7/site-packages/distributed/nanny.py", line 309, in instantiate
    timedelta(seconds=self.death_timeout), self.process.start()
tornado.util.TimeoutError: Timeout
distributed.dask_worker - INFO - End worker
```

So you probably need to investigate network settings.  Maybe specify a different network interface with the `interface=` keyword?

You might want to experiment a bit manually with the `dask-scheduler` and `dask-worker` CLI to see if you can get things to work directly, and then switch back to dask-jobqueue.  

https://docs.dask.org/en/latest/setup/cli.html

**Comment by trivialfis** [comment]
> So you probably need to investigate network settings. Maybe specify a different network interface with the interface= keyword?

Walked through interfaces from `ip addr`, no luck so far.  Very much a newbie to cluster ...

So I tried to use cli interface with no script preloaded, not sure how to put it together with slurm for GPU, will take more time to learn about these.

dask-scheduler:
```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-9bp1zvry
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.dashboard.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: pip install jupyter-server-proxy
distributed.scheduler - INFO -   Scheduler at:    tcp://10.33.12.57:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Register tcp://10.33.12.57:45417
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.12.57:45417
distributed.core - INFO - Starting established connection
```

And `dask-worker`:
```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.12.57:33517'
distributed.diskutils - INFO - Found stale lock file and directory '/home/jiamingy/worker-hkrvt_2i', purging
distributed.diskutils - INFO - Found stale lock file and directory '/home/jiamingy/worker-t89ot7fx', purging
distributed.worker - INFO -       Start worker at:    tcp://10.33.12.57:45417
distributed.worker - INFO -          Listening to:    tcp://10.33.12.57:45417
distributed.worker - INFO -          dashboard at:          10.33.12.57:43768
distributed.worker - INFO - Waiting to connect to:     tcp://10.33.12.57:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         64
distributed.worker - INFO -                Memory:                  201.38 GB
distributed.worker - INFO -       Local Directory: /home/jiamingy/worker-1r1wyiuy
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.33.12.57:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
```

Will come back here after finishing other stuffs. ;-) Thanks for being responsive.

**Comment by guillaumeeb** [comment]
Any news @trivialfis ?

**Comment by trivialfis** [comment]
Looking.

**Comment by trivialfis** [comment]
Now changing the interface to `ib0` resolves the problem.  Might be related to some updates from our server, not sure.  But doesn't seem to be a bug in dask.  Thanks for providing so much help!
