### ISSUE TITLE
Un-nest configuration

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#326]
Currently our configuration has separate entries for each job manager.  Most of the keys within each of these entries are the same.  Should we consider lifting these common keys out to the `jobqueue:` namespace directly?

We would still want to support namespaced configurations for users with multiple job queuing systems on the same NFS, but this could be a special case, rather than required.

**Comment by lesteve** [comment]
No strong feelings on this one but I am not sure how nice this plays with named configuration aka `config_name`. With `config_name`, you can copy and paste the `slurm` section in `jobqueue.yaml`, change `slurm` to `my-config` and use the `my-config` section like this:

```py
cluster = SLURMCluster(config_name='my-config')
```

**Comment by guillaumeeb** [comment]
> We would still want to support namespaced configurations

How would you propose to handle this ? I think we don't want to simplify the configuration at the expense of additionnal code.

**Comment by guillaumeeb** [comment]
Closing this for now as stale and no strong need. @mrocklin feel free to open it again if you have some suggestion on how to do this.
