### ISSUE TITLE
Automatically detect available cores and memory

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#327]
Currently if the user does not provide cores and memory options we provide an informative error message asking them to provide `cores=` and `memory=` keywords.  

By inspecting the local machine, we might change this slightly in two ways:

1.  Provide suggested values like "please provide the following keyword arguments `cores=24, memory="500 GB"`
2.  We could do this automatically, and change the error to a warning

If I recall correctly we guessed cores and memory previously, but we decided to not do this because sometimes the login nodes were different than the compute nodes.  Should we reconsider this?

**Comment by lesteve** [comment]
I am not too convinced by auto-detection I have to admit. Maybe having a more helpful error message with a few examples could help? Something like this:

```
Please provide cores and memory. Here are a few examples:
cluster = FooCluster(cores=1, memory='10GB')
each job you are starting afterwards, e.g. by using cluster.scale, will use one core and 10GB of memory.

cluster = FooCluster(cores=6, processes=2, memory='10GB')
each job you are starting afterwards, e.g. by using cluster.scale, will use 6 cores with 3 threads per process and 10GB of memory.

If you are familiar with your job scheduler, you can look at the output of cluster.job_script() to see the full script which is going to be submitted.
```

Better wording more than welcome!

I noticed another midly annoying thing so I opened https://github.com/dask/dask-jobqueue/issues/329.

**Comment by guillaumeeb** [comment]
I'm not convinced either.

> If I recall correctly we guessed cores and memory previously, but we decided to not do this because sometimes the login nodes were different than the compute nodes

I'm not sure we ever guessed it, but we had a discussion about this. I'm biased as in our setup, login nodes and compute nodes have not the same configuration. Moreover, we have different generations of compute nodes, with different CPU and memory setting. So clearly, we cannot guess it.

We could maybe provide a default setting, like `cores=4, memory='16GB'`, as this setting will probably fit on any machine configuration...

**Comment by lesteve** [comment]
> We could maybe provide a default setting, like cores=4, memory='16GB', as this setting will probably fit on any machine configuration...

I think we have to decide how important being able to do `cluster = FooCluster()` is and whether this is important enough to offset the fact that the default behaviour we chose may be less than great in some cases.

One argument for allowing this, is that the user would not have to think too much about these details to get something up and running.

I agree with @guillaumeeb that having a default setting that is likely to work on most clusters could be an option. I would even be inclined to use `cores=1, memory='4GB'`. Asking for 4 cores per job,  may increase your waiting time in the queue on a very busy cluster (not sure how likely this is in practice).

IMO having a more clever auto-detection mechanism seems tricky and fragile. On SGE you could in principle use `qconf -sq <queue_name>` and parse the output to get the worker nodes of a queue. After that `qconf -se <worker_node>` + parsing of the output could get you memory, number of cores, etc ...

**Comment by mrocklin** [comment]
> IMO having a more clever auto-detection mechanism seems tricky and fragile. On SGE you could in principle use qconf -sq <queue_name> and parse the output to get the worker nodes of a queue. After that qconf -se <worker_node> + parsing of the output could get you memory, number of cores, etc ...

I was thinking of using the current node as a model for a compute node (they are often the same type) and using psutil to get the number of CPU cores and amount of memory.  The login nodes and compute nodes are identical in around 90% of the machines that I've encountered.

>  I would even be inclined to use cores=1, memory='4GB'. Asking for 4 cores per job, may increase your waiting time in the queue on a very busy cluster (not sure how likely this is in practice).

About 30% of the machines that I've encountered require you to consume the full node, and don't allow sharing one node by many jobs.

**Comment by lesteve** [comment]
Interesting insights, thanks for the percentage estimates! To give you an idea of the kind of heteregoneity I am more accustomed to, see [this](https://wiki.inria.fr/ClustersSophia/Hardware) for example (Inria Sophia). Number of cores per node vary from 12 to 80, RAM per node vary from 96GB to 1024GB. The login node has 4 cores and 12GB of RAM but you can also submit from two other "devel" nodes (more powerful nodes for compilation etc ...) that have 12 cores and ~40GB of RAM.

Besides better usability, what advantage do you see of being able to do `cluster = FooCluster()`?

Also if you use the login node number of CPUs, how much would you use as the default values for `cores`? In the clusters I am used to, the login node is less powerful than the compute nodes, but IIRC in @guillaumeeb's case that was the other way around.

**Comment by mrocklin** [comment]
Ah, most of the machines I deal with are pretty homogeneous.  It sounds like I have a biased sample though.

**Comment by mrocklin** [comment]
> Besides better usability, what advantage do you see of being able to do cluster = FooCluster()?

Just usability.

**Comment by lesteve** [comment]
For usability reasons, I could be convinced by a reasonable default + warning saying "you may want to look in more details at `cores` and `memory` because the default may not make sense in your cluster configuration".

I have to admit, it's not clear to me what a reasonable default would be. I am starting to think that `cores=4, memory='16GB'` as proposed by @guillaumeeb is as reasonable as we can get.

**Comment by mrocklin** [comment]
OK.  I think that you've convinced me.  Closing.

**Comment by guillaumeeb** [comment]
> Ah, most of the machines I deal with are pretty homogeneous. It sounds like I have a biased sample though.

Cheyenne and Summit are special references 😃. It maybe funding principles between US and Europe which differ. I've Seen a lot of non heterogeneous platforms here.
