### ISSUE TITLE
Add LSF docker solution to testing matrix

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#330]
We currently have docker setups for SGE, SLURM, and PBS, which are probably the three most common platforms on which people run dask-jobqueue.  These currently live here: https://github.com/dask/dask-jobqueue/tree/master/ci

It would be convenient to also have such a docker setup for continuous testing for LSF, which also seems to somewhat popular.

**Comment by guillaumeeb** [comment]
Duplicate of #115 ?
