### ISSUE TITLE
dashboard_link parameter cannot be set when using SLURMCluster from dask_jobqueue

### ISSUE THREAD

**Issue by naji-s** [dask/dask-jobqueue#335]
I am trying to use the dashboard with SLURMCluster, but setting dashboard_link='127.0.0.1:8787' does not do anything. My code is as follows:
```
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(cores=32,
                     memory="100GB",
#                      project='P48500028',
#                      queue='premium',
#                      interface='ib0',
                    dashboard_link = '127.0.0.1:8787',
                     walltime='00:30:00')

cluster.scale(2)  # Start 100 workers in 100 jobs that match the description above

from dask.distributed import Client
client = Client(cluster) 
```
In fact the output of cluster is just:

Client    
Scheduler: tcp://128.2.204.115:32776 
| Cluster    Workers: 2   Cores: 64   Memory: 200.00 GB

Am I missing something here?

**Comment by lesteve** [comment]
Using `dashboard_address` (rather than `dashboard_link`) works for me:

```py
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(cores=1, memory='1GB', dashboard_address=':12123')
print(cluster.dashboard_link)
```

Output:
```
http://128.93.66.160:12123/status
```

Note that if you rerun the same snippet, the 12123 port is already used so it will pick a random port instead.

Output of executing the same snippet (in the same python session):
```
/home/local/lesteve/miniconda3/lib/python3.7/site-packages/distributed/dashboard/core.py:72: UserWarning: 
Port 12123 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn("\n" + msg)
http://128.93.66.160:37785/status
```

Out of interest, where did you get the `dashboard_link` argument? In an ideal world you would get an error or at least a warning if you were trying to use a parameter that does not make sense ...

**Comment by naji-s** [comment]
That was actually mad bad. I was reading https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html and didn't realize dashboard_link is in attributes and not parameters. 

Any in case, what you suggested also doesn't work and returns this:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-4e59dea4ef69> in <module>
----> 1 print(cluster.dashboard_link)

~/matrix_tf_python/lib/python3.5/site-packages/dask_jobqueue/deploy/cluster_manager.py in dashboard_link(self)
    145     def dashboard_link(self):
    146         host = self.scheduler.address.split("://")[1].split(":")[0]
--> 147         port = self.scheduler.services["dashboard"].port
    148         return format_dashboard_link(host, port)
    149 

KeyError: 'dashboard'
```

**Comment by lesteve** [comment]
There were some changes in `dask/distributed` and thus dask-jobqueue recently, see [this](https://jobqueue.dask.org/en/latest/changelog.html?highlight=changelog) for more details.

In your case, it seems like you are using a recent version of dask-jobqueue but an old version of distributed.

I am confident that updating to the latest versions of dask, distributed and dask-jobqueue will get rid of this error.

**Comment by naji-s** [comment]
Hey thanks for the help. Sadly still getting the same error. I have all those three in their most recent version.

**Comment by lesteve** [comment]
Weird, can you make sure that `bokeh` is installed in your environment. 

Here is a conda command that creates an environment with the latest versions of dask, distributed and dask-jobqueue:
```
conda create -n testenv -c conda-forge dask distributed dask-jobqueue -y 
```

Activating this environment:
```
conda activate testenv
```

I can then execute the snippet above without any problems:
```
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(cores=1, memory='1GB', dashboard_address=':12123')
print(cluster.dashboard_link)
```

Side-comment (not related to your error): unless you have a good reason to use `python 3.5`, I would advise to use `python >= 3.6`.

**Comment by naji-s** [comment]
I am really sorry it was bokeh. So surprising that the error was not implying that.

Thanks a lot!

**Comment by naji-s** [comment]
Thank you so much!
