### ISSUE TITLE
can't find any documentation for how to handle scale for a cluster

### ISSUE THREAD

**Issue by naji-s** [dask/dask-jobqueue#336]
I am using the info here: 
https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html

Sadly there is cluster.scale(10) being used but I could not find any explanation as to what this exactly is! My only goal is being able to use the full potential of my SLURM cluster, but playing around I am not able to make more than 16 workers run on 4 different jobs on slurm. cluster.scale(100) does no different from cluster.scale(10). and the number of jobs on slurm does not change at all when I increase the cores. I am very confused how I am able to specify the number cpus per job or in total and how that would be different from the number of cores(which by the way there is no way to specify)

**Comment by lesteve** [comment]
To sum up:
```oy
# each SLURM job will use 36 cores with 9 dask workers
# Each dask worker will use 4 threads per worker
# creating the cluster object does not launch any job
cluster = SLURMCluster(cores=36, processes=9, memory='16GB')

# the easiest I think is to use scale with cores parameters
# this start one SLURM job which you can see with squeue
cluster.scale(cores=36)
# this starts another SLURM job. You should see 2 SLURM jobs with squeue
cluster.scale(cores=72)

# If you are note using cores parameter scale is in terms of dask workers
# (note: this might change in the next release)
# this should start one SLURM job which you can see through squeue
cluster.scale(9)
# this should start another SLURM job. You should see 2 SLURM jobs with squeue
cluster.scale(18)
```

If you see a way to improve the documentation about this a PR would be more than welcome! Maybe https://jobqueue.dask.org/en/latest/howitworks.html would be a good place to add this kind of content.

Other than this, https://examples.dask.org is a good place to learn more about dask.

**Comment by naji-s** [comment]
Thanks so much @lesteve for all the help. The thing is when I try to use scale there is a lot of crash happening that's not even traceable. I see with cluster.scale(2) that a job 2 jobs start and one of them immediately gets cancelled with no output at all. So it is impossible for me trace the cause of it. I am not sure how I can make things work properly in terms of having multiple jobs, but your explanation definitely helped with my understanding. Thank you! I might try to help with the documentation. What is PR?

**Comment by lesteve** [comment]
> The thing is when I try to use scale there is a lot of crash happening that's not even traceable. I see with cluster.scale(2) that a job 2 jobs start and one of them immediately gets cancelled with no output at all. So it is impossible for me trace the cause of it.

You may want to have a look at: https://jobqueue.dask.org/en/latest/debug.html. In particular, you probably have a SLURM log file named something like `dask-worker.o<your_job_id_goes_here>`. Getting in touch with your cluster sys admin could be an option if you can not figure out why your jobs dies instantly. 

> What is PR?

You may want to look at https://opensource.guide/how-to-contribute/#opening-a-pull-request. I recommend reading the whole page which is quite good.

**Comment by naji-s** [comment]
Sorry for my late get back. Thanks a lot again for the tips.


> You may want to have a look at: https://jobqueue.dask.org/en/latest/debug.html. In particular, you probably have a SLURM log file named something like `dask-worker.o<your_job_id_goes_here>`. Getting in touch with your cluster sys admin could be an option if you can not figure out why your jobs dies instantly.
I have access to those log files. The problem is in this instant crashing case no log file is created! I can only see the jobs when I constantly run squeue and they appear for a brief moment with status PD and then they disappear. 

> You may want to look at https://opensource.guide/how-to-contribute/#opening-a-pull-request. I recommend reading the whole page which is quite good.
Oh thanks! Pull requests. I should look into that.

**Comment by guillaumeeb** [comment]
@naji-s any news here? Were you able to get an explanation on why your jobs are disappearing? A wild guess is that it comes from the job script header generated by dask-jobqueue. You should try to submit worker jobs by hand.

**Comment by guillaumeeb** [comment]
Closing as stale. Feel free to reopen @naji-s if you have new things to add or ask.
