### ISSUE TITLE
Exact associations between SBATCH parameters and SLURMCluster

### ISSUE THREAD

**Issue by naji-s** [dask/dask-jobqueue#337]
I have the following test.slurm file:
```
#!/bin/bash
#SBATCH -J sigmoids_parallel
#SBATCH -t 0-5:59
#SBATCH --ntasks=48
#SBATCH --ntasks-per-node=16
#SBATCH --mem=90000M


python pi.py 1000000
```

which attempts to calculate pi in parallel using the following python file:
```
import sys
from time import time
from mpmath import mp

digits = int(sys.argv[1])
mp.dps = digits

print("Pi is approximately equal to:")

start_time = time()
print(mp.pi)
end_time = time()
seconds = end_time - start_time

print("Done, {} digits in {} seconds".format(digits, seconds))

```
I took the codes from [here](https://www.vanderbilt.edu/accre/getting-started/tutorial/) btw.

The above test.slurm runs 1 job with 3 nodes I assume totalling 48 tasks (which I assume it is equivalent to threads?). I cannot find any equivalent for ntask or ntask_per_node in dask documentation to set this parameters.

Can somebody please help me with this?

**Comment by lesteve** [comment]
You can look at `cluster.job_script()` to see the script that is going to be used for each job. Full disclosure: I am not a SLURM expert.

**Comment by naji-s** [comment]
Thanks! But I still am wondering (independent of SLURM or any other scheduler) how one sets the number threads,  number of jobs (as in number of separate jobs on the cluster), number of nodes (number of nodes involved which is in a way equivalent to jobs I think) and number of workers. The documentation only clarifies "processes" and "cores".

**Comment by lesteve** [comment]
I am assuming that https://github.com/dask/dask-jobqueue/issues/336 answers most of you remaining questions, so I am going to close this one.
