### ISSUE TITLE
AttributeError when passing PBSCluster to distributed.Client

### ISSUE THREAD

**Issue by wtbarnes** [dask/dask-jobqueue#341]
Creating a `PBSCluster` and passing it to distributed client,

```python
>>>import distributed
>>> from dask_jobqueue import PBSCluster
>>> cluster = PBSCluster()
>>> client = distributed.Client(cluster)
```

gives me an exception

```python-traceback
-------------------------------------------------------------------------
AttributeError                          Traceback (most recent call last)
<ipython-input-7-e795384793a0> in <module>
----> 1 client = distributed.Client(cluster)

~/miniconda3/envs/aia-on-pleiades/lib/python3.7/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    653                 loop = address.loop
    654             if security is None:
--> 655                 security = self.cluster.security
    656 
    657         self.security = security or Security()

AttributeError: 'PBSCluster' object has no attribute 'security'
```

## Version Info
* dask 2.4.0
* distributed 2.5.0
* dask-jobqueue 0.6.3

This affects the current releases on PyPI, conda-forge (v0.6.3). However, this seems to be fixed on master.

**Comment by mrocklin** [comment]
My mistake.  Fixed upstream in https://github.com/dask/distributed/pull/3100 .  If you get a chance can you verify that that works for you?  If so then I'll push out a bugfix release.

I should have tested the new releases with dask-jobqueue before pushing them out.  

It will be nice when we release dask-jobqueue@master .  I hope that things become much more consistent then.

**Comment by jhamman** [comment]
@mrocklin - I think we should get 0.7 out here soon. @lesteve and @guillaumeeb, do we have any blockers in our path to releasing?

**Comment by mrocklin** [comment]
I think that @lesteve wanted a window of time for people to test things out on clusters that they have access to.  If that isn't happening though then yes, I would be in favor of releasing soon.  

Personally I don't mind things being a little rough at this point in the project (most users are still early adopters, and most users are pretty friendly).

**Comment by wtbarnes** [comment]
> My mistake. Fixed upstream in [dask/distributed#3100](https://github.com/dask/distributed/pull/3100) . If you get a chance can you verify that that works for you? If so then I'll push out a bugfix release.
> 
> I should have tested the new releases with dask-jobqueue before pushing them out.
> 
> It will be nice when we release dask-jobqueue@master . I hope that things become much more consistent then.

Looks like that fix works with dask-jobqueue v0.6.3. Thanks!

**Comment by wtbarnes** [comment]
> I think that @lesteve wanted a window of time for people to test things out on clusters that they have access to. If that isn't happening though then yes, I would be in favor of releasing soon.

In light of this issue, I'll be running on master anyway so I can provide feedback from the PBS/Pleiades perspective

**Comment by mrocklin** [comment]
distributed 2.5.1 has been released.  It should be on conda-forge within an
hour.
