### ISSUE TITLE
'SLURMCluster' object has no attribute 'security'

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/dask-jobqueue#342]
This is probably server-side issue, but thought I'd report it just in case. I'm running `dask-jobqueue=0.6.3=py_0` on a SLURMcluster. The following code generates an error message (in JupyterLab):

```
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster()
client = Client(cluster)
```

The error message is:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-bc46b4527c7f> in <module>
----> 1 client = Client(cluster)

~/mypath/lib/python3.7/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    653                 loop = address.loop
    654             if security is None:
--> 655                 security = self.cluster.security
    656 
    657         self.security = security or Security()

AttributeError: 'SLURMCluster' object has no attribute 'security'
```

This can be resolved by passing an empty string to security: `client = Client(cluster, security='')`.

**Comment by mrocklin** [comment]
Try updating to distributed==2.5.1

**Comment by SultanOrazbayev** [comment]
I'm having difficulty updating distributed to 2.5.1 via `conda-forge` right now. I see it online at https://anaconda.org/conda-forge/distributed, but my conda update/conda install are not cooperating at the moment, so I will check again on Monday.

**Comment by SultanOrazbayev** [comment]
Using distributed==2.5.1 removes the error message.

**Comment by lesteve** [comment]
@SultanOrazbayev excellent, thanks for letting us know and closing the issue!
