### ISSUE TITLE
'PBSCluster' object has no attribute 'security'

### ISSUE THREAD

**Issue by PhenoloBoy** [dask/dask-jobqueue#343]
With the new release of dask/distributed 2.5.0 I'm getting this error:

~/miniconda3/lib/python3.7/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    653                 loop = address.loop
    654             if security is None:
--> 655                 security = self.cluster.security
    656
    657         self.security = security or Security()

AttributeError: 'PBSCluster' object has no attribute 'security'
Seems that something similar has occurred in the past. [here](https://github.com/dask/dask-jobqueue/issues/24#issue-309150358)

Can anyone help to fix these?

**Comment by lesteve** [comment]
This is a duplicate of https://github.com/dask/dask-jobqueue/issues/342. Make sure that you have `distributed >= 2.5.1`. This should fix the problem.

I am going to close this one, feel free to reopen if the problem persists.
