### ISSUE TITLE
Dask worker stops right after it starts with slurm.

### ISSUE THREAD

**Issue by jianwuwang** [dask/dask-jobqueue#345]
I have a slurm job and a python code (see below). When I submit the slurm job through sbatch, it successfully receives additional nodes from SLURM. But the worker process exits very quickly, leaving the main python code waiting indefinitely. I believe the code worked before. So it could be because some recent update at my insititute cluster. 

I didn't see any error message in slurm outputs for main python code or worker process. Only showing distributed.nanny started and then quickly closed. 

I'm using conda3, dask distributed and dask jobqueue (see version info below). My tests with other conda installation also failed. 

**conda list**
dask                      2.5.0                      py_0  
dask-core                 2.5.0                      py_0  
dask-jobqueue             0.4.1                      py_0    conda-forge
dask-labextension         0.3.1                    pypi_0    pypi
distributed               2.5.1                      py_0 

**Slurm Job**
(base) [jianwu@taki-usr1 xarray-dask]$ more aggregation-file-level-dask-test.slurm
#!/bin/bash -l
#SBATCH --job-name=mod_agg
#SBATCH --output=%x-%j_dask-monthly-aggregation-file-level.out
#SBATCH --error=%x-%j_dask-monthly-aggregation-file-level.err
#SBATCH --partition=batch
#SBATCH --qos=long+
#SBATCH --mem=MaxMemPerNode
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --account=pi_jianwu
#SBATCH --exclusive

/umbc/xfs1/cybertrn/common/Softwares/anaconda3/bin/python /umbc/xfs1/jianwu/common/MODIS_Aggregation/github/MODIS-Aggregatio
n/benchmarking/xarray-dask/aggregation-file-level-dask-test.py 

**Python code**
...
if __name__ == '__main__':

    cluster = SLURMCluster(cores=1, memory='50 GB', project='pi_jianwu', queue='batch', walltime='02:00:00', job_extra=['--exclusive', '--qos=medium+'])

    cluster.scale(3)
    client = Client(cluster)

    tt = client.map(aggregateOneFileData, M06_files, M03_files)

    for future, result in as_completed(tt, with_results= True):
        cloud_pix_global+=result[0]
...

**All worker nodes are up for a short period.**
(base) [jianwu@taki-usr1 xarray-dask]$ squeue -u jianwu
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           1382353     batch dask-wor   jianwu  R       0:01      1 cnode125
           1382354     batch dask-wor   jianwu  R       0:01      1 cnode126
           1382355     batch dask-wor   jianwu  R       0:01      1 cnode139
           1382352     batch  mod_agg   jianwu  R       0:04      1 cnode103

**Slurm output for worker process. All worker nodes are up for a short period.**
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.2.1.125:37896'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.2.1.125:37896'
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.dask_worker - INFO - End worker

**Comment by andersy005** [comment]
@jianwuwang, what is the output of 

```python
print(cluster.job_script())
```

?

**Comment by jianwuwang** [comment]
@andersy005. Thanks for the help. The output is below. Do you know how to change the code to use local IP, not public IP (130.85.28.198)?

#!/usr/bin/env bash
#SBATCH -J dask-worker
#SBATCH -p batch
#SBATCH -A pi_jianwu
#SBATCH -n 1
#SBATCH --cpus-per-task=1
#SBATCH --mem=47G
#SBATCH -t 02:00:00
#SBATCH --exclusive
#SBATCH --qos=medium+
JOB_ID=${SLURM_JOB_ID%;*}



/umbc/xfs1/cybertrn/common/Softwares/anaconda3/bin/python -m distributed.cli.dask_worker tcp://130.85.28.198:45839 --nthreads 1 --memory-limit 50.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60

**Comment by jianwuwang** [comment]
I also tried the print(cluster.job_script()) with conda python 3.7 and got an error message.

python aggregation-file-level-dask-test.py

Traceback (most recent call last):
  File "aggregation-file-level-dask-test.py", line 65, in <module>
    cluster.scale(3)
  File "/umbc/xfs1/jianwu/common/anaconda3/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 143, in scale
    raise NotImplementedError()
NotImplementedError
Exception ignored in: <function Cluster.__del__ at 0x2aaac18be9d8>
Traceback (most recent call last):
  File "/umbc/xfs1/jianwu/common/anaconda3/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 86, in __del__
AttributeError: 'SLURMCluster' object has no attribute 'status'

**Comment by green-codes** [comment]
Are you launching the python code from the SLURM script?

**Comment by jianwuwang** [comment]
@green-codes, I tried launching the python code from a SLURM script and directly on login node. Both failed.

**Comment by green-codes** [comment]
@jianwuwang Dask handles SLURM script generation (as seen in print(cluster.job_script())), and might have caused your error when you launched the python code from your own SLURM script, as this is undefined behavior. 

If you're getting errors when running the python code directly on a login node, please make sure that your Dask client and worker versions match (to the last number). Dask is a quickly evolving platform and a slight version mismatch might cause API incompatibility. 

- This is Jiaxin, Mai over at SDSC forwarded me about your problem. I've been working on Dask on Kubernetes for a few months, and I wouldn't mind communicating more about Dask deployment stuff :P

**Comment by guillaumeeb** [comment]
> If I ran the command manually on a cluster node, it can start worker correctly

This is really weird.

Can you start fresh, install a new conda environment with latest versions of Dask and dask-jobqueue, and report back? Just start simple: Launch a SlurmCluster from a login node, and see it worker can connect to it when calling scale.

**Comment by jianwuwang** [comment]
Thanks for the help. Some of our tests now can run successfully. We are comparing the successful ones and failed ones. One possible reason for the successful runs is we have _srun_ before python command in the slurm file.

**Comment by guillaumeeb** [comment]
@jianwuwang, did you get to the bottom of this? Was this the lack of `srun` in your main slurm file?

**Comment by guillaumeeb** [comment]
Closing this one as stale. It seems @jianwuwang has some solution to his problem. Feel free to reopen if needed.

**Comment by jianwuwang** [comment]
@guillaumeeb, sorry for the late response. We do not have the issue right now. So it is good to us to close it. Thanks!
