### ISSUE TITLE
Use Expert Mode for LSFCluster ?

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#352]
The problem was mentioned in @mrocklin's great blog post: https://blog.dask.org/2019/08/28/dask-on-summit#invalid-operations-in-the-job-script.

The work-around is to use `header_skip` to get rid of the offending lines in the job_script. Maybe a better option would be to allow to submit in "expert mode" instead. 

I originally thought "easy mode" was a Summit cluster scpecific thing, but actually it seems like [LSF thing](https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_csm/lsf_csm_submit_expert.html) although it seems some kind of LSF extension (LSF with Cluster System Manager whatever this means) and not all LSF clusters may have it.

Since `'-csm y'` can be used in `job_extra` maybe this is only something that could be added to the documentation e.g. https://jobqueue.dask.org/en/latest/examples.html#slurm-deployments. @mrocklin if you could try this at one point on Summit this would be great! If there are other `dask-jobqueue` users on Summit, feel free to get them involved of course!

In principle I think something like this should work if I am reading the LSF doc and @mrocklin's blog post correctly:
```py
from dask_jobqueue import LSFCluster
cluster = LSFCluster(
    cores=128,
    memory="600 GB",
    project="GEN119",
    walltime="00:30",
    job_extra=['-csm y']
)
cluster.scale(jobs=3)  # ask for three nodes
```

**Comment by lesteve** [comment]
I seem to remember that at one point you said you could start and scale a `LSFCluster` from a compute node but not from the login node. This could have been because EasyMode was only enabled on the login node.

**Comment by guillaumeeb** [comment]
Closing this issue as stale. If any LSF user is around and wants to test this, please comment!
