### ISSUE TITLE
add options to change the folder of generated script

### ISSUE THREAD

**Issue by songqiqqq** [dask/dask-jobqueue#368]
I use dask-jobqueue with slurm and find the script file is generated at the folder of /tmp. Is there a option for me to change it to a specific folder?  It's requested by the administrator here. Great thanks for any suggention.

**Comment by lesteve** [comment]
> Is there a option for me to change it to a specific folder?

I don't think there is at the moment.

> It's requested by the administrator here

Can you give us a better idea why (or even better ask him/her to comment on this issue if you are not sure)? IIRC the script should be a temporary file which is removed after the submission so I don't really see a reason why that can pose a problem, but of course I may be missing something ...

**Comment by songqiqqq** [comment]
Ok, thanks for your reply.  The cause sounds funny, but  actually that's really the rule in our lab that common users are not suggested to put files in \tmp.  Maybe really weird the administrator is (agree)  or  it's related to the high privacy between different users (actually, it is). 

 However, the problem becomes not fatal for me now and everything works well here. Thanks for your reply and the great project.

**Comment by guillaumeeb** [comment]
Just for the record, I think all this is using https://docs.python.org/3/library/tempfile.html in the background, so you should be able to control the folder. see https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp:
>  The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables
