### ISSUE TITLE
Any methods to assign specific task to specific workers

### ISSUE THREAD

**Issue by songqiqqq** [dask/dask-jobqueue#369]
When using dask/distributed only,  my workflow is :
(1) start different workers with different resources with `dask-worker --memory-limit  large_mem --name A` and `dask-worker --memory-limit small_mem --name B`
(2) submit tasks with different memory consumptions to different workers by `client.submit(f1, workers=[A]` and `client.submit(f2, workers=[b])`. This funciton of dask/distributed perfectly satisfied my needs and i thinks it's really useful for HPC users. 

Is there similar practice when using dask-jobqueue? I cannot find this kind of instruction in dask-jobqueue's doc.  Any suggestions would be greatly appreciated.

**Comment by willirath** [comment]
There currently is no way of easily creating differently sized workers with jobqueue. I'm not sure that this is necessary for what you want to achieve: See https://distributed.dask.org/en/latest/resources.html#example for an example to specify the memory (or other resource) requirements of a task.

**Comment by songqiqqq** [comment]
It's a pity that jobqueue does not support this. Besides, thanks for your share of that link, it's really helpful.
