### ISSUE TITLE
Drop Python 3.5

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#373]
Python 3.5 has been dropped in `distributed` and `dask` 2.7.0 (https://github.com/dask/distributed/commit/e4a0404f0ed3f853a86adf79c48a60620f3e9fb6 and https://github.com/dask/dask/commit/0871699c0e4b021fca4a3104042d1adf7c5fd5d5) i.e. November 2019.

We should probably do the same at one point.

**Comment by guillaumeeb** [comment]
Yep, no objection from me in the 0.8 release!
