### ISSUE TITLE
'SLURMCluster' object has no attribute 'scheduler_info'

### ISSUE THREAD

**Issue by MSKazemi** [dask/dask-jobqueue#385]
With following scripts:
In python 2 it works without error but in python 3 it returns following error
'SLURMCluster' object has no attribute 'scheduler_info'

```
from dask_jobqueue import SLURMCluster
from dask.distributed import Client
import dask.dataframe as ds
cluster =  SLURMCluster(cores=36,
                        processes=36,
                        memory='110 GB',
                        project='XXXX',
                        queue='gll_usr_prod',
                        shebang='#!bin/bash',local_directory='YYYY',
                        walltime='01:00:00', 
                        interface ='ib0',
                        death_timeout=36000,
                        extra=['--memory-limit 0'])

cluster.start_workers(36)
```

**Comment by lesteve** [comment]
This is quite likely that updating `distributed` and `dask-jobqueue` will fix it. Can you post your `distributed` and `dask-jobqueue` versions for further reference?

**Comment by lesteve** [comment]
Also general advice, posting the full stack-trace is very helpful for people trying to understand your problem.

**Comment by MSKazemi** [comment]
> This is quite likely that updating `distributed` and `dask-jobqueue` will fix it. Can you post your `distributed` and `dask-jobqueue` versions for further reference?

Thank you.

Before 
dask: 2.11.0
dask_jobqueu 0.4.1
distributed 2.11.0
I reinstall it starts to work. 

After
dask: 2.11.0
dask_jobqueu 0.4.1
distributed 1.28.1

**Comment by lesteve** [comment]
Glad it fixed it, I am going to close the issue.

My advice would be to have
- a more recent version of dask-jobqueue 0.7 or 0.6.* ...
- dask and distributed with the same version e.g. 2.11.0

**Comment by MSKazemi** [comment]
> Glad it fixed it, I am going to close the issue.
> 
> My advice would be to have
> 
> * a more recent version of dask-jobqueue 0.7 or 0.6.* ...
> * dask and distributed with the same version e.g. 2.11.0

I installed the job_queue version 0.7 now I have the following error:
dask: 2.11.0
distributed 1.28.1


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-e85dde7fe193> in <module>
     10 print('distributed',distributed.__version__)
     11 
---> 12 import dask_jobqueue
        global dask_jobqueue = undefined
     13 print('dask_jobqueu',dask_jobqueue.__version__)

~/miniconda3/lib/python3.7/site-packages/dask_jobqueue/__init__.py in <module>
      1 # flake8: noqa
      2 from . import config
----> 3 from .core import JobQueueCluster
        global core = undefined
        global JobQueueCluster = undefined
      4 from .moab import MoabCluster
      5 from .pbs import PBSCluster

~/miniconda3/lib/python3.7/site-packages/dask_jobqueue/core.py in <module>
     12 import dask
     13 from dask.utils import ignoring
---> 14 from distributed.deploy.spec import ProcessInterface, SpecCluster
        global distributed.deploy.spec = undefined
        global ProcessInterface = undefined
        global SpecCluster = undefined
     15 from distributed.scheduler import Scheduler
     16 

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/spec.py in <module>
     12 from .cluster import Cluster
     13 from ..core import rpc, CommClosedError
---> 14 from ..utils import (
        global utils = undefined
        global LoopRunner = <class 'distributed.utils.LoopRunner'>
        global silence_logging = <function silence_logging at 0x7f35803fd050>
        global ignoring = <function ignoring at 0x7f35803fa050>
        global parse_bytes = <function parse_bytes at 0x7f35803ff170>
        global parse_timedelta = <function parse_timedelta at 0x7f35803ff200>
        global import_term = undefined
        global TimeoutError = undefined
     15     LoopRunner,
     16     silence_logging,

ImportError: cannot import name 'import_term' from 'distributed.utils'

**Comment by lesteve** [comment]
As I mentioned in my previous message I would recommend to use the same version of dask and distributed.

You seem to be using conda, so that should do it:
```
conda update dask distributed -y
```
