### ISSUE TITLE
0.7.1 release

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#399]
Mostly for wider awareness.

I don't have that much time in the next few days to finish https://github.com/dask/dask-jobqueue/pull/398 so my priority is to cut a 0.7.1 relase and delay that until 0.7.2.

There are already a few useful things in 0.7.1:
* different interfaces on scheduler and worker through `scheduler_options`
* all cluster classes: interface set from config file was ignored
* LSFCluster switch to `use_stdin=True` by default (it seems Summit is a bit peculiar)
* OARCluster and HTCondor fixes

**Comment by lesteve** [comment]
0.7.1 was pushed on PyPI.

**Comment by mrocklin** [comment]
Woot.

**Comment by lesteve** [comment]
It was not on my radar that dask was released recently, hmmm maybe I could have waited a bit just in case there were unexpected side-effects. I did check that the Dask-Jobqueue tests pass with Dask/distributed 2.13.

Oh well, given the circumstances, what could possibly go (even more) wrong ;-) ?

**Comment by guillaumeeb** [comment]
Many many thanks @lesteve for keeping on working on dask-jobqueue!

**Comment by lesteve** [comment]
@guillaumeeb no problems, I think you were doing the bulk of the work at one point so it is only fair that I take turns too ;-) !
