### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#40]
Here are a few high level thoughts on the current documentation:

Looking at the main example on the main page I'm curious if it is realistic:

```python
from dask_jobqueue import PBSCluster

cluster = PBSCluster(processes=6, threads=4, memory="16GB")
cluster.start_workers(10)

from dask.distributed import Client
client = Client(cluster)
```

Should we include project, queue, resource specs, and other keywords that might both be necessary for realistic use and also recognizable to users of that kind of system?  Similarly I think it would be very useful to include a few real-world examples in the example deployments documentation.  I suspect that this was the original intent of that page (nice idea!).   Perhaps we can socialize this on the pangeo issue tracker and ask people to submit PRs for their clusters?

### History

I recommend that we remove the history section from the main page

### Description of how it works

My experience trying to explain these projects to users of HPC systems is that most of them are familiar with job scripts.  I wonder if we might include a "How does this work?" section that shows the job script that we generate, and explain that we submit this several times.

Thoughts?

**Comment by mrocklin** [comment]
Socialized the examples documentation on https://github.com/pangeo-data/pangeo/issues/218

**Comment by lesteve** [comment]
All your suggestion makes sense, thanks for starting this!

**Comment by guillaumeeb** [comment]
I agree with all the suggestions.

The main example in the main page is realistic to me (I probably updated it according to my use :smiley:  ). We've got a default routing queue on my PBS cluster, project option is not mandatory, and I like automatically computed resource_specs (and once again I'm biased :grin: ).
But I fully agree that this is not the case for everyone! There is a more detailed example that we could put here in the PBSCluster docstrings:

```python
cluster = PBSCluster(queue='regular', project='DaskOnPBS',
                             local_directory=os.getenv('TMPDIR', '/tmp'),
                             threads=4, processes=6, memory='16GB',
                             resource_spec='select=1:ncpus=24:mem=100GB')
```

interface keyword is important too and should appear.

**Comment by jhamman** [comment]
I provided this on the dask documentation issue but I'll paste it here as well: 

```Python
cluster = PBSCluster(processes=18, threads=4, memory="6GB",
                     project='P48500028', queue='premium',
                     resource_spec='select=1:ncpus=36:mem=109G',
                     walltime='02:00:00', interface='ib0')
```

This is what I've been using on NCAR's HPC system Cheyenne.

**Comment by jhamman** [comment]
Looking at the most recent build of the docs, we could probably cleanup the docstrings a bit for the API docs:

![jobq](https://user-images.githubusercontent.com/2443309/39605305-b8f29574-4ee4-11e8-8d64-448d75050686.png)

I'd like to see us cleanup a few things:

- figure out how to drop the `__init__` method from the abstract job queue class
- fill in docstrings for job_script, scale_down, scale_up, and stop_workers methods

Some of the docstrings probably can go in the `distributed.deploy.cluster` (all except for `job_script`).

**Comment by jhamman** [comment]
Actually, everything could be done here and was fairly straightforward: https://github.com/dask/dask-jobqueue/commit/f7b14fe91ea0984f31dcd02301ce71a7477b3984

**Comment by guillaumeeb** [comment]
Closing this, as this has been adressed in #50 by @mrocklin and by @jhamman above.
