### ISSUE TITLE
community: scaling xskillscore

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-jobqueue#404]
Hi dask-jobqueue,

I previously worked on https://github.com/dask/dask-jobqueue/pull/78

I recently showed how a package I developed works with dask (https://github.com/raybellwaves/xskillscore-tutorial/blob/master/03_Big_Data.ipynb).

Unfortunately, I don't have access to a HPC anymore and can't demonstrate how it scales beyond my laptop.

If you are interested I setup a friendly competition in the issue tracker to see how large people can scale the dataset https://github.com/raybellwaves/xskillscore-tutorial/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

If you would like to partake you are welcome to run the example on an Cluster and you can even have a competition among the different schedulers :)

I'll close this in a week.

**Comment by lesteve** [comment]
Thanks for letting us know and thanks a lot for the `LSFCluster` implementation! I met some people that were using `LSFCluster` at the Dask workshop in Washington a few months ago.
