### ISSUE TITLE
Creating jobqueue scheduler-specific teams

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#410]
So I am the current bottleneck in Dask-Jobqueue, I am able to devote 4 hours per week max on this (when @guillaumeeb was the main person involved it was the same thing for him).

For some time I have been thinking that having a way to ping jobqueue scheduler-specific people easily could help because they can help debug cluster-specific things and help figure out whether this is a problem in `Dask-Jobqueue`, a jobqueue scheduler specific thing, a site local cluster-specific thing etc ... 

OK so here is my first attempt to make a list of volunteers by jobqueue scheduler let me know if I have missed some obvious candidates:
- SLURM @rcthomas @willirath @kathoef @jhamman (maybe more on Kubernetes these days in which case feel free to say no) @lesteve 
- LSF @d-v-b @stuarteberg (hopefully you haven't changed opinion since the Dask workshop a few months ago :wink:) 
- PBS @guillaumeeb actually is there anyone else there was a `MoabCluster` implementation that is supposed to be PBS-like but I have never heard back since probably that means it "just works" or it is rather useless ... 
- SGE @ericmjl @lesteve  
- HTCondor @mivade @matyasselmeci @riedel
- OAR @lesteve maybe I can find someone else in France, let's see, same thing I know some (~5-10) people are using it and I have never heard too much back ...

I guess the easiest if is you just reply quickly in this issue you are fine being added to such a list. Any other feed-back about the general idea more than welcome! 
Another thing

For more about how to get more people involved on Dask-on-HPC see https://github.com/dask/community/issues/43, don't hesitate to get involved there.

This goes without saying but this is opt-in only, and there the only very tiny moral contract is that from time to time (I would estimate less than once a week) I may ping you when I feel it is a jobqueue scheduler specific thing and if you have some spare bandwidth at this particular moment to help debug the problem that would be greatly appreciated!

**Comment by jakirkham** [comment]
cc @raybellwaves (who wrote the LSF implementation originally IIRC)

**Comment by willirath** [comment]
Sounds like a good way of structuring this. (Thanks for the constant work you've put into this @lesteve!)

**Comment by kathoef** [comment]
Sounds good to me, too!

**Comment by raybellwaves** [comment]
Gonna reach out to colleagues at UM to see if they interested in any feedback/dev etc. for LSF

**Comment by ericmjl** [comment]
Count me in, @lesteve. Definitely appreciate the help you’ve rendered thus far. May I also nominate @sntgluca to join me as well? (Please feel free to decline, Gianluca :smile:.)

**Comment by guillaumeeb** [comment]
Of course I'm in. I'm still hoping I can also find again up to half a day for dask and dask-jobqueue. Or else get someone here at CNES work on it. For PBS, you can also add @jhamman and @andersy005 and maybe @kmpaul !

**Comment by andersy005** [comment]
@lesteve / @guillaumeeb , I am happy to join as well.

**Comment by lesteve** [comment]
@ocaisa if you want to get involved in this, let me know!

I just saw your comment in https://github.com/dask/community/issues/43) and realise that I did not mention you here although you have made very useful contributions.

**Comment by sntgluca** [comment]
I really need to get better at following up with you guys...
Dear @ericmjl I am in.

**Comment by ocaisa** [comment]
> @ocaisa if you want to get involved in this, let me know!
> 
> I just saw your comment in [dask/community#43](https://github.com/dask/community/issues/43) and realise that I did not mention you here although you have made very useful contributions.

Yes, sure, I am happy to help out

**Comment by lesteve** [comment]
So I have created the teams:
- @dask/dask-jobqueue  is the parent team everybody should be in it and have Triage permissions to open/close issues add labels etc ... do feel free to use these rights as much as you see fit!
- each scheduler has a team e.g. @dask/dask-jobqueue-slurm.

Thanks everyone I am going to close this one 

I am still missing @sntgluca and @stuarteberg. Probably the Dask organization invitation  has been lost deep into one of your inbox. Apparently you should be able to see and accept the invitation here:
https://github.com/orgs/dask/invitation

**Comment by stuarteberg** [comment]
@lesteve I'm now a member of the dask org. Please add me to the LSF team!  Thanks.

**Comment by jakirkham** [comment]
Done :)

**Comment by lesteve** [comment]
Thanks everyone, I managed to get the few last persons remaining added. As part of the process I also learn that org invitation can go out of date which I did not know ...

**Comment by jakirkham** [comment]
> As part of the process I also learn that org invitation can go out of date which I did not know ...

Good to know. Do you know when they go out of date? 24hrs? Longer?

**Comment by stuarteberg** [comment]
>>org invitation can go out of date

>Do you know when they go out of date? 24hrs? Longer?

My invitation said 7 days.

**Comment by sntgluca** [comment]
It was more than one week, my bad... at the time I didn't have time to follow up.
Thank you for the new one!!

**Comment by kmpaul** [comment]
@andersy005 I didn't join, but please keep me in the loop on this.  If I have time to help, I'm happy to.

**Comment by andersy005** [comment]
> @andersy005 I didn't join, but please keep me in the loop on this. If I have time to help, I'm happy to.

Will do
