### ISSUE TITLE
Add `submit_command_extra` and `cancel_command_extra` to HTCondor

### ISSUE THREAD

**Issue by riedel** [dask/dask-jobqueue#411]
Primarily for HTCondor it might be important to pass extra parameters, such as schedd.

As for specifying the schedd, I think @lesteve's suggestion of `submit_command_extra` and `cancel_command_extra` is a good way of solving this problem; that way we don't have to argue over which arguments are "important".

_Originally posted by @matyasselmeci in https://github.com/dask/dask-jobqueue/pull/319#issuecomment-541160495_

This probably should be added across all schedulers: see also #202

**Comment by riedel** [comment]
What stops me from doing this is actually a meaningful test case.  In this case it would be enough to see if the command/cancel command is correctly assembled, right?

Actually I noted another thing, I want to put up for discussion: 
wouldn't it make sense to actually pass actual the cancel and submit commands in the constructor (with a default!)  as a format string with named parameters ( sth. like `"condor_submit {submit_command_extra} {submit_file}".format(**{**kw_args,**computed_args}` )

The background is that some schedulers might expose a SGE interface for compatibility reasons: e.g. `htcondor_qsub` that could be easily used. Also it is sometime easy to extend things using simple wrapper scripts. Also this might help if for some reasons the commands are not in the path.

For the named parameter formatting: The problem comes with akward positional parameters see #319 or rather #351.

**Comment by matyasselmeci** [comment]
I recommend against looking too closely at htcondor_qsub -- it hasn't been widely advertised, and doesn't get maintained much either.

If you wanted to test more than just whether `{submit_command_extra}` got properly interpolated, put something like `my.testattribute="foo"` into the submit_command_extra; this will add an extra attribute named `testattribute` with the value `foo` into the job which you can test for with something like `condor_q {job_id} -af testattribute`.

**Comment by riedel** [comment]
I think this is mostly closed. One should maybe add more tests (but this is sth that always can be done), but I think this does not justify keeping the issue open.
