### ISSUE TITLE
CI for SLURM using Docker

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#42]
This issue is derived from #2. The goal is to add some CI configuration for testing SLURM on a toy dockerized cluster. See work done in #23 and #27 for SGE.

Some useful comments:
https://github.com/dask/dask-jobqueue/issues/2#issue-301592217
https://github.com/dask/dask-jobqueue/issues/2#issuecomment-369761765
https://github.com/dask/dask-jobqueue/issues/2#issuecomment-376709540

**Comment by lesteve** [comment]
About @jhamman's comment https://github.com/dask/dask-jobqueue/issues/2#issuecomment-376709540

> Ran across this dockerized slurm cluster today: https://github.com/giovtorres/slurm-docker-cluster

For the record, I was able to create a SLURM cluster from this github repo (I needed just minor tweaks IIRC). I haven't looked at installing the dask-related dependencies that we will need to set up our CIs.

**Comment by guillaumeeb** [comment]
The link from @jhamman is working great!

Should we duplicate this work, or try to depend on it? 
The first would be brute force but probably more straight forward, as we could easily modify images to add our dependencies (e.g. Dask and python), and the compose to mount our project.
A cleaner way is to depend on it, or on the associated dockerhub image: https://hub.docker.com/r/giovtorres/docker-centos7-slurm/. 

I can try to work on that second point, we would just need a docker-compose file really close to the one in https://github.com/giovtorres/slurm-docker-cluster, a Dockerfile that depend on the one from the dockerhub and which add our dependencies.

**Comment by jhamman** [comment]
Following concepts in #52, I think using the centos image would be ideal.
