### ISSUE TITLE
Make HTCondor CI a bit closer to the other CI

### ISSUE THREAD

**Issue by riedel** [dask/dask-jobqueue#427]
In an ideal world, it would be great if HTCondor CI was a bit closer to the other CI, in particular:
- have a Dockerfile with the dependencies (`dask`, `distributed` etc ...) installed in the Dockerfile
- maybe follow `start-slurm.sh` etc ... convention but maybe this is overkill since HTCondor use a single Docker image rather than a `docker-compose` setup so I am a bit undecided on this last point.

_Originally posted by @lesteve in https://github.com/dask/dask-jobqueue/pull/420#issuecomment-624047047_

(following up on #247)

**Comment by riedel** [comment]
As this is not urgent I guess I would wait a bit for #424to be settled as the PR #425  introduced some changes.

IMHO modularization actually makes debugging a bit harder (at least for me), but on the other hand someone else might have difficulties if everything is handled differently.

Currently there is 3 different CI setups:
* (multiple) Dockerfile + additional scripts
* docker-compose + additional  scripts
* no Dockerfile and additional scripts

**Comment by riedel** [comment]
@matyasselmeci I was expecting the docker image for mini:el7 to change 2 days ago since mini:8.9.6-el7 was released (https://hub.docker.com/r/htcondor/mini/tags) . Is that a mistake or some logic behind this?

One possible thing to do would be pinning the versions (like #425) to not break the CI.  Although on the other hand it would be also very good to see if sth breaks in current version. Is there a chance for a stable tag (mini:8.8-el7 or mini:stable-el7 and maybe even mini:8.6-el7/mini:old-stable-el7 as those systems are out there in the wild ) be released as a good compromise? I guess I could build them easily but I like the "official" release.

**Comment by lesteve** [comment]
I would favor running with the latest version as the default and only pinning when there is nothing we can do about it (or we don't really want to investigate like the mysql one recently). We can revisit this approach if things start to break too often but I am trusting you fully on this one for not making the htcondor docker image break every 2 days.

Thanks @riedel by the way about the SLURM CI fix, I don't even want to imagine all the additional hours (or maybe days) and energy I would have spent on this without you!

**Comment by matyasselmeci** [comment]
@riedel good catch; unfortunately building these is currently a manual step so parts of it can get lost. I fixed it.

Some of our images depend on features that are only available in 8.9 (namely TOKEN auth), so we're not planning on making 8.8 images regularly. I can do a one-off htcondor/mini for 8.8.9. We will add stable series images, but only once we start the next stable series.

You can build 8.6.11 with a few tweaks to the Dockerfiles (apparently the 8.6 RPMs don't create the condor user/group), and htcondor/mini should be functional. However, 8.6 is no longer supported by the developers so we're not going to host any builds in the htcondor organization.


By the way, thanks so much for putting together the CI in the first place! We uploaded images for the central manager (htcondor/cm), submit node (htcondor/submit) and execute node (htcondor/execute) -- I'll document them soon -- so a three-node setup with docker-compose will be an option soon.

**Comment by riedel** [comment]
@matyasselmeci , great news! 

It would probably be great to have some minor level tags to follow ( having the tags "latest","8","8.9" all on the latest image like in the official docker images https://hub.docker.com/_/mysql: I today learned that in autobuilds this can be achieved with hooks)

I hopefully will make a docker_compose file for HTCondor soon, first with mini I guess just to make it more look like the others, but it actually then makes sense to do a full 3 node setup. Actually mini is really nice for speeding up the CI: it is currently the fastest setup! It is nice to see that you build everything on a common base image, I imaging that will also speed up the 3 node set-up!

**Comment by matyasselmeci** [comment]
We could probably do something like "8.9-el7" or "latest-el7". I hesitate to make just plain "latest" because, at least for the execute node image, the underlying distribution matters because it determines what jobs the user can run, and we don't want to break anything when we start making el8 images.

**Comment by riedel** [comment]
that would work perfectly, 8.9-el7 would be a perfect image to pull i guess for the CI, I probably would not want update with each single release. But no hassle, it works!
