### ISSUE TITLE
Pickle Failed to Deserialize on PBSCluster

### ISSUE THREAD

**Issue by Ovec8hkin** [dask/dask-jobqueue#436]
When running a script using dask on a PBS Cluster, the workers exit prematurely with the following logged error message (truncated):
```
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x05\x95c;\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8 ...
``` 
This does not happened when running the same script on SLURM or LSF styles clusters. 

What is the potential cause of this? I've checked that all the packages across the different systems are the same, and that the dask worker and scheduler are using the same package versions as well.

**Environment**:

- Dask version: 2.16.0
- Python version: 3.8.2
- Operating System: CentOS 7
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
Can you show what you were doing when this error happened, please?
Versions of other packages might be important too, such as cloudpickle. Are you certain that the versions are all the same? You could run `client.get_versions()` to check. 
Also, is your code perhaps referring to an object that is in a local module on your client? That might only be importable if each worker can see the same disk and has the same working directory set.

**Comment by Ovec8hkin** [comment]
The code is indeed attempting to import a local module that we have developed and that is not installed via pip or conda. Im not sure whether each workers can see the same disk or not.

Here is the output of client.get_versions(check=True):
```bash
>>> from dask.distributed import Client
>>> from dask_jobqueue import PBSCluster
>>> cl = PBSCluster()
>>> cl.scale(2)
>>> c = Client(cl)
>>> c.get_versions(check=True)

{'scheduler': {
     'host': {
          'python': '3.6.10.final.0',
          'python-bits': 64,
          'OS': 'Linux',
          'OS-release': '3.10.0-514.26.2.el7.x86_64', 
          'machine': 'x86_64', 'processor': 'x86_64', 
          'byteorder': 'little', 
          'LC_ALL': 'None', 
          'LANG': 'en_US.UTF-8'
     }, 
     'packages': {
          'dask': '2.13.0', 
          'distributed': '2.13.0', 
          'msgpack': '1.0.0', 
          'cloudpickle': '1.5.0dev0',
          'tornado': '6.0.4', 
          'toolz': '0.10.0', 
          'numpy': '1.18.4', 
          'lz4': None, 
          'blosc': None}}, 
     'workers': {
          'tcp://172.1.1.5:35662': {
               'host': {
                    'python': '3.6.10.final.0', 
                    'python-bits': 64, 
                    'OS': 'Linux', 
                    'OS-release': '3.10.0-514.26.2.el7.x86_64', 
                    'machine': 'x86_64', 
                    'processor': 'x86_64', 
                    'byteorder': 'little',
                     'LC_ALL': 'None', 
                    'LANG': 'en_US.UTF-8'
               }, 
               'packages': {
                    'dask': '2.13.0', 
                    'distributed': '2.13.0', 
                    'msgpack': '1.0.0', 
                    'cloudpickle': '1.5.0dev0', 
                    'tornado': '6.0.4', 
                    'toolz': '0.10.0', 
                    'numpy': '1.18.4', 
                    'lz4': None, 
                    'blosc': None
               }
          }, 
          'tcp://172.1.1.5:44521': {
               'host': {
                    'python': '3.6.10.final.0',
                    'python-bits': 64, 
                    'OS': 'Linux', 
                    'OS-release': '3.10.0-514.26.2.el7.x86_64', 
                    'machine': 'x86_64', 
                    'processor': 'x86_64', 
                    'byteorder': 'little', 
                    'LC_ALL': 'None', 
                    'LANG': 'en_US.UTF-8'
               }, 
               'packages': {
                    'dask': '2.13.0', 
                    'distributed': '2.13.0', 
                    'msgpack': '1.0.0', 
                    'cloudpickle': '1.5.0dev0', 
                    'tornado': '6.0.4', 
                    'toolz': '0.10.0', 
                    'numpy': '1.18.4', 
                    'lz4': None, 
                    'blosc': None
               }
          }
}, 
'client': {
          'host': {
               'python': '3.6.10.final.0', 
               'python-bits': 64, 
               'OS': 'Linux', 
               'OS-release': '3.10.0-514.26.2.el7.x86_64', 
               'machine': 'x86_64', 
               'processor': 'x86_64', 
               'byteorder': 'little', 
               'LC_ALL': 'None', 
               'LANG': 'en_US.UTF-8'
     }, 
     'packages': {
               'dask': '2.13.0', 
               'distributed': '2.13.0', 
               'msgpack': '1.0.0', 
               'cloudpickle': '1.5.0dev0', 
               'tornado': '6.0.4', 
               'toolz': '0.10.0',
                'numpy': '1.18.4', 
               'lz4': None, 
               'blosc': None
          }
     }
}
```

**Comment by martindurant** [comment]
To send an object to the workers which is defined in a class in a module, that module must be importable by the workers for unpickling - otherwise we would have to send the whole source of all of your installed python libraries! You may be able to send just the one source file with `client.upload_file`, but generally it's better to have your own way to distribute environments, whether by sharing discs, using [conda-pack](https://conda.github.io/conda-pack/), or something else.

**Comment by Ovec8hkin** [comment]
Ok. The cluster in question was setup and is administered by a single individual (I don't know why my PI wants to use this cluster specifically), so its probably a disk sharing issue related to how the cluster was configured. The fact that there is no $SCRATCH volume further supports this idea. I will ask my PI and the cluster admin if this is the case.
