### ISSUE TITLE
stop_workers() not working with SLURMCluster

### ISSUE THREAD

**Issue by sdtaylor** [dask/dask-jobqueue#44]
stop workers is not working for me on a SLURM cluster. Looking at the SLURM status I can still see the jobs running, and they are still available in the scheduler after running stop_workers, even after a few minutes.

```
In [1]: from dask_jobqueue import SLURMCluster

In [2]: cluster = SLURMCluster(processes=1, threads=1, memory='7GB', walltime='00:20:00')

In [3]: from dask.distributed import Client

In [4]: client  = Client(cluster)

In [5]: workers = cluster.start_workers(2)

In [6]: 

In [6]: cluster.stop_workers(workers)

In [7]: client.scheduler_info()['workers']
Out[7]: 
{'tcp://172.16.193.150:34830': {'name': 'dask-worker-3',
  'memory_limit': 7000000000,
  'host': '172.16.193.150',
  'resources': {},
  'ncores': 1,
  'services': {'nanny': 45411, 'bokeh': 8789},
  'local_directory': '/home/shawntaylor/projects/dask-jobqueue/dask-worker-space/worker-fcck4f5r',
  'pid': 31568,
  'cpu': 2.0,
  'memory': 67280896,
  'time': 1524318570.0637333,
  'read_bytes': 2777.9680047420147,
  'write_bytes': 2062.4913531609777,
  'num_fds': 22,
  'executing': 0,
  'in_memory': 0,
  'ready': 0,
  'in_flight': 0},
 'tcp://172.16.193.150:41714': {'name': 'dask-worker-2',
  'memory_limit': 7000000000,
  'host': '172.16.193.150',
  'resources': {},
  'ncores': 1,
  'services': {'nanny': 43241, 'bokeh': 42670},
  'local_directory': '/home/shawntaylor/projects/dask-jobqueue/dask-worker-space/worker-857lfd0u',
  'pid': 31570,
  'cpu': 0.0,
  'memory': 67092480,
  'time': 1524318569.739144,
  'read_bytes': 2542.885851061595,
  'write_bytes': 2066.345038028005,
  'num_fds': 22,
  'executing': 0,
  'in_memory': 0,
  'ready': 0,
  'in_flight': 0}}

In [8]: 
```

I'm pretty sure it's because `stop_workers` is calling `self.cancel_command` (set to `scancel` for SLURM) and expecting to use the slurm job id, which is saved here:

```
In [30]: cluster.jobs
Out[30]: {4: 'Submitted batch job 19566158', 5: 'Submitted batch job 19566159'}
```
and using the entire string with `scancel` instead of just the job id. This gets set here https://github.com/dask/dask-jobqueue/blob/74b3f45a7272e938c7b075f08c7de96fe6369caa/dask_jobqueue/core.py#L164

That's probably made for another schedulers job submission output format? I can fix this for SLURM but I don't know how I would generalize that to fit in the package. If someone can point me in the right direction I can give it a try though and submit a PR.

**Comment by jhamman** [comment]
Thanks for the report. We probably need a method on each cluster that handles decoding the job id from the submit call.

**Comment by guillaumeeb** [comment]
Yes we're not really generic here, it seems very PBS oriented :slightly_smiling_face: ...
Looking at the code, I think we could probably also improve error handling.

In the case of SLURM output, maybe we could use the following option with the sbatch command (see https://slurm.schedmd.com/sbatch.html):
```
--parsable
    Outputs only the job id number and the cluster name if present. The values are separated by a semicolon. Errors will still be displayed. 
```

Using `sbatch --parsable` as a submit_command might be enough if it works as expected. But it will probably also be cleaner to have some kind of method to implement in every JobQueueCluster child object as @jhamman mentioned. 

It would be great if you could work on a PR @sdtaylor!
