### ISSUE TITLE
Document steps to release dask-jobqueue

### ISSUE THREAD

**Issue by jhamman** [dask/dask-jobqueue#46]
I have just made the 0.1.1 release of dask-jobqueue. These are the steps I took: 

- checkout dask/dask-jobqueeue master, for me this was: `git checkout upstream/master`
- create a tag: `git tag -a 0.1.1 -m '0.1.1'`
- push the tag to github: `git push --tags upstream`
- build the wheels/dist for pypi: `python setup.py bdist_wheel sdist`
- upload the release to pypi: `twine upload dist/dask*0.1.1*`

@jakirkham has suggested wrapping these tasks into a `rever` workflow: https://github.com/dask/dask-jobqueue/issues/36#issuecomment-382606275. I'm open to going that route but it is not a high priority for me at the moment.

Perhaps someone else wants to step in there. There may be other steps we want in this workflow. I view this as the bare minimum. I think this issue is the place where we should discuss those.

**Comment by mrocklin** [comment]
For reference here is my approach with some other dask sub-projects:
https://github.com/dask/dask/blob/master/docs/release-procedure.md
