### ISSUE TITLE
Learnings from submitit

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-jobqueue#462]
Case across this on Twitter. May be some learnings

https://github.com/facebookincubator/submitit

**Comment by guillaumeeb** [comment]
Thanks @raybellwaves.

There's a dask-jobqueue comparison in there: https://github.com/facebookincubator/submitit#comparison-with-daskdistributed.

In the end, submitit looks like a Python wrapper to Slurm command, whereas Dask-jobqueue enables Dask usage on a lot of job queueing system, not the same goal I think.
