### ISSUE TITLE
New cluster type for IBM Spectrum Conductor

### ISSUE THREAD

**Issue by jennalc** [dask/dask-jobqueue#469]
I have been working on a new JobQueue cluster to integrate with IBM Spectrum Conductor.
https://www.ibm.com/ca-en/marketplace/spark-workload-management

Would love to contribute the cluster to this project.

**Comment by guillaumeeb** [comment]
Hi @jennalc,

I'm not sure if your link is providing a lot of information on your JobQueue cluster implementation. It mostly talks of Spark an other tooling.

Anyway, if you want to propose a JobQueueCluster implentation with a new Scheduler, feel free to open a PR for it!

I was under the impression that Spectrum Conductor was not exactly like LSF or other queuing system, but I may well be wrong.

**Comment by jennalc** [comment]
@guillaumeeb - It is not exactly like LSF, but based on similar scheduling technology, though with different interface than LSF.
I saw from the contributing guidelines that there are some test requirements for different schedulers as a docker image. I do not have such an image prepared for Conductor. Would you still accept a PR in this case?

**Comment by jennalc** [comment]
@guillaumeeb - PR has been submitted: https://github.com/dask/dask-jobqueue/pull/472

**Comment by guillaumeeb** [comment]
Closing this as discussed in the related PR.
