### ISSUE TITLE
Enable documentation autobuild (for PRs) on Readthedocs

### ISSUE THREAD

**Issue by andersy005** [dask/dask-jobqueue#483]
Now that Readthedocs provides automatic build of documentation for pull requests: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html, it would nice to enable this feature for this repo. 

Ccing @lesteve, @guillaumeeb who may have administrative access to the dask-jobqueue on Readthedocs.

**Comment by guillaumeeb** [comment]
I am far from a ReadTheDoc expert, I don't believe ever connecting to it, and this looks confirmed by the fact it did'nt know my email...

Maybe @mrocklin can help us here?

And I think @andersy005 you should have every rights on everything related to dask-jobqueue!

**Comment by lesteve** [comment]
I don't have the rights on readthedocs either.

According to https://readthedocs.org/projects/dask-jobqueue/ maintainers are @mrocklin @jhamman @TomAugspurger @jrbourbeau. If one of you could add me to the dask-jobqueue maintainers on ReadTheDocs that would be great!

Then I can add @guillaumeeb and @andersy005!

**Comment by TomAugspurger** [comment]
@lesteve I added you on readthedocs.

**Comment by lesteve** [comment]
Great thanks! I added @andersy005 @guillaumeeb and @willirath as maintainer on ReadTheDocs and enabled building the doc on PRs.

Closing this one, any issues let me know!
