### ISSUE TITLE
Cluster overview is showing cores = nthreads * workers, instead of actual cores

### ISSUE THREAD

**Issue by bgulowaty** [dask/dask-jobqueue#485]
**What happened**:
Cluster overview is showing misleading number of used cores. 

```python
cluster = SLURMCluster(
    queue='queue-name',
    project="project-name",
    cores=24,
    processes=1,
    memory="32GB",
    interface='bond0',
    walltime='4:00:00',
    extra=['--nthreads 2']
)
```

![2021-01-25_17:26:49](https://user-images.githubusercontent.com/2604929/105734194-aa97a300-5f32-11eb-8e08-eeeecda82ffc.png)

**What you expected to happen**:
When I set extra params of worker by passing `extra`, eg `extra=['--nthreads 2']`, number of cores is misleading, as it shows nthreads (used by workes) times workers, instead of actual reserved cores, which would be cores (as passed to eg. `SLURMCluster`) times jobs.

I guess such number came from assumption that 1 thread = 1 python job, but we could run multiprocessing within one python script (eg. via native ProcessPoolExecutor or joblib/loky). Therefore this should be changed as is somehow misleading when it comes to resource consumption of `HPC` (which might be charged)

```
dask==2021.1.0
dask-jobqueue==0.7.2
Python 3.8.5
Linux 3.10
pip
```

**Comment by guillaumeeb** [comment]
Hi @bgulowaty, thanks for posting here, and sorry for the delay.

I see what you'd want in your specific use case, but I think it is too edgy and wouldn't represent everyone's point of view.

`SlurmCluster` in an implementation of `SpecCluster` from dask.distributed, so it must also be consistent with other Clusters implementations. The widget you displayed just represent the Dask Cluster that is running, not necessarily the resources you've requested from your job queueing system (or K8S Cluster, or anything).

So from my point of view, this should not be changed. 

In a general rule, I would advise against running Python multiprocessing into dask workers in most cases, this can be tricky. But you may want to run other binaries that are multi threaded.

If you want a consistent view on your cluster, you can also try to use Dask [worker resources](https://distributed.dask.org/en/latest/resources.html). This way, you would be able to express multiprocessing jobs along with single core ones.

And finally, it is interesting to see that in your case you specify an extra args for reducing the worker threads, and not for giving additionnal resource to individual jobs through scheduler options. What I mean is that in your case I would have done something like:
```python
cluster = SLURMCluster(
    queue='queue-name',
    project="project-name",
    cores=2,
    processes=1,
    memory="32GB",
    interface='bond0',
    walltime='4:00:00',
    job_extra=['--ncpu=24'] #Or whatever Slurm option is
)
```
