### ISSUE TITLE
Indefinite wait time with SLURMCluster and client.submit(..., resources={'MEMORY': int(1024**3)}) 

### ISSUE THREAD

**Issue by WillemMarais** [dask/dask-jobqueue#489]
When I execute the following code the last `client.submit` blocks indefinitely:
```
import os
import sys
import dask
from dask.distributed import Client
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(
    cores=1, 
    memory='5GB',
    processes=1,
    interface="ib0",
    walltime="00:20:00",
    python='/home/willemm/miniconda3/bin/python',
    dashboard_address=':9995'
)

client = Client(cluster)
display(client)

cluster.adapt(minimum=0, maximum=10)
display(client)

def inc(x):
    return x + 1

def double(x):
    return x * 2

def add(x, y):
    return x + y

data = [1]

output = []
for x in data:
    a = client.submit(inc, x)
    b = client.submit(double, x)
    c = client.submit(add, a, b)
    output.append(c)
total = client.submit(sum, output, resources={'MEMORY': int(1024**3)})

print(total.result())
```
When I replace `resources={'MEMORY': int(1024**3)}` with `resources={}` the code behave as expected and `total.result()` returns the number 4. Based on the [`SLURM Deployment` example](https://jobqueue.dask.org/en/latest/examples.html#slurm-deployment-providing-additional-arguments-to-the-dask-workers) I am under the impression that the above code should work, or maybe I missed something in the documentation? 

**Environment**:

- Dask version: '2021.02.0'
- dask_jobqueue version: 0.7
- Python version: 3.7.9
- Operating System: CentOS Linux 8 (Core)
- Slurm: slurm 20.02.0-0rc1
- Install method (conda, pip, source): conda-forge

**Comment by andersy005** [comment]
> When I execute the following code the last client.submit blocks indefinitely:

@WillemMarais, If I understand your code snippet correctly, you want your tasks to run on workers that meet certain constraints. Your issue has to do with the fact you are using resource constraints: `resources={'MEMORY': int(1024**3)}` in `client.submit()` and you haven't defined this in the `SLURMCluster`. As a result, from dask scheduler's perspective, there's no worker in your cluster that meets the the constraints you specified in `client.submit()`.


The following should address your issue:


```python
cluster = SLURMCluster(
    cores=1, 
    memory='5GB',
    processes=1,
    interface="ib0",
    walltime="00:20:00",
    python='/home/willemm/miniconda3/bin/python',
    dashboard_address=':9995',
    extra=[f'--resources MEMORY={int(1024**3)}']
)
```


See [worker resources docs](https://distributed.dask.org/en/latest/resources.html) for details on defining resources.

**Comment by lesteve** [comment]
@andersy005's answer seems right to me, I am going to close this one. @WillemMarais feel free to comment if that does not fix your original problem.
