### ISSUE TITLE
Learning from ipyparallel

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-jobqueue#49]
[ipyparallel]( https://github.com/ipython/ipyparallel ) (formerly part of the Jupyter Notebook) provides similar functionality to dask distributed and dask-jobqueue in that it allows users to startup a cluster and submit work to it. The model of the ipyparallel is a bit different from that of dask distributed, but that doesn't really concern us here.

What is interesting is ipyparallel has a trove of knowledge regarding starting jobs on various common HPC Schedulers. This knowledge is [largely baked into one file]( https://github.com/ipython/ipyparallel/blob/6.1.1/ipyparallel/apps/launcher.py ). For HPC Schedulers already in dask-jobqueue, it's worth comparing notes to ipyparallel and see what can be learned on this front. As to the schedulers not present in dask-jobqueue, it's worth taking a look at ipyparallel's implementations and seeing what can be gleaned from it and how it might be used here. It's probably also worth learning how things have been refactored out in ipyparallel to see if there are any useful strategies for modeling HPC Schedulers generally.

**Comment by mrocklin** [comment]
It's a good point.

Also, just for fun, but ipyparallel is also a reasonable way to deploy dask
itself:
http://ipyparallel.readthedocs.io/en/latest/api/ipyparallel.html#ipyparallel.Client.become_dask

**Comment by jhamman** [comment]
Thanks for sharing. I had a quick skim. There are some remarkable similarities between the two projects, particularly on the level of abstraction between different scheduling systems. May be worth using this as a starting point when developing the LSF cluster (#4).

**Comment by guillaumeeb** [comment]
Wow, big source file! Scary at first, but a lot of information in there, probably worth taking a second look.

Thanks for sharing.

**Comment by guillaumeeb** [comment]
Closing this for now, we may want to look at it again for some other scheduler implementation, was useful for LSF. We may also want to look at this for #133, along with https://github.com/jupyterhub/batchspawner.
