### ISSUE TITLE
Add possibility of overriding the scheduler address the workers see?

### ISSUE THREAD

**Issue by davidmonro** [dask/dask-jobqueue#490]
Hi,

we are trying to do something slightly odd; we want to have the notebook and scheduler run on a node inside our openstack cluster, and the workers run on the our PBS cluster, which is not inside openstack.

The openstack nodes do have floating public IPs assigned, but that IP address is not visible on any of the interfaces of the node (there's effectively a reverse NAT going on between the workers and the scheduler).

From looking at the code which generates the job script, it just inserts self.scheduler into the string, which should return the address. However, I can't tell the scheduler to listen on the public address, because it isn't bound to any interfaces on the node. In addition, passing the scheduler object to the client wouldn't work at that point, because you can't reach that public IP address from within the node itself!

Would it be possible to have an option added to override the address generated in the jobscript?

Cheers

David

**Comment by davidmonro** [comment]
Oh, and just to complicate things slightly, we'd want to maintain the port number chosen by the scheduler, and just override the actual IP.

**Comment by guillaumeeb** [comment]
Hi @davidmonro,

Sorry for the delay...

I'm not sure I understand your issue. From what I get, you're trying to do something impossible.
If the Scheduler cannot bind to an IP on the Openstack node to be visible from the workers, Dask can't work.

Maybe you want to launch the Scheduler on the PBS cluster too? The IP from the PBS cluster can be reached from the notebook inside Openstack?

What IP are you trying to assign to the Scheduler?

Hm I think I get it, you know an IP where the Scheduler can be reached inside the Openstack node, but the Scheduler or dask-jobqueue cannot know it.

Have you tried replacing your FooclusterObject.scheduler.address? Not sure it would work...

Anyway, maybe you've looked a little more into it by now? Any PR to try to solve this would be welcome, or maybe digging into https://github.com/dask/dask-jobqueue/issues/419 would help.

**Comment by davidmonro** [comment]
Hi,

the workers can connect to the node running the notebook and scheduler, but using a different IP address than the one visible inside the node.

(At least on our implementation, inside an openstack project all the nodes get allocated an internal IP; you can allocate external "floating" IPs to them as well, which things outside openstack can connect to, but on the inside, you see the traffic as being rewritten to your internal IP. The external IP doesn't appear on any interface inside the node).

If I override the scheduler address on the cluster object then that breaks the client side (which needs to use the internal IP).

I just want an option which overrides the address which gets generated in the job script, rather than having it always pull it from the cluster object. Ideally it would preserve the port number from the cluster object (but I suppose there might be other scenarios where it might be useful to override that as well, so maybe 2 options).

Launching the scheduler on PBS might be a workaround, but I don't think there's currently a way of doing that from within dask-jobqueue? And I suspect there might be issues with walltime limits killing the scheduler job?

Cheers

David

Cheers

David

**Comment by lesteve** [comment]
I am not quite sure this covers your use case but maybe you can try `PBSCluster(..., scheduler_options({'host': 'your-host-ip-here'})` ...

**Comment by guillaumeeb** [comment]
> If I override the scheduler address on the cluster object then that breaks the client side (which needs to use the internal IP).

Yes, you're right... Complicated situation.

> I just want an option which overrides the address which gets generated in the job script, rather than having it always pull it from the cluster object

If the solution proposed by @lesteve doesn't work, one option would be to override the Job classes of your scheduler to give your own scheduler address. https://github.com/dask/dask-jobqueue/blob/main/dask_jobqueue/core.py#L86. 
https://github.com/dask/dask-jobqueue/blob/main/dask_jobqueue/pbs.py#L37

Else, propose some PR to add an argument to the PBS job class, but maybe you should first try to see if you can do it an maintain a fork for your specific setup.

> Launching the scheduler on PBS might be a workaround, but I don't think there's currently a way of doing that from within dask-jobqueue? And I suspect there might be issues with walltime limits killing the scheduler job?
No and yes!

**Comment by davidmonro** [comment]
Sorry it took me a couple of days to get back to you. @lesteve solution doesn't work because it causes the scheduler to try and bind to the address I give it, which isn't possible since that IP doesn't appear on any interface belonging to the node (I get an exception OSError: [Errno 99] Cannot assign requested address which is exactly what I would expect).

I'll look at adding an argument to the class. I agree it is a somewhat unusual setup.

**Comment by guillaumeeb** [comment]
This has been solved thanks to @etejedor here https://github.com/dask/dask-jobqueue/issues/548!
