### ISSUE TITLE
Provide a maximum number of simultaneous workers for SLURMCluster

### ISSUE THREAD

**Issue by Rodot-** [dask/dask-jobqueue#491]
When using SLURMCluster and using adaptive deployments, there's no way currently to tell the scheduler to restrict the number of simultaneous workers.  This is an issue since some accounts submitting to SLURM may be limited in the total number of simultaneous jobs that may be submitted to the job queue.

**Comment by jrbourbeau** [comment]
Thanks @Rodot- -- I'm transferring this issue over to dask-jobqueue as it seems specific to that project

**Comment by andersy005** [comment]
@Rodot-, 

>  there's no way currently to tell the scheduler to restrict the number of simultaneous workers. This is an issue since some accounts submitting to SLURM may be limited in the total number of simultaneous jobs that may be submitted to the job queue


Let's assume that your system has a limit of 36 concurrent running jobs per user, wouldn't the following achieve what you are looking for?

```python
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(processes=1, cores=1, ...)
cluster.adapt(minimum_jobs=1, maximum_jobs=36)
```

**Comment by Rodot-** [comment]
@andersy005 

The problem is that I might need more *total* jobs than that.

I'll give the example for my case.  I have 100,000 functions I would like to evaluate over a grid of parameters.  Each function takes 12 minutes to evaluate and runs on a single core.  Say each node in my cluster has 20 cores and a maximum of 50 jobs at a time in the queue.  So I make a collection of workers with 20 cores each that run for say, 2 hours each.  When I use

    `cluster.adapt(minimum_jobs=1, maximum_jobs=50)`
    
If I'm understanding this correctly, it will evaluate the requirements of the first job, and determine I need 50 workers, since that's the max I specified.  But I would need 500 workers to ensure that I eventually complete every job.  After running through the 50 workers it would stop spawning new ones even though I have waiting tasks to complete.

This is me operating under the assumption that the kwargs `minimum_jobs` and `maximum_jobs` are the same as `minium` and `maximum` respectively.  I can't seem to find anything in the documentation about those kwargs specifically, so perhaps I could be mistaken.

**Comment by Rodot-** [comment]
Ah, I see, I found it looking through the source code: https://github.com/dask/dask-jobqueue/blob/main/dask_jobqueue/core.py

Thanks for the help!

**Comment by Rodot-** [comment]
Sorry, it looks like my issue is not resolved, I'll provide a code example to demonstrate what I mean.  I misunderstood the difference between `minimum`/`maximum` and `minimum_jobs`/`maximum_jobs`, the issue is the same.

```python
def test_func(index):
    import time
    time.sleep(10)
    return index

cluster = SLURMCluster(walltime='00:00:30', memory='4gb', cores=2, processes=2, local_directory='/tmp')
cluster.adapt(minimum_jobs=1, maximum_jobs=50)
cluster.scheduler.allowed_failures = 1000
client = Client(cluster)
futures = client.map(test_func, range(100_000))
for future in as_completed(futures):
    print(future.result())
```

This code will not complete all 100000 function calls.  The workers will reach their lifetime then die, and adapt will not respawn them.  I've tried playing around with `cluster.scheduler.allowed_failures`, I've tried using the `--lifetime`, `--lifetime-stagger`, and `--lifetime-restart` extra args (with appropriate parameters), I've tried setting the `target_duration` with adapt.  In every case, once the worker walltime expires, no more workers are ever spawned.  Then the program just waits for workers to become available that never spawn.  The dashboard also then stops updating, showing there are still workers even though `squeue` shows there are none.

Here's the contents of the last out file:

```
distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.8.47:36173'
distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.8.47:42675'
distributed.worker - INFO -       Start worker at:   tcp://192.168.8.47:37132
distributed.worker - INFO -          Listening to:   tcp://192.168.8.47:37132
distributed.worker - INFO -       Start worker at:   tcp://192.168.8.47:41502
distributed.worker - INFO -          dashboard at:         192.168.8.47:43823
distributed.worker - INFO -          Listening to:   tcp://192.168.8.47:41502
distributed.worker - INFO - Waiting to connect to:  tcp://192.168.9.200:38619
distributed.worker - INFO -          dashboard at:         192.168.8.47:34843
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:  tcp://192.168.9.200:38619
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-wv8e7lcv
distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-3y24varv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:  tcp://192.168.9.200:38619
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:  tcp://192.168.9.200:38619
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
slurmstepd: error: *** JOB 17006352 ON lac-247 CANCELLED AT 2021-03-10T13:08:21 DUE TO TIME LIMIT ***
```

**Comment by guillaumeeb** [comment]
You might find this part of the doc relevant too:

https://jobqueue.dask.org/en/latest/advanced-tips-and-tricks.html#how-to-handle-job-queueing-system-walltime-killing-workers
