### ISSUE TITLE
Allow for arbitrary path to configuration files

### ISSUE THREAD

**Issue by AlecThomson** [dask/dask-jobqueue#499]
Hi there!

Currently, the `jobqueue.yaml` file must be placed in `~/.config/dask/` or in the directory specified by `DASK_ROOT_CONFIG` environment variable. It'd be great if a config file could be passed in via a kwarg in the cluster definition, e.g.
```python
cluster = SLURMCluster(
    config_file='/path/to/config/jobqueue.yaml'
)
```

As an example use case, I'm building a pipeline which I'd like to make as portable as possible. I think it'd be easier to package a default `jobqueue.yaml` which users could tweak for their system, rather than editing the definition inside a script. Allowing this config filepath definition would allow the code to remain relatively static. It also reduces the need for users to copy a config file somewhere else, or define an environment variable.

Cheers!

**Comment by jacobtomlinson** [comment]
This is a pretty big departure from how we generally do config across Dask today. Adding arguments like this would kinda invalidate the [documentation for the Dask config system](https://docs.dask.org/en/latest/configuration.html). The Dask config is loaded from many places across the system and merged together into a single source which can be queried using a dot notation. 

Perhaps for your use case you may want to consider implementing a custom config loader.

```
import yaml

with open("yourconfig.yaml", 'r') as f:
    config = yaml.safe_load(f)

cluster = SLURMCluster(
    **config
)
```

**Comment by AlecThomson** [comment]
That looks like that'll do exactly what I need. Thanks!

**Comment by jacobtomlinson** [comment]
@AlecThomson you might also be interested in [dask-ctl](https://dask-ctl.readthedocs.io) which is an incubator project where I am trying to solve some of the problems around creating, managing and deleting Dask clusters.

Specifically, the [section on cluster specs](https://dask-ctl.readthedocs.io/en/latest/spec.html) where you can define a cluster entirely in a YAML file and then create it in Python or from the command line.

It's early days for dask-ctl but I think this could be a good use for it.

```yaml
# yourconfig.yaml
version: 1
module: "dask_jobqueue"
class: "SLURMCluster"
args: []
kwargs:
  n_workers: 2
  threads_per_worker: 1
  memory_limit: '1GB'
  # etc
```

```python
from dask_ctl import create_cluster

cluster = create_cluster("yourconfig.yaml")
```
