### ISSUE TITLE
dask_jobqueue SLURMCluster: job_extra does not include option in SBATCH

### ISSUE THREAD

**Issue by areichmuth** [dask/dask-jobqueue#508]
**What happened**:
I try to get dask running with jobscheduler on a SLURM HPC. Our HPC does not take `--mem` but instead `--mem-per-cpu`. For this I called following dask_jobscheduler:
```
cluster = SLURMCluster(header_skip=['--mem'], job_extra=['--mem-per-cpu=8G'], memory = "1 GB", queue='compute', project="myproj", cores=6)
```

**What you expected to happen**:
The `header_skip` did correctly remove the memory from my sbatch call. Unfortunately the `--mem-per-cpu` is not correctly included.

**Minimal Complete Verifiable Example**:
This is the output if run through `cluster.job_script()`:
```
#SBATCH -J dask-worker
#SBATCH -p compute
#SBATCH -A myproj
#SBATCH -n 1
#SBATCH --cpus-per-task=6
#SBATCH -t 00:30:00
```
I'm using 
dask==2021.6.2
dask-jobqueue==0.7.2

**Comment by areichmuth** [comment]
Found the error but it might be a bug.
If I do not use the `header_skip` and leave memory untouched it correctly includes `--mem-per-cpu`. This results in the following:
```
#SBATCH -J dask-worker
#SBATCH -p testing
#SBATCH -A myproj
#SBATCH -n 1
#SBATCH --cpus-per-task=6
#SBATCH --mem=954M
#SBATCH -t 00:30:00
#SBATCH --mem-per-cpu=8G
```
Our HPC can not resolve this as two different memory options are included. How can I exclude the default memory statement and give this demanded `--mem-per-cpu` option?

Thanks
Anne

**Comment by guillaumeeb** [comment]
Hi @areichmuth, sorry for the delay.

I think the problem comes from how the `header_skip` kwarg is used:
https://github.com/dask/dask-jobqueue/blob/main/dask_jobqueue/core.py#L286

It removes every line from the header containing your text.

Maybe you should try with `header_skip=['--mem=']`?

**Comment by guillaumeeb** [comment]
I'm also closing as duplicated of https://github.com/dask/dask-jobqueue/issues/461. We'll see in the other thread if we need to fix it or not. 

@areichmuth if you could still report back if my suggestion above is a correct workaround for your problem it would be nice.

**Comment by areichmuth** [comment]
@guillaumeeb thank you for this hint. It is giving the correct options. Could you maybe please update this site as I got it from there. https://jobqueue.dask.org/en/latest/advanced-tips-and-tricks.html
This helps maybe many unexperienced user as me.

**Comment by guillaumeeb** [comment]
@areichmuth would you be interested on proposing this documentation update?
