### ISSUE TITLE
Python entry is missing in config file

### ISSUE THREAD

**Issue by PhML** [dask/dask-jobqueue#517]
I don’t know if it is on purpose or not but `python` argument can’t be set from config file (if not provided at cluster initialization, it is set to `sys.executable`).

My use case is that I run dask in a singularity container on a PBS cluster so it can’t rely on `sys.executable`.

**Comment by guillaumeeb** [comment]
Hi @PhML, thanks for the issue.

I don't think it is on purpose, it's true that it's one of the few (the only one? Didn't really check) argument that is not available in config file. 

I'm not sure how it impacts your use case, but any PR making it easier to run dask-jobqueue in Singularity container would be welcomed! Are you interested in proposing something? 

At least, could you described more precisely your use case and the problem encountered?

**Comment by guillaumeeb** [comment]
@PhML, do you have more input on this? Can't you use the `python` kwarg when building your `Cluster` object?

Wihtout any news from you in the following weeks, I'm going to close this issue as stale, but any PR proposing to solve you issue will be welcomed.

**Comment by guillaumeeb** [comment]
Closing this issue as stale for now.
