### ISSUE TITLE
Add pytest xfails for known issue in CI

### ISSUE THREAD

**Issue by riedel** [dask/dask-jobqueue#534]
E.g. #520 could be easily tested even before a fix is merged.

**Comment by riedel** [comment]
Please comment on this if this is desirable. I added some code in #533 that also can be used to xfail only for a single Cluster type if iterating over multiple as a proposal: https://github.com/dask/dask-jobqueue/blob/827a687cb47380c49599302338b22cf68d8b4d1d/dask_jobqueue/tests/test_jobqueue_core.py#L353

**Comment by guillaumeeb** [comment]
I find it useful, especially with #533!
