### ISSUE TITLE
HTCondor and slurm CIs have no shared filesystem

### ISSUE THREAD

**Issue by riedel** [dask/dask-jobqueue#535]
This why one cannot e.g. test security contexts. This actually could be even desirable as jobqueue probably does not even need one. However, in this case the security context code needs to be rewritten (found nothing else depending on this). 

This is a bit paradox due to this line:
https://github.com/dask/dask-jobqueue/blob/8264b8cd6fa028f35665a554c5fea4be34a97781/dask_jobqueue/htcondor.py#L236

**Comment by riedel** [comment]
See the effect of this e.g. in https://github.com/dask/dask-jobqueue/pull/532/checks

**Comment by guillaumeeb** [comment]
> This actually could be even desirable as jobqueue probably does not even need one

I totally agree with that sentence. 

> However, in this case the security context code needs to be rewritten

I think we can just specify that it will work only with a shared file system.

> This is a bit paradox due to this line

We should remove the line if not true. Maybe it was at first?

**Comment by riedel** [comment]
> I think we can just specify that it will work only with a shared file system.

Does it make sense to actually specify a directory for shared files and make $HOME the default.  If one knows that a file is outside a shared filesystem there is probably a way to transfer those files for all schedulers (`sbcast` for slurm or `transfer_input_files=` for htcondor). I wonder if there are more use cases than the security context 

(If you wonder by now, why all the fuzz: I really want to be able to support temporary security context to actually comply by default with our internal security policies when handling sensitive data. I did not think that this is so complicated)

**Comment by guillaumeeb** [comment]
> Does it make sense to actually specify a directory for shared files and make $HOME the default

I think so,if this can be overrided easily. 

I'm just wondering if this should be $HOME or the current working directory (on HPC system, you generally launch script from a shared file system).
