### ISSUE TITLE
Push python ci dependency to python=3.7

### ISSUE THREAD

**Issue by riedel** [dask/dask-jobqueue#541]
as dask dropped support for 3.6 in dask/dask#7006

https://github.com/dask/dask-jobqueue/blob/4980e746e9be15e5fe6736b6c496b8faea737fd7/ci/environment.yml#L6

actually fixing #539 could help making all CI compatible as well 

The actual problem is that one might acutally pull in a newer click dependency which triggers this bug dask/dask#7658 which is only fixed in newer dask versions

**Comment by guillaumeeb** [comment]
👍 for dropping Python 3.6.

**Comment by lesteve** [comment]
FYI I started #545 but there seems to be CI genuine errors ...
