### ISSUE TITLE
CI errors after dropping Python 3.6

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#547]
- worker memory limit is slightly different than requested https://github.com/dask/dask-jobqueue/runs/5314879710?check_suite_focus=true#step:8:323. It does not seem related to a MB vs MiB thing since it is not the right factor
- Weird errors e.g https://github.com/dask/dask-jobqueue/runs/5314879645?check_suite_focus=true#step:8:630, maybe just a timeout thing. Note do not happen in SLURM but in SGE and PBS (not sure about HTCondor for now)
- HTCondor install fails with "dask-jobqueue requires Python '>=3.7' but the running Python is 3.6.8" and somehow it manifests itself as a timeout in our CI https://github.com/dask/dask-jobqueue/runs/5314879601?check_suite_focus=true (rather than an error at install time ...)

**Comment by riedel** [comment]
One problem with HTCondor could be that actually no images are prebuild (#540), so updating things in the CI can be of limited impact. Further I will need to actually pull in the dependencies specified (#539).  

Hopefully after a week of vacation and a stressful next week I can work on getting the HTCondor build working. Thanks for actually taking the step to update python. 

Fun fact: actually after finally getting our HTCondor installation to run really smoothly with dask, we decided to switch off the HTCondor cluster I am worked on and move to a slurm cluster. But don't worry I somehow started to like HTCondor in a weird way, after working with it for 8 years, and we are still running it in a few places, so I will try to keep maintaining this part.

**Comment by riedel** [comment]
@guillaumeeb: this was fixed within #562, right (great effort btw, thanks!), with last bits tracked as #568?

**Comment by guillaumeeb** [comment]
You're right, thanks for following :slightly_smiling_face:
