### ISSUE TITLE
Latest click broke dask-jobqueue

### ISSUE THREAD

**Issue by rsignell-usgs** [dask/dask-jobqueue#549]
did `mamba install click=8.0.4` to get it working again.

**Comment by andersy005** [comment]
i believe the issue was actually coming from `distributed` and it appears to have been fixed https://github.com/dask/distributed/issues/6013 and https://github.com/dask/distributed/pull/6018

**Comment by andersy005** [comment]
have tried upgrade `distributed` to the latest version `2022.04.0`?

**Comment by rsignell-usgs** [comment]
No, because I rely on conda-forge!
https://anaconda.org/conda-forge/distributed

**Comment by jakirkham** [comment]
Then you are in luck as we just merged an update ( https://github.com/conda-forge/distributed-feedstock/pull/202 ). Will take a bit to mirror to CDN

**Comment by jakirkham** [comment]
(should add it is also on CDN now 🙂)
