### ISSUE TITLE
Completely Silence Slurm logs

### ISSUE THREAD

**Issue by jwiemer112** [dask/dask-jobqueue#550]
Hello there,

I use `dask_jobqueue.SLURMClusteris` to simulate year-simulations. I always get a shitlaod of  logs in the slurm_logs folder.
Is there a handy way to completely silence these logs?

The parameter `silence_logs` is default on `error` in `JobQueueCluster(SpecCluster)`.

Greetz 
Jan

**Comment by guillaumeeb** [comment]
Hi @jwiemer112,

If you're talking about the logs of the worker emitted through Python `logging` module, you should look at https://docs.dask.org/en/latest/how-to/debug.html#logs. 

`silence_logs` parameter is only affecting the Scheduler started into your Python process building the `SlurmCluster` object.

Hope this helps!

**Comment by jwiemer112** [comment]
Thanks for your response. In my `jobqueue.yaml` is no logging section. But I will play around with logging a bit and try to figure it out. :)

**Comment by guillaumeeb** [comment]
Actually, as long as you're putting Yaml files in ~/.config/dask/, the name doesn't matter. You can put one `jobqueue.yaml`, and one `distributed.yaml` file, or everything in the first one. And in these config files, you put whatever Dask configuration you want to put.

See https://docs.dask.org/en/latest/configuration.html#yaml-files.

**Comment by jwiemer112** [comment]
Thanks for your help and all the information.
