### ISSUE TITLE
io_loop error when running Dask Actors on SGECluster

### ISSUE THREAD

**Issue by mronda** [dask/dask-jobqueue#552]
**What happened**:
Getting an error when trying to submit an Actor to a client started with an `SGECluster` cluster. 

Using example code found [here](https://distributed.dask.org/en/stable/actors.html#:~:text=Actors%20enable%20stateful%20computations%20within,methods%20on%20that%20remote%20object.). Works fine with a `LocalCluster` . I get an `io_loop` error when running with an `SGECluster`. 

Error:
```python
AttributeError: type object 'Counter' has no attribute '_io_loop'
```

**What you expected to happen**:
I expect the Dask Actor to work on an SGECluster

**Minimal Complete Verifiable Example**:

Example:

```python
class Counter:
    """ A simple class to manage an incrementing counter """
    n = 0

    def __init__(self):
        self.n = 0

    def increment(self):
        self.n += 1
        return self.n

    def add(self, x):
        self.n += x
        return self.n

future = client.submit(Counter, actor=True)  # Create a Counter on a worker
counter = future.result()

counter.add(1)
```

Error:

```python
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 counter.add(1)

File /hpc/apps/bifrost/test/x86_64/envs/bifrost.66/lib/python3.8/site-packages/distributed/actor.py:214, in Actor.__getattr__.<locals>.func(*args, **kwargs)
    211         return _OK(result["result"])
    212     return _Error(result["exception"])
--> 214 actor_future = ActorFuture(io_loop=self._io_loop)
    216 async def wait_then_set_result():
    217     actor_future._set_result(await run_actor_function_on_worker())

File /hpc/apps/bifrost/test/x86_64/envs/bifrost.66/lib/python3.8/site-packages/distributed/actor.py:190, in Actor.__getattr__(self, key)
    187     else:
    188         return attr
--> 190 attr = getattr(self._cls, key)
    192 if callable(attr):
    194     @functools.wraps(attr)
    195     def func(*args, **kwargs):

AttributeError: type object 'Counter' has no attribute '_io_loop'
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.5.0
- Dask-jobqueue: 0.7.3
- Python version: 3.8.13
- Operating System: CentOs
- Install method (conda, pip, source): conda

**Comment by jacobtomlinson** [comment]
@graingert @fjetter could this be related to the upstream ioloop work in distributed?

**Comment by graingert** [comment]
the issue is the `_io_loop` `@property` is raising an `AttributeError` causing attribute lookup to fallback to `Actor.__getattr__`

https://github.com/dask/distributed/blob/5feb17151cdf660a3443abf8596444a9f51dc575/distributed/actor.py#L122-L128

**Comment by graingert** [comment]
@jacobtomlinson can you find out what the `counter._worker`, `counter._client`, `counter._worker.io_loop`, `counter._client.io_loop` both on the client side and the worker side?

**Comment by jacobtomlinson** [comment]
@graingert thanks for responding here. I think some of your sentence got cut off in your last comment and I'm not sure what you're asking.

**Comment by graingert** [comment]
@jacobtomlinson fixed

**Comment by mronda** [comment]
Hi @jacobtomlinson @graingert , I checked for those attributes on `counter` and they do not get set:

```python

counter.__dict__

{'key': 'Counter-70d13dd5-903b-46c6-8da0-b9dc95a7593c',
 '_cls': __main__.Counter,
 '_address': '...',
 '_future': None,
 '_worker': None,
 '_client': None
}
```

Checking on client side, `client.io_loop` is set to `zmq.eventloop.ioloop.ZMQIOLoop`.

Let me know where else I can check

**Comment by graingert** [comment]
I think https://github.com/dask/distributed/blob/5feb17151cdf660a3443abf8596444a9f51dc575/distributed/actor.py#L108 is getting hit here?

**Comment by mronda** [comment]
Looks like it ! `LocalCluster` also sets `worker` attributes to `None`

**Comment by mronda** [comment]
@graingert , interesting, `get_client()` does not work when I stand up an `SGECluster`, but it does for `LocalCluster` . Do I need to run this within a context manager?

**Comment by graingert** [comment]
What happens if you run the example from

https://distributed.dask.org/en/stable/api.html#distributed.get_worker

```python
def f():
    return get_worker().address

print(client.submit(f).result())
```

**Comment by mronda** [comment]
@graingert I get this :

`TypeError: Data serialized with error but only able to deserialize data with ['pickle', 'dask']`

**Comment by mronda** [comment]
Forget the message above. I do get an address back

**Comment by mronda** [comment]
@graingert  I think I fixed it! I had set `set_as_default=False` when starting my Client. I set that to True and now it does set `Actor._client.io_loop` . Thanks for the help ! You pointed me to some code that allowed me to debug that further
