### ISSUE TITLE
Last release is July 2021.   Would be great to get a new one!

### ISSUE THREAD

**Issue by rsignell-usgs** [dask/dask-jobqueue#555]
I tried to use the `shared_temp_directory` argument in `SLURMCluster` and was surprised when it didn't work. 
I then realized that the version I installed with conda-forge is from July 2021!  

Would be great to get a new release!

**Comment by rsignell-usgs** [comment]
@jacobtomlinson ?

**Comment by guillaumeeb** [comment]
Hi @rsignell-usgs, to be honest, as we did not do much thing in dask-jobqueue the past year, I wasn't thinking there was a need for a new release. But you just cited at least one feature not in a official release.

So I can try to perform a new minor release soon for this (and check a bit in what state we are). No promise though, as I'm on long term holiday 😉.

But maybe at one point this will allow me to fix a few things here. And if there are people willing to contribute, please do so!

**Comment by rsignell-usgs** [comment]
Thanks @guillaumeeb!   And I worked in Europe for a few years, I miss those long term holidays!

**Comment by jacobtomlinson** [comment]
@guillaumeeb I would be happy to handle a release here, but I'm not up to speed with the current state of `main`. Are things in a good state to release? If so I can take this on.

**Comment by guillaumeeb** [comment]
@jacobtomlinson there are not much changes here, I believe main is quite stable. I'm trying to release tonight. As I've not done that for a long time, and after tonight I won't have the availability, I leave it to you if I don't make it.

**Comment by jacobtomlinson** [comment]
Ok great. I'm happy to keep an eye on the tracker if there are any issues raised after the release.

**Comment by guillaumeeb** [comment]
Release done on Pypi, waiting for conda forge!

**Comment by jacobtomlinson** [comment]
Thanks @guillaumeeb

**Comment by guillaumeeb** [comment]
And finaly on conda-forge, I fell asleep before the conda-bot triggers the PR 😄
