### ISSUE TITLE
Replace --nprocs by --nworkers in the generated job script

### ISSUE THREAD

**Issue by ikabadzhov** [dask/dask-jobqueue#559]
When I want to create a SLURM cluster and specify `process = X ` in the constructor, by looking at the job script, I see that the command that is run has a flag `--nprocs X`.

That currently does not error. However, referring to https://docs.dask.org/en/stable/deploying-ssh.html#cmdoption-dask-ssh-nworkers `--nprocs` is deprecated.

I tried to pass as an `extra = ['--nworkers X']`, but then from another terminal I saw that my job got kicked from the squeue. And the terminal where I started the program, remains in a "wait state". I created a standalone SLURM script passing both `--nprocs` and `--nworkers`, but then I get: `ERROR - Both --nprocs and --nworkers were specified. Use --nworkers only.`

Request: would it be possible to translate the input of `process = ` in the SLURMCluster constructor to `--nworkers`, but not `--nprocs`.

**Comment by guillaumeeb** [comment]
Hi @ikabadzhov,

Thanks for opening this issue. This is a bit more general than SlurmCluster and affects every implementation. I actually thought I had opened an issue for this already, which is not the case.

This comes from https://github.com/dask/distributed/pull/5641.

So we should update dask-jobqueue to take this into account.

**Comment by guillaumeeb** [comment]
I modified the title of the issue to reflect what should be done. And maybe we should handle the previous kwarg for old Dask version, but I don't think this is really needed.

**Comment by ikabadzhov** [comment]
I took a closer look. I will give it a try now.
