### ISSUE TITLE
Cluster keeps appending "interface" flag to job script

### ISSUE THREAD

**Issue by theXYZT** [dask/dask-jobqueue#589]
When I run the following code snippet:

```python
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(memory="100GB", cores=40, interface="ib0")

for _ in range(20):
    _ = cluster.job_script()
    
print(cluster.job_script())
```

I get the following output:
```
#!/usr/bin/env bash

#SBATCH -J dask-worker
#SBATCH -n 1
#SBATCH --cpus-per-task=40
#SBATCH --mem=94G
#SBATCH -t 00:30:00

/path/to/python -m distributed.cli.dask_worker tcp://xx.xx.xx.xx:pppp --nthreads 5 --nworkers 8 --memory-limit 11.64GiB --name dummy-name --nanny --death-timeout 60 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0 --interface ib0
```
It seems everytime the job script method is called, the interface flag is appended to it. I am running `dask-jobqueue==0.8.0`  off the `conda-forge` channel. (Python 3.10 if relevant)

You can replicate this with `PBSCluster` as well. The issue seems to be in how `worker_extra_args` are handled in the `__init__()` method of `dask_jobqueue.core.Job`

**Comment by guillaumeeb** [comment]
Hi @theXYZT,

Good catch!

It seems that when we retrieve the `worker-extra-args` from `dask.config` (https://github.com/dask/dask-jobqueue/blob/main/dask_jobqueue/core.py#L226), as we don't make a copy, the object is kept in memory in `dask.config`, and so we retrieve the same object each time we construct a Job.

I'm not sure why yet, but this issue was not present in previous release (0.7.4) before we renamed `extra` in `worker-extra-args`.

I'll propose some fix, but I'd like to understand which change we made that lead to this result. cc @jolange if you have some idea.

@theXYZT does is causes errors on your system or is it just a visual problem?

**Comment by theXYZT** [comment]
I am not sure if this causes any problems currently. Although I use a few more worker-extra-args and all of them get duplicated quite a bit in the job script over time.

**Comment by jolange** [comment]
I did not notice this funny feature so far, thanks! From a quick look at the renaming diffs, I don't see what might have caused that, but if you are sure that it did not happen in the previous release, I will have a closer look later!

**Comment by guillaumeeb** [comment]
> From a quick look at the renaming diffs, I don't see what might have caused that

Neither do I, but I tested the problem on 0.7.4 and it did not behave that way. I admit I have no idea if this comes from the renaming or something else. It's ok if you don't have time, I just wanted to know if something strikes you.

**Comment by jolange** [comment]
Ok, this is a subtle combination of two things:
1) The one you noted: The config is assigned to `worker_extra_args`:
https://github.com/dask/dask-jobqueue/blob/f79f9136542abd86566e0a36f7370c144052ee9d/dask_jobqueue/core.py#L226-L228
2) In the [renaming](https://github.com/dask/dask-jobqueue/commit/96e39daaf7f5ba48df764cfed12eef9449b97323#diff-2b72fb950d6946ee9e2a90af40d1668cb8a2d149b9609be158820257726b27c4L242-L243), I changed from `X = X + NEW` to `X += NEW`:
```diff
         if interface:
-            extra = extra + ["--interface", interface]
+            worker_extra_args += ["--interface", interface]
```
This overwrites the config, whereas before `worker_extra_args` (or `extra` then) was newly assigned. I will revert that!

**Comment by guillaumeeb** [comment]
Nice catch and many thanks @jolange.
