### ISSUE TITLE
OARCluster implementation does not let OAR take into account the memory parameter

### ISSUE THREAD

**Issue by ychiat35** [dask/dask-jobqueue#594]
The current implementation of OARCluster does not let OAR take into account the memory parameter.

For example, if 256 GB are asked for Dask workers as memory, OAR is not aware about this memory request and thus the resources selected by OAR to compute the job might not have enough memory.

Consequently, specifying memory in OARCluster is counter-intuitive. As a Dask-Jobqueue user, we expect this parameter to be taken into account but in practice it is not.

**Comment by guillaumeeb** [comment]
Never used OAR, but it looks you're right! The only way to specify job memory is to use `resource_spec` (https://github.com/dask/dask-jobqueue/blob/main/dask_jobqueue/oar.py#L25). 

> Consequently, specifying memory in OARCluster is counter-intuitive. As a Dask-Jobqueue user, we expect this parameter to be taken into account but in practice it is not.

:+1:

**Comment by ychiat35** [comment]
Maybe @lesteve could help reviewing this pull request #595 ? Thanks in advance!

**Comment by guillaumeeb** [comment]
I don't think @lesteve has time to look at dask-jobqueue for the time being. But I'll have a look to your PR as soon as I can (following days I hope, but may be weeks, sorry).

**Comment by guillaumeeb** [comment]
Fixed in #595.
