### ISSUE TITLE
dask_jobqueue tries to import non-existent function dask.utils.ignoring

### ISSUE THREAD

**Issue by rjplevin** [dask/dask-jobqueue#600]
`ImportError: cannot import name 'ignoring' from 'dask.utils' (.../lib/python3.10/site-packages/dask/utils.py)`
```
.../site-packages/dask_jobqueue $ find . -name \*py -print0|xargs -0 fgrep -n ignoring
./core.py:13:from dask.utils import ignoring
```
dask.utils does not define ignoring().

**Environment**:

- Dask version: 2022.5.0
- dask-jobqueue 0.7.0
- Python version: 3.10.4
- Operating System: macos 12.6
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
I believe that was fixed in https://github.com/dask/dask-jobqueue/pull/503 which was included in the `dask-jobqueue=0.7.3` release

**Comment by rjplevin** [comment]
Thanks! The question now is why conda determined that 0.7.0 was the latest version compatible with my other requirements...

**Comment by guillaumeeb** [comment]
Hi @rjplevin, I'm going to close this issue as it is now more related to Conda environment problems rather than dask-jobqueue.

Dask-jobqueue has [not a lot of requirements](https://github.com/dask/dask-jobqueue/blob/main/requirements.txt), so not sure from where this might come.
