### ISSUE TITLE
Strange Worker KeyError when using LSFCluster.

### ISSUE THREAD

**Issue by austinbaggetta** [dask/dask-jobqueue#608]
Hi everyone! I'm new to HPC and I recently have been testing dask-jobqueue for my research needs. I've been using the Minerva HPC resource, which uses LSF to queue jobs. Very brief background (which I think is relevant) is that I am processing large videos (approximately 1.59TB), and our processing pipeline uses Dask to chunk the video data into manageable sizes across frames. At first I tried submitting my job using the following code:

```python
from dask.distributed import Client
from dask_jobqueue import LSFCluster

NUMB_JOBS = 1
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=48,
                     memory='120GB',
                     processes=1,
                     local_directory='path_to_local',
                     walltime='48:00',
                     interface='ib0')
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')
```

This seems to work; however, because Minerva is extensively used the queue time ended up being over 48 hours for the job to run. Trying this a few times, it can be anywhere from 24 to 72 hours before a single job begins running. My goal was to drastically decrease the wait time since the processing itself takes a while. On Minerva, one node has 48 cores, so I figured the reason for the extremely long wait times was because LSF had to wait for all jobs running on one node to finish before scheduling me on that node, which would be dependent on the number of jobs running and their length of time. So, I wanted to separate the analysis into multiple jobs. The code I used is below.

```python
NUMB_JOBS = 12
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=4,
                     memory='16GB',
                     processes=1,
                     local_directory='path_to_directory',
                     walltime='24:00',
                     interface='ib0')
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')
```

The code submits and everything runs fine for a while (I can load in the large video) until I start chunking the data to do a denoising and background removal step. I start receiving the following error (truncated for brevity, also changed the IPs to xxx.xx.xx.xxx since I'm unsure if I should be posting them on a forum lol. I kept the port IDs so it's clear that it's multiple workers):

KeyError: 'tcp://[xxx.xx.xx.xxx:38164](http://xxx.xx.xx.xxx:38164/)'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f15fef97550>, <Task finished name='Task-68840' coro=<BaseTCPListener._handle_stream() done, defined at /hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/comm/tcp.py:459> exception=KeyError('tcp://xxx.xx.xx.xxx:38164')>)
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/comm/tcp.py", line 476, in _handle_stream
    await self.comm_handler(comm)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 3603, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4666, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4576, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://[xxx.xx.xx.xxx:38164](http://xxx.xx.xx.xxx:38164/)'
distributed.core - ERROR - 'tcp://[xxx.xx.xx.xxx:34266](http://xxx.xx.xx.xxx:34266/)'
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4576, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://[xxx.xx.xx.xxx:34266](http://xxx.xx.xx.xxx:34266/)'
distributed.utils - ERROR - 'tcp://[xxx.xx.xx.xxx:34266](http://xxx.xx.xx.xxx:34266/)'
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/utils.py", line 655, in log_errors
    yield
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 3603, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4666, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4576, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://[xxx.xx.xx.xxx:34266](http://xxx.xx.xx.xxx:34266/)'
distributed.core - ERROR - Exception while handling op register-worker
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 3603, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4666, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4576, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://[xxx.xx.xx.xxx:34266](http://xxx.xx.xx.xxx:34266/)'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f15e9b18f70>, <Task finished name='Task-69112' coro=<BaseTCPListener._handle_stream() done, defined at /hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/comm/tcp.py:459> exception=KeyError('tcp://xxx.xx.xx.xxx:34266')>)
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/comm/tcp.py", line 476, in _handle_stream
    await self.comm_handler(comm)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 3603, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4666, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 4576, in handle_release_data
    ws: WorkerState = parent._workers_dv[worker]
KeyError: 'tcp://[xxx.xx.xx.xxx:34266](http://xxx.xx.xx.xxx:34266/)'
distributed.utils - ERROR - "('transpose-10cf9c1a738ecebcd64af0fd0195b71e', 3976, 0, 0)"
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/utils.py", line 655, in log_errors
    yield
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 3561, in add_worker
    typename=types[key],
KeyError: "('transpose-10cf9c1a738ecebcd64af0fd0195b71e', 3976, 0, 0)"
distributed.core - ERROR - Exception while handling op register-worker
Traceback (most recent call last):
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/scheduler.py", line 3561, in add_worker
    typename=types[key],
KeyError: "('transpose-10cf9c1a738ecebcd64af0fd0195b71e', 3976, 0, 0)"
Traceback (most recent call last):
  File "minian_minerva.py", line 250, in <module>
    varr = save_minian(
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/minian/utilities.py", line 524, in save_minian
    arr = ds.to_zarr(fp, compute=compute, mode=md)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/xarray/core/dataset.py", line 1745, in to_zarr
    return to_zarr(
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/xarray/backends/api.py", line 1482, in to_zarr
    writes = writer.sync(compute=compute)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/xarray/backends/common.py", line 155, in sync
    delayed_store = da.store(
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/dask/array/core.py", line 1022, in store
    result.compute(**kwargs)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/dask/base.py", line 281, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/dask/base.py", line 563, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/client.py", line 2655, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/client.py", line 1964, in gather
    return self.sync(
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/client.py", line 838, in sync
    return sync(
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/hpc/users/baggea01/.conda/envs/minian_multicon/lib/python3.8/site-packages/distributed/client.py", line 1829, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ("('xarray-session_id-0d10e0411e8b3d8ab1de65214e4cfd29', 10135)", <Worker 'tcp://[xxx.xx.xx.xxx:46000](http://xxx.xx.xx.xxx:46000/)', name: LSFCluster-6-1, memory: 0, processing: 784>)

I was searching through other error posts, and I came across these two which I think are certainly related:
https://github.com/dask/dask-jobqueue/issues/364 as well as this issue: https://github.com/dask/dask-jobqueue/issues/254

Based on the error and these posts, it seems that the workers can't communicate across nodes? Is there a workaround in dask-jobqueue to allow for this? Any and all help is greatly appreciated!

**Comment by guillaumeeb** [comment]
Hi @austinbaggetta,

It is a little hard to tell from where the error is comming just from this stacktrace. I'm a bit confused when you say:
> The code submits and everything runs fine for a while (I can load in the large video)

Maybe you could try to share a simple workflow reproducing this error?

> I was searching through other error posts, and I came across these two which I think are certainly related:
https://github.com/dask/dask-jobqueue/issues/364 as well as this issue: https://github.com/dask/dask-jobqueue/issues/254

I'm not sure I see the relation between these issues and this one. 

> Based on the error and these posts, it seems that the workers can't communicate across nodes? Is there a workaround in dask-jobqueue to allow for this? Any and all help is greatly appreciated!

Maybe you should try with some code example (like generating a random dask array and saving it to disk, or performing a global operation like a mean) if you are able to reproduce this error. You can configure the worker network interface through the `interface` kwarg if needed, but I'm not sure this is the issue.

**Comment by austinbaggetta** [comment]
Hi @guillaumeeb, thank you for your response! I took your advice and tried reproducing the error with a minimal code example. This is going to be a long post walking through my thought process, and hopefully it can be helpful to future users.

I first started by drastically reducing the amount of resources I was requesting and just simply computing the mean. This works fine. The job submits via dask-jobqueue and the mean is computed.

```python
import xarray as xr
import bottleneck
import numpy as np
from dask.distributed import Client
from dask_jobqueue import LSFCluster

def covariance_gufunc(x, y):
    return (
        (x - x.mean(axis=-1, keepdims=True)) * (y - y.mean(axis=-1, keepdims=True))
    ).mean(axis=-1)


def pearson_correlation_gufunc(x, y):
    return covariance_gufunc(x, y) / (x.std(axis=-1) * y.std(axis=-1))


def spearman_correlation_gufunc(x, y):
    x_ranks = bottleneck.rankdata(x, axis=-1)
    y_ranks = bottleneck.rankdata(y, axis=-1)
    return pearson_correlation_gufunc(x_ranks, y_ranks)


def spearman_correlation(x, y, dim):
    return xr.apply_ufunc(
        spearman_correlation_gufunc,
        x,
        y,
        input_core_dims=[[dim], [dim]],
        dask="parallelized",
        output_dtypes=[float],
    )

## Submit one job
NUMB_JOBS = 1
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=6,
                     memory='20GB',
                     processes=2,
                     local_directory='../spillage',
                     walltime='00:05',
                     interface='ib0')
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')
print('Starting...')
rs = np.random.RandomState(0)
array1 = xr.DataArray(rs.randn(1000, 100000),
                      dims=['place', 'time'])
array2 = array1 + 0.5 * rs.randn(1000, 100000)
print('Creating chunked arrays...')
chunked1 = array1.chunk({'place': 10})
chunked2 = array2.chunk({'place': 10})
print(chunked1.mean(dim='place'))
print('Finished!')
```

I next wanted to try calculating spearman correlations between the two chunked arrays using code from the xarray documentation. This also ran fine!

```python
## Submit one job
NUMB_JOBS = 1
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=6,
                     memory='20GB',
                     processes=2,
                     local_directory='../spillage',
                     walltime='00:05',
                     interface='ib0')
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')

print('Starting...')
rs = np.random.RandomState(0)
array1 = xr.DataArray(rs.randn(1000, 100000),
                      dims=['place', 'time'])
array2 = array1 + 0.5 * rs.randn(1000, 100000)
print('Creating chunked arrays...')
chunked1 = array1.chunk({'place': 10})
chunked2 = array2.chunk({'place': 10})
print('Computing spearman correlations...')
r = spearman_correlation(chunked1, chunked2, 'time').compute()
print('Finished!')
```

I then tried completing the task by submitting multiple smaller jobs across nodes. This also works fine, but I believe all the jobs were running on the same node. When I use the bjobs command, all jobs are on the same host.

```python
## Submit three jobs job
NUMB_JOBS = 3
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=2,
                     memory='10GB',
                     processes=1,
                     local_directory='../spillage',
                     walltime='00:05',
                     interface='ib0' )
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')

print('Starting...')
rs = np.random.RandomState(0)
array1 = xr.DataArray(rs.randn(1000, 100000),
                      dims=['place', 'time'])
array2 = array1 + 0.5 * rs.randn(1000, 100000)
print('Creating chunked arrays...')
chunked1 = array1.chunk({'place': 10})
chunked2 = array2.chunk({'place': 10})
print('Computing spearman correlations...')
r = spearman_correlation(chunked1, chunked2, 'time').compute()
print('Finished!')
```

I figured if workers distributed across nodes are unable to talk to each other (which is what I thought the original issue was, which is why I was resourcing those other two posts), then if I were to submit even more jobs to ensure that some are distributed across nodes then maybe it would error. However, this also ran fine. I also confirmed that jobs were distributed across different hosts.

```python
## Submit eight jobs
NUMB_JOBS = 8
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=2,
                     memory='10GB',
                     processes=1,
                     local_directory='../spillage',
                     walltime='00:05',
                     interface='ib0')
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')

print('Starting...')
rs = np.random.RandomState(0)
array1 = xr.DataArray(rs.randn(1000, 100000),
                      dims=['place', 'time'])
array2 = array1 + 0.5 * rs.randn(1000, 100000)
print('Creating chunked arrays...')
chunked1 = array1.chunk({'place': 10})
chunked2 = array2.chunk({'place': 10})
print('Computing spearman correlations...')
r = spearman_correlation(chunked1, chunked2, 'time').compute()
print('Finished!')
```

So I am a bit lost at this point. In regards to the original post, I tested all my preprocessing code on a small video (approximately 40 minutes) and it worked fine. It is only when I move to the much larger dataset (1.59TB, approximately 42 hours) that I have the error listed above, and I cannot figure out how to circumvent it. Is it simply a total memory issue?

I also don't know if this makes sense, but for these smaller tasks, is it possible that not all the workers across nodes are being used, and therefore there is no error? I imagine the dask dashboard would tell me whether some workers are simply remaining idle. Based on the dashboard, it appears that all workers have at least a small amount of memory usage, so that doesn't appear to be the issue either! Let me know what you think.

**Comment by guillaumeeb** [comment]
>  It is only when I move to the much larger dataset (1.59TB, approximately 42 hours) that I have the error listed above, and I cannot figure out how to circumvent it. Is it simply a total memory issue?

So this sounds like a scaling issue. Do you see other errors, or only key error? Aren't some workers dying from lack of memory? How many tasks is your workflow generating?

**Comment by austinbaggetta** [comment]
I decided to first try an intermediate sized video (approximately 8.5 hours) to see if I could work out the scaling issues.

```python
NUMB_JOBS = 10
cluster = LSFCluster(queue='premium', 
                     project='my_account',
                     cores=6,
                     memory='90GB',
                     processes=2,
                     local_directory='../spillage',
                     walltime='14:00',
                     interface='ib0',
                     nanny=True)
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
print(cluster.job_script())
print(f'> The dashboard link: {cluster.dashboard_link}')
chunk_size = 300 ## 300 MB, the size of each chunk in the dask array
```

Interestingly, I continued to get errors with this smaller set-up. At first I thought it was (again) a memory issue, but based on the worker logs it does not appear so. Strangely my computation would be running along, and suddenly one (or a few) workers would exhibit this error in their log:

distributed.worker - INFO - Threads: 3
distributed.worker - INFO - Memory: 45.00 GB
distributed.worker - INFO - Local Directory: ../spillage/dask-worker-space/worker-g77mah1j
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Registered to: tcp://xxx.xx.xx.xx:33319
distributed.worker - INFO - -------------------------------------------------
[Errno 2] No such file or directory: '../spillage/dask-worker-space/worker-g77mah1j/storage/%28%27xarray-session_id-cd57c71534262688054ba758a7944f44%27%2C%204155%29#0'

Another worker had this separate error in its log instead of the one above:
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Threads: 3
distributed.worker - INFO - Memory: 45.00 GB
distributed.worker - INFO - Local Directory: ../spillage/dask-worker-space/worker-epl4pu9d
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Registered to: tcp://xxx.xx.xx.xx:33319
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Failed to put key in memory Traceback (most recent call last):

Many of the times I've tried running this code the computation would keep running and eventually lead to an error that stopped the code from running. I am posting the killed worker error below (which would appear in the command window). 

distributed.scheduler.KilledWorker: ("('rechunk-store-45cb0202-1c16-11ee-88ed-7cd30a68ad58', 5975, 0, 0)", <Worker 'tcp://xxx.xx.xx.xxx:45876', name: LSFCluster-2-0, memory: 0, processing: 4448>)

Sometimes the scheduler will just appear to freeze as well (there are still tasks that haven't been completed, but all the sudden no tasks are being completed but no error has been raised. It just is frozen without finishing). The amount of tasks at this particular saving step is 111,620 tasks.

Strangely it doesn't always kill the worker at this step, and may kill the worker at another step later on when using the same function. I've been using our lab's open source calcium imaging analysis pipeline (https://minian.readthedocs.io/en/stable/), and the function where the errors occur I am posting below (I'm not sure if it's helpful). The error seems to occur when saving to a .zarr file using the xarray.DataArray.to_zarr method, which is making me think this isn't really a dask-jobqueue issue anymore?

```python
def save_minian(
    var: xr.DataArray,
    dpath: str,
    meta_dict: Optional[dict] = None,
    overwrite=False,
    chunks: Optional[dict] = None,
    compute=True,
    mem_limit="500MB",
) -> xr.DataArray:
    """
    Save a `xr.DataArray` with `zarr` storage backend following minian
    conventions.

    This function will store arbitrary `xr.DataArray` into `dpath` with `zarr`
    backend. A separate folder will be created under `dpath`, with folder name
    `var.name + ".zarr"`. Optionally metadata can be retrieved from directory
    hierarchy and added as coordinates of the `xr.DataArray`. In addition, an
    on-disk rechunking of the result can be performed using
    :func:`rechunker.rechunk` if `chunks` are given.

    Parameters
    ----------
    var : xr.DataArray
        The array to be saved.
    dpath : str
        The path to the minian dataset directory.
    meta_dict : dict, optional
        How metadata should be retrieved from directory hierarchy. The keys
        should be negative integers representing directory level relative to
        `dpath` (so `-1` means the immediate parent directory of `dpath`), and
        values should be the name of dimensions represented by the corresponding
        level of directory. The actual coordinate value of the dimensions will
        be the directory name of corresponding level. By default `None`.
    overwrite : bool, optional
        Whether to overwrite the result on disk. By default `False`.
    chunks : dict, optional
        A dictionary specifying the desired chunk size. The chunk size should be
        specified using :doc:`dask:array-chunks` convention, except the "auto"
        specifiication is not supported. The rechunking operation will be
        carried out with on-disk algorithms using :func:`rechunker.rechunk`. By
        default `None`.
    compute : bool, optional
        Whether to compute `var` and save it immediately. By default `True`.
    mem_limit : str, optional
        The memory limit for the on-disk rechunking algorithm, passed to
        :func:`rechunker.rechunk`. Only used if `chunks` is not `None`. By
        default `"500MB"`.

    Returns
    -------
    var : xr.DataArray
        The array representation of saving result. If `compute` is `True`, then
        the returned array will only contain delayed task of loading the on-disk
        `zarr` arrays. Otherwise all computation leading to the input `var` will
        be preserved in the result.

    Examples
    -------
    The following will save the variable `var` to directory
    `/spatial_memory/alpha/learning1/minian/important_array.zarr`, with the
    additional coordinates: `{"session": "learning1", "animal": "alpha",
    "experiment": "spatial_memory"}`.

    >>> save_minian(
    ...     var.rename("important_array"),
    ...     "/spatial_memory/alpha/learning1/minian",
    ...     {-1: "session", -2: "animal", -3: "experiment"},
    ... ) # doctest: +SKIP
    """
    dpath = os.path.normpath(dpath)
    Path(dpath).mkdir(parents=True, exist_ok=True)
    ds = var.to_dataset()
    if meta_dict is not None:
        pathlist = os.path.split(os.path.abspath(dpath))[0].split(os.sep)
        ds = ds.assign_coords(
            **dict([(dn, pathlist[di]) for dn, di in meta_dict.items()])
        )
    md = {True: "a", False: "w-"}[overwrite]
    fp = os.path.join(dpath, var.name + ".zarr")
    if overwrite:
        try:
            shutil.rmtree(fp)
        except FileNotFoundError:
            pass
    arr = ds.to_zarr(fp, compute=compute, mode=md)
    if (chunks is not None) and compute:
        chunks = {d: var.sizes[d] if v <= 0 else v for d, v in chunks.items()}
        dst_path = os.path.join(dpath, str(uuid4()))
        temp_path = os.path.join(dpath, str(uuid4()))
        with da.config.set(
            array_optimize=darr.optimization.optimize,
            delayed_optimize=default_delay_optimize,
        ):
            zstore = zr.open(fp)
            rechk = rechunker.rechunk(
                zstore[var.name], chunks, mem_limit, dst_path, temp_store=temp_path
            )
            rechk.execute()
        try:
            shutil.rmtree(temp_path)
        except FileNotFoundError:
            pass
        arr_path = os.path.join(fp, var.name)
        for f in os.listdir(arr_path):
            os.remove(os.path.join(arr_path, f))
        for f in os.listdir(dst_path):
            os.rename(os.path.join(dst_path, f), os.path.join(arr_path, f))
        os.rmdir(dst_path)
    if compute:
        arr = xr.open_zarr(fp)[var.name]
        arr.data = darr.from_zarr(os.path.join(fp, var.name), inline_array=True)
    return arr
```

If you think this error is better suited elsewhere I can totally move it to where it's appropriate! Thank you for your help.

**Comment by austinbaggetta** [comment]
In response to the freezing above, another worker had the following error:

distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Threads: 3
distributed.worker - INFO - Memory: 45.00 GB
distributed.worker - INFO - Local Directory: ../spillage/dask-worker-space/worker-ssnesyok
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Registered to: tcp://xxx.xx.xx.xxx:33319
distributed.worker - INFO - -------------------------------------------------
distributed.worker - ERROR - Worker stream died during communication: tcp://xxx.xx.xx.xxx:39901 Traceback (most recent call last):

**Comment by austinbaggetta** [comment]
I'm going to close this - I was setting the local_directory in the case that workers needed to spill to disk. Based on the dask-jobqueue documentation, a separate way to manage this is to not allow workers to spill to disk at all. By using the following code, it simply became a scaling issue (not requesting enough memory), and all these strange errors have disappeared. Thanks again for all your help!

```python
import dask
from dask.distributed import Client
from dask_jobqueue import LSFCluster

dask.config.set({'distributed.worker.memory.target': False})
dask.config.set({'distributed.worker.memory.spill': False})
dask.config.set({'distributed.worker.memory.pause': 0.80})
dask.config.set({'distributed.worker.memory.target': 0.95})

NUMB_JOBS = 30
cluster = LSFCluster(queue='premium', 
                     project='my_project',
                     cores=4,
                     memory='65GB',
                     processes=1,
                     walltime='23:00',
                     interface='ib0',
                     nanny=True)
cluster.scale(jobs=NUMB_JOBS)
client = Client(cluster)
```
