### ISSUE TITLE
SLURMCluster doesn't spawn new workers when old ones timeout

### ISSUE THREAD

**Issue by berkgercek** [dask/dask-jobqueue#611]
When spawning a SLURM cluster on dask-jobqueue, the cluster spawns workers as expected when `cluster.adapt(minimum_jobs=6, maximum_jobs=100)` is called. These workers continue to function as expected until they time out, however when the workers die (due to walltime limits on the job associated) the dask cluster does not spawn new workers to replace them.

```python
NCORES=4
GPU=True
WORKERS_PER_GPU=4
cluster = SLURMCluster(
    queue="shared-gpu" if GPU else "shared-cpu",
    cores=NCORES,
    processes=WORKERS_PER_GPU if GPU else 1,
    memory=f"{12 * WORKERS_PER_GPU}GB" if GPU else "12GB",
    walltime="06:15:00",
    log_directory="/home/gercek/dask-worker-logs",
    interface="ib0",
    job_script_prologue=[
        f"export OMP_NUM_THREADS={NCORES}",
        f"export MKL_NUM_THREADS={NCORES}",
        f"export OPENBLAS_NUM_THREADS={NCORES}",
        ],
    job_extra_directives=["--gpus=1"] if GPU else None,
)
daskclient = Client(cluster)

# Computation goes here, submitted to daskclient via daskclient.compute, and gathered via daskclient.gather
```

For me this is a case of unknown unknowns. I don't know where to look for the dask scheduler logs which would perhaps explain why the issue is happening. The worker logs are fine, and simply show that they were killed due to the cluster timeout.

**Environment**:

- Dask version: 2022.11.1
- Dask-Jobqueue version: 8.1
- Python version: 3.10.5
- Operating System: Rocky Linux, SLURM 23.02.1
- Install method (conda, pip, source): conda-forge

**Comment by ocaisa** [comment]
There's a long issue discussion on this at https://github.com/dask/dask-jobqueue/issues/122 (which hopefully includes a solution for you!)

**Comment by ocaisa** [comment]
See https://github.com/dask/dask-jobqueue/issues/122#issuecomment-626333697

**Comment by guillaumeeb** [comment]
@berkgercek, hopefully the links provided by @ocaisa should give you at least some workaround.

Other than that, I agree that in a simple case, with adaptive mode, new Workers should be started if some are lost. We should look at how this is handled in distributed repository.

**Comment by jacobtomlinson** [comment]
Just a note you should be able to get the scheduler logs with `cluster.get_logs()`.

**Comment by matrach** [comment]
It seems that that it should be possible to make the respawning workaround even with just `cluster.scale(n)` by calling:

```python
current = len(self.plan)
cluster.scale(jobs=len(cluster.scheduler.workers))
cluster.scale(current)
```

However, in the following code responsible for scaling:
https://github.com/dask/distributed/blob/a83d8727567dd3cdc7c6abdc7eda26d1029cd9de/distributed/deploy/spec.py#L512-L524

there is a mismatch between worker names (when using `processes > 1`):
- `set(self.worker_spec)` has keys without a suffix: `{'SLURMCluster-611', 'SLURMCluster-631'}`
- `v["name"] for v in self.scheduler_info["workers"].values()` has a suffix e.g., `{'SLURMCluster-592-1', 'SLURMCluster-592-0'}`

This mismatch seems to be also responsible for making `adapt` remove alive workers instead of the dead (`not_yet_connected` above).

**Comment by maawoo** [comment]
Spawning of new workers fails with:
```python
cluster.adapt(minimum_jobs=1, 
              maximum_jobs=2, 
              worker_key=lambda state: state.address.split(':')[0], 
              interval='10s')
``` 

It works however when using the following (assuming that each job would spawn 4 workers):
```python
cluster.adapt(minimum=1, 
              maximum=8, 
              worker_key=lambda state: state.address.split(':')[0],  
              interval='10s')
```

Removing `worker_key` and `interval` will result in the endless loop of spawning and killing workers as described in https://github.com/dask/dask-jobqueue/issues/498

**Comment by guillaumeeb** [comment]
@matrach you are right about the mismatch in the distributed code in the specific case where we want to scale down not yet launched workers. However I'm not sure how this relates to this problem were we want to respawn dead workers?

@maawoo the link to your code is dead for me. Considering the second part, cluster.adapt(minimum_jobs=1, maximum_jobs=2) will be translated in cluster.adapt(minimum=4, maximum=8), which probably causes the issue.

It's important to stress that adaptive mode is known to have issues with dask-jobqueue when starting several Worker processes per job. 

Getting back at the original problem, I just tested the following code using dask 2023.6.0:
```python
import time
import numpy as np
from dask_jobqueue import SLURMCluster as Cluster
from dask import delayed
from dask.distributed import Client, as_completed

cluster = Cluster(walltime='00:01:00', cores=1, memory='4gb', account="campus")
cluster.adapt(minimum=2, maximum=4) # FIX

client = Client(cluster)
```

And I see new workers being created as soon as older ones dies, without performing any computations.

I'm going to close this issue as the more specific problems are covered by other ones.

**Comment by matrach** [comment]
> @matrach you are right about the mismatch in the distributed code in the specific case where we want to scale down not yet launched workers. However I'm not sure how this relates to this problem were we want to respawn dead workers?

I've never mentioned such a case. The issue was (is?) that the variable name `not_yet_connected` doesn't contain what it states to: with this naming mismatch it always contained all of the workers. Even without the mismatch, it would contain both "not yet connected" and "already dead" workers.

```python
            not_yet_launched = set(self.worker_spec) - {
                v["name"] for v in self.scheduler_info["workers"].values()
            }
            while len(self.worker_spec) > n and not_yet_launched:
                del self.worker_spec[not_yet_launched.pop()]
```                

But, `set.pop()` is allowed to return arbitrary element. Thus an implementation starting from the newest entries might always start from "not yet connected" instead of "already dead" workers.

**Comment by guillaumeeb** [comment]
> I've never mentioned such a case

What I meant was that it is another issue, or is it not?
