### ISSUE TITLE
conftest.py not included in PyPI source tarball

### ISSUE THREAD

**Issue by bcbnz** [dask/dask-jobqueue#612]
**Describe the issue**: The source tarball on PyPI does not include conftest.py. This makes it impossible to run the tests as they depend on the custom markers, fixtures etc defined in that file.

**Minimal Complete Verifiable Example**:

```bash
$ wget https://files.pythonhosted.org/packages/ff/b2/2367d1ef1e6f1f5dec33b549f8f465780f14d33df5ba6eb11239ea8d4b4b/dask-jobqueue-0.8.2.tar.gz
$ tar --list -f dask-jobqueue-0.8.2.tar.gz conftest.py
tar: conftest.py: Not found in archive
tar: Exiting with failure status due to previous errors
```

**Comment by jacobtomlinson** [comment]
I'm always interested in the debate on whether you should package your tests or not. @bcbnz you seem to have a case for packaging them, could you expand a little on why you want to run the tests from the source tarball and why that is useful to you?

**Comment by jacobtomlinson** [comment]
Closing due to lack of response
