### ISSUE TITLE
ImportError on ignoring attribute from dask.utils when importing dask_jobqueue

### ISSUE THREAD

**Issue by stfnrnn** [dask/dask-jobqueue#615]
**Description**:

When trying to use dask_jobqueue version 0.8.2 in an environment with Dask version 2023.6.0 (or also with version 2023.9.0), I encountered an ImportError. The traceback indicates that dask_jobqueue is trying to import the ignoring attribute from dask.utils, but this attribute doesn't seem present in the specified Dask versions.

**Expected Behavior**:

The dask_jobqueue module should be imported without any errors.

**Actual Behavior**:

Received the following error:
ImportError: cannot import name 'ignoring' from 'dask.utils' (/path/to/site-packages/dask/utils.py)

**Minimal Complete Verifiable Example**:

```bash
conda create --name dask_env python=3.9
conda activate dask_env
conda install dask=2023.6.0 -c conda-forge
conda install dask-jobqueue -c conda-forge
```

```python
import dask-jobqueue
```

**Additional context**:

I've checked the meta.yaml for dask-jobqueue 0.8.2 and found that it specifies a dependency on dask-core >=2022.02.0. However, even after aligning with these versions, the error persists. I'd appreciate guidance on the compatible versions or a potential fix for this issue. Thanks a lot

**Environment**:

- Dask version:  Tried both 2023.6.0 or 2023.9.0
- Dask-jobqueue version: 0.8.2
- Python version: 3.9.18
- Conda version: 23.9.0
- Operating System: Linux
- Install method (conda, pip, source): conda-forge

**Comment by guillaumeeb** [comment]
Hi @stfnrnn,

I've follow the provided MCVE, but I cannot reproduce the issue. Everything is working fine for me.

Could you print the entire stacktrace?

**Comment by stfnrnn** [comment]
Hi @guillaumeeb, thanks a lot for your reply! I can't reproduce the issue anymore, and it seems to be solved now. Thanks a lot for your time anyway. I am closing it now.
