### ISSUE TITLE
Add a `py.typed` marker

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [dask/dask-jobqueue#617]
I am developing a package that uses `dask-jobqueue`, and when I use `mypy` for type checking, it complains that there is no `py.typed` marker for `dask-jobqueue`. Perhaps one should be added, as [described here](https://peps.python.org/pep-0561/).

**Comment by guillaumeeb** [comment]
Hi @Andrew-S-Rosen, sorry for the delay.

I'm really not familiar with this, but any PR is welcome if well justified and not intrusive here!
