### ISSUE TITLE
passing options to submit and cancel commands

### ISSUE THREAD

**Issue by apatlpo** [dask/dask-jobqueue#65]
Wouldn't it be useful to be able to pass options to submit and cancel commands ?

For example, I would like to stop receiving job deletions emails on a PBS cluster and one way to doing this is to pass ` -Wsuppress_email=-1` option to `qdel`

If yes, what would be a good way to do this?

**Comment by jhamman** [comment]
I agree, this would be nice. 

Short term, this may work for you:

```Python
cluster = PBSCluster()
cluster.cancel_command = 'qdel -Wsuppress_email=-1'
client = Client(cluster)
...
```

Maybe this is straightforward enough that we don't need to do anything further?

**Comment by apatlpo** [comment]
Thanks, if nobody else is interested in this, there is probably no need for anything else.

Minor detail, in turns out that on PBS, it's at submission that you turn off emails:

```
cluster = PBSCluster(local_directory=local_dir)
cluster.submit_command = 'qsub -m n'
...
```

**Comment by guillaumeeb** [comment]
Yes, you can probably do this using the `job_extra` keyword:
```python
cluster = PBSCluster(..., job_extra=['-m n'])
```

**Comment by lesteve** [comment]
I guess we could add `submit_command_additional_args='', cancel_command_additional_args=''` to `JobQueueCluster.__init__`. This additional arguments would be added to the command we run in `start_workers` and `stop_workers`.

**Comment by guillaumeeb** [comment]
Perfect!
