### ISSUE TITLE
Failing with SGE

### ISSUE THREAD

**Issue by ericmjl** [dask/dask-jobqueue#69]
I would like to try using dask-jobqueue to set up a Dask cluster on our internal Grid Engine cluster (I believe it is UGE, not SGE, but they should be siblings of each other).

My script is below:

```python
# dask_sge_test.py
from dask_jobqueue.sge import SGECluster
cluster = SGECluster(queue='regular')
```

The error is below:
```
$ python dask_sge_test.py
Traceback (most recent call last):
  File "dask_sge_test.py", line 1, in <module>
    from dask_jobqueue.sge import SGECluster
  File "/home/maer3/anaconda/envs/tm-sleep/lib/python3.6/site-packages/dask_jobqueue/__init__.py", line 2, in <module>
    from .core import JobQueueCluster
  File "/home/maer3/anaconda/envs/tm-sleep/lib/python3.6/site-packages/dask_jobqueue/core.py", line 11, in <module>
    from distributed.deploy import Cluster
ImportError: cannot import name 'Cluster'
```

I did some checking in an IPython session:

```python
In [9]: import distributed

In [10]: 'Cluster' in distributed.deploy.__dict__.keys()
Out[10]: False
```

Not sure why this is happening, I dug into the `distributed` Python module, and found everything set up correctly: under `deploy/__init__.py`, I see `from .cluster import Cluster`, so the name is available.

**Comment by mrocklin** [comment]
git-master of dask-jobqueue depends on git-master of distributed which also depends on git-master of dask

A release of all three should be out within a week

**Comment by ericmjl** [comment]
@mrocklin I had installed this using conda-forge; is the git commit version still a relevant point here?

**Comment by mrocklin** [comment]
Not sure when Cluster was added, but it's there now

```python
In [1]: import distributed

In [2]: 'Cluster' in distributed.deploy.__dict__.keys()
Out[2]: True
```

So my guess is that there is some version mismatch here.  If you just conda installed everything then that's surprising.

**Comment by ericmjl** [comment]
Yes, that is quite surprising. What was even more surprising for me was that when I dug into `site-packages/distributed`, `Cluster` was imported into `deploy`. 

```bash
$ pwd
/home/maer3/anaconda/envs/tm-sleep/lib/python3.6/site-packages/distributed/deploy
$ cat __init__.py | grep Cluster
from .cluster import Cluster
from .local import LocalCluster
    from .ssh import SSHCluster
$ cat cluster.py | grep Cluster
class Cluster(object):
    Clusters inheriting from this class should provide the following:
    >>> from distributed.deploy import Cluster
    >>> class MyCluster(cluster):
    >>> cluster = MyCluster()
    LocalCluster: a simple implementation with local workers
        Cluster.scale_up
        Cluster.scale_down
```

Let me check version numbers:

```bash
$ conda list | grep distributed
distributed               1.21.8                   py36_0    conda-forge
$ conda list | grep dask-jobqueue
dask-jobqueue             0.1.1                      py_0    conda-forge
```

**Comment by mrocklin** [comment]
In your situation I would either install from git across all three
packages, or else wait a day or two.

**Comment by ericmjl** [comment]
👍

**Comment by ericmjl** [comment]
As things turn out, there was a legacy `~/.local/...` in my PYTHONPATH that was interfering with everything! Big lesson learned.

Btw, thank you for teaching me the PDB tricks at PyCon, @mrocklin! :smile:

**Comment by mrocklin** [comment]
A worthwhile investment it seems :)

**Comment by mrocklin** [comment]
OK to close @ericmjl ?

**Comment by ericmjl** [comment]
Closing!
