### ISSUE TITLE
Assumption made about location of dask-worker

### ISSUE THREAD

**Issue by ocaisa** [dask/dask-jobqueue#75]
In https://github.com/dask/dask-jobqueue/blob/774f2610f7e7befd44e04d972c42e299b942fa5e/dask_jobqueue/core.py#L15
the assumption is made that the `dask-worker` script is in the same place as the python executable. This is not true in our case since dask is available through an environment module (so the availability of the script is handled via the `$PATH` envvar).

Would it be possible to add a check before https://github.com/dask/dask-jobqueue/blob/774f2610f7e7befd44e04d972c42e299b942fa5e/dask_jobqueue/core.py#L127 to verify that this default actually exists and, if not, use the location found in `$PATH` (otherwise die gracefully)? Something like
```
if not os.path.isfile(os.path.join(dirname, 'dask-worker'):
    if os.path.isfile(os.path.abspath('dask-worker'):
        dirname = os.path.join(os.path.abspath('dask-worker'), '..')
    else:
        # Trigger a graceful death
```

**Comment by mrocklin** [comment]
Perhaps we should include a keyword argument executable=our_default_value
but allow other people to overwrite it?

**Comment by lesteve** [comment]
Or use `python -m distributed.cli.dask_worker` as was done in `dask-drmaa` [here](https://github.com/dask/dask-drmaa/pull/91)? I think the context in dask-drmaa was that `dask-worker` was not found in a user install of dask.

**Comment by ocaisa** [comment]
@lesteve That seems like a clean solution and would work for us

**Comment by ocaisa** [comment]
PR #77 tested for our system (feel free to replace it with something else)
