### ISSUE TITLE
RuntimeWarning: Couldn't detect a suitable IP address

### ISSUE THREAD

**Issue by rabernat** [dask/dask-jobqueue#85]
I am starting a cluster like this:
```python
cluster = PBSCluster(processes=5, threads=4, memory="0.2",
                     interface="ib0",
                     group_list='g26209',
                     resource_spec='select=1:ncpus=20:mpiprocs=5:model=ivy',
                     walltime='06:00:00')
```

I receive the following warning:
```
/nobackup/rpaberna/conda/envs/pangeo/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
```

Do I need to be concerned about this?

**Comment by guillaumeeb** [comment]
It probably means that you don't have access to internet on the node your launching your scheduler, so nothing to worry about if the dask-jobqueue is working properly.

In your exemple above, I'm surprised about your `memory="0.2"` arg. What's the result?
Is the `mpiprocs=5` necessary too?

**Comment by guillaumeeb** [comment]
@rabernat OK to close this?
