### ISSUE TITLE
Build example blog/screencast on JupyterHub enabled system

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#96]
Dask-jobqueue seems to be having an impact in a number of deployments.  A lightning talk at SciPy seemed to kindle a surprising amount of activity.  We're showing a path that people can take to use their HPC systems for interactive development.  

Taking this further, we would like for these same systems how they can use JupyterHub to remove the current ssh-in, launch Jupyter, ssh-tunnel process.  This would likely smooth over the user experience even more.  I was talking to @joestubbs from TACC today and they have JupyterHub running on an HPC SLURM system today.  It might be useful to collaborate on a blogpots or short video that shows the advantages of such a system.

**Comment by mrocklin** [comment]
@minrk might also know other JupyterHub BatchSpawner users that might be willing to participate.

**Comment by guillaumeeb** [comment]
I'm working currently on deploying a JupyterHub with BatchSpawner on CNES PBS cluster. Let me know if I can help in any way: giving advice, config, installation steps... We're at the beginning right now, but hopefully I'll have something more consistent in a few weeks.

**Comment by mrocklin** [comment]
You may be interested in
https://github.com/jupyterhub/batchspawner/issues/101

**Comment by ocaisa** [comment]
We actually used JupyterHub with `dask-jobqueue` in a recent tutorial for [JURECA](http://www.fz-juelich.de/ias/jsc/EN/Expertise/Supercomputers/JURECA/Configuration/Configuration_node.html). I had little experience with JupyterHub prior to that. The ease of introduction with JupyterHub was great but JupyterHub itself was a little unstable when the number of users increased (that might well be a local problem).

**Comment by guillaumeeb** [comment]
@mrocklin , I think you and @jhamman provided some nice response to this issue, see http://blog.dask.org/2018/10/08/Dask-Jobqueue and the video in it (which is also on dask-jobqueue documentation landing page).

So I'm closing this one.
