### ISSUE TITLE
Dask resource_spec does not generalize to older version of PBS

### ISSUE THREAD

**Issue by halexand** [dask/dask-jobqueue#99]
Hello, 

While trying to use Dask-Jobqueue on my local HPC (running PBS 6.1.2) I am having problems getting the PBS cluster call to properly define the resources I have requested. It seems that the issue might lie with the `resource_spec` call. I specify the `resource_spec` as I have previously specified `-l nodes=4:ppn=4:mem=4gb` in a PBS script (below) I get the following error:
```
cluster = PBSCluster(processes=4,
    ...:                      threads=4, memory="4GB",
    ...:                      name="TestRun",
    ...:                      resource_spec='nodes=4:ppn=4:mem=4gb',
    ...:                      walltime='24:00:00', 
    ...:                      jobextra='-A ged -m abe', )
cluster.start_workers(3)
```
> ERROR:dask_jobqueue.core:qsub: submit error (Command syntax invalid MSG=Invalid 

If I run it as shown in the documentation there is no error-- but the memory and node allocations are not what I specified. It would appear that our system does not support or recognize`select=1:ncpus=24`.

Thank you!

**Comment by jhamman** [comment]
@halexand - thank you for this report. Can you share a sample pbs script that dask-jobqueue creates and a link to your system's documentation?

To see the job script, you can do:

```Python
print(cluster.job_script())
```

**Comment by guillaumeeb** [comment]
Looks like you got a quite old PBS version! It's using old style keywords apparently, so it is not surprising it does not work as expected with our PBSCluster implementation.

The use of resource_spec seems a good idea, that may work. As @jhamman asked, it would be easier to analyse your problem if you could give us the generated job script.

Currently it looks like PBS is receiving options it doesn't like when you specify resource_spec.

**Comment by chaoxue-sysu** [comment]
> Hello,
> 
> While trying to use Dask-Jobqueue on my local HPC (running PBS 6.1.2) I am having problems getting the PBS cluster call to properly define the resources I have requested. It seems that the issue might lie with the `resource_spec` call. I specify the `resource_spec` as I have previously specified `-l nodes=4:ppn=4:mem=4gb` in a PBS script (below) I get the following error:
> 
> ```
> cluster = PBSCluster(processes=4,
>     ...:                      threads=4, memory="4GB",
>     ...:                      name="TestRun",
>     ...:                      resource_spec='nodes=4:ppn=4:mem=4gb',
>     ...:                      walltime='24:00:00', 
>     ...:                      jobextra='-A ged -m abe', )
> cluster.start_workers(3)
> ```
> 
> > ERROR:dask_jobqueue.core:qsub: submit error (Command syntax invalid MSG=Invalid
> 
> If I run it as shown in the documentation there is no error-- but the memory and node allocations are not what I specified. It would appear that our system does not support or recognize`select=1:ncpus=24`.
> 
> Thank you!

I recently got the same error in PBS system. I found that, if I seperate the resource parameter 'cpu' and 'memory', it will work. i.e.,
 ```bash
#PBS -l nodes=4:ppn=4 
 #PBS -l mem=4gb
```

**Comment by jacobtomlinson** [comment]
As a workaround you could move the memory option into the `jobextra` section. _(It looks like `jobextra` [expects a list](
https://github.com/dask/dask-jobqueue/blob/master/dask_jobqueue/pbs.py#L97))._

```python
cluster = PBSCluster(processes=4,
                     threads=4, memory="4GB",
                     name="TestRun",
                     resource_spec='nodes=4:ppn=4',
                     walltime='24:00:00', 
                     jobextra=['-A ged', '-m abe', '-l mem=4gb'],)
cluster.start_workers(3)
```

**Comment by guillaumeeb** [comment]
Thanks for the added information @chaoxue-sysu. Did you by chance tested the solution proposed by @jacobtomlinson?
